version = 1
SPDX-PackageName = "sap-build-forms-extension"
SPDX-PackageSupplier = "ospo@sap.com"
SPDX-PackageDownloadLocation = "https://github.com/SAP/sap-build-forms-extension"
npmnbbbbSPDX-FileCopyrightText = "2026 SAP SE or an SAP affiliate company and sap-build-forms-extension contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 SAP SE or an SAP affiliate company and sap-build-forms-extension contributors"
SPDX-License-Identifier = [
    "Apache-2.0",
    "MIT",
    "CDDL-1.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "EPL-2.0",
    "EPL-1.0",
    "ISC"
]