package com.sap.bfx.security.oidc;

import com.sap.bfx.security.Constants;
import com.sap.bfx.utils.AbstractCookieHandler;
import jakarta.servlet.http.Cookie;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.security.web.savedrequest.DefaultSavedRequest;
import org.springframework.security.web.savedrequest.RequestCache;
import org.springframework.security.web.savedrequest.SavedRequest;
import org.springframework.stereotype.Component;

import java.util.*;

/**
 * A custom implementation of RequestCache that stores the saved request in a cookie.
 * This class extends AbstractCookieHandler to handle cookie operations and implements the RequestCache
 * interface to manage SavedRequest objects.
 */
@Component
public class RedisRequestCache extends AbstractCookieHandler implements RequestCache {

    private final RedisTemplate<String, SimpleSavedRequest> redis;

    /**
     * Constructs a RedisRequestCache with the provided RedisTemplate.
     *
     * @param redis the RedisTemplate used for storing and retrieving SimpleSavedRequest objects
     */
    @Autowired
    public RedisRequestCache(
            @Qualifier("request-cache-redis-template") RedisTemplate<String, SimpleSavedRequest> redis) {
        this.redis = redis;
    }

    @Override
    public void saveRequest(HttpServletRequest request, HttpServletResponse response) {
        // Capture the standard request state generated by Spring Security
        final var savedRequest =
                new DefaultSavedRequest(request, new org.springframework.security.web.PortResolverImpl());

        // Extract a lightweight subset to prevent exceeding cookie size limits
        final var simpleRequest = new SimpleSavedRequest(savedRequest.getRedirectUrl(), savedRequest.getMethod());
        final var id = StringUtils.remove(UUID.randomUUID().toString(), '-');
        redis.boundValueOps(id).set(simpleRequest, Constants.TEMP_TIMEOUT);

        // Serialize and Base64 encode the payload
        this.addCookie(request, response, Constants.AUTH_REQUEST_COOKIE_NAME, id, true, true, Constants.TEMP_TIMEOUT);
    }

    @Override
    public SavedRequest getRequest(HttpServletRequest request, HttpServletResponse response) {
        final var cookie = AbstractCookieHandler.getCookie(request, Constants.AUTH_REQUEST_COOKIE_NAME);
        if (cookie == null || cookie.getValue().isEmpty()) {
            return null;
        }

        // Decode and deserialize back into the lightweight model
        final var simpleRequest = redis.boundValueOps(cookie.getValue()).get();
        if (simpleRequest == null) {
            return null;
        }
        // Reconstruct a standard SavedRequest compliance wrapper
        return new ReconstructedSavedRequest(simpleRequest.redirectUrl, simpleRequest.method);
    }

    @Override
    public HttpServletRequest getMatchingRequest(HttpServletRequest request, HttpServletResponse response) {
        SavedRequest savedRequest = getRequest(request, response);
        if (savedRequest == null) {
            return null;
        }

        // Check if the current request matches the cached destination
        if (request.getRequestURI().equals(savedRequest.getRedirectUrl())) {
            removeRequest(request, response);
            return request;
        }
        return null;
    }

    @Override
    public void removeRequest(HttpServletRequest request, HttpServletResponse response) {
        // Clear the state by evicting the cookie tracking key
        addCookie(request, response, Constants.AUTH_REQUEST_COOKIE_NAME, "", true, true, 0);
    }

    /**
     * Lightweight Internal Data Model
     */
    @NoArgsConstructor
    @AllArgsConstructor
    @Data
    public static class SimpleSavedRequest {
        private String redirectUrl;
        private String method;
    }

    /**
     * Minimal Compliance Wrapper for Spring Security API
     */
    @AllArgsConstructor
    @Data
    private static class ReconstructedSavedRequest implements SavedRequest {
        private String redirectUrl;
        private String method;

        // Stub standard collections to satisfy the interface blueprint safely
        @Override
        public List<Cookie> getCookies() {
            return Collections.emptyList();
        }

        @Override
        public Collection<String> getHeaderNames() {
            return Collections.emptyList();
        }

        @Override
        public List<String> getHeaderValues(String name) {
            return Collections.emptyList();
        }

        //        public java.util.Collection<String> getParameterNames() {
        //            return java.util.Collections.emptyList();
        //        }

        @Override
        public String[] getParameterValues(String name) {
            return new String[0];
        }

        @Override
        public Map<String, String[]> getParameterMap() {
            return Collections.emptyMap();
        }

        @Override
        public List<Locale> getLocales() {
            return Collections.emptyList();
        }
    }
}