<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="icon" type="image/x-icon" href="./assets/${favicon}"/>
    <title>Login</title>
    <style>
	</style>
</head>


<body style="border: 0; margin: 0; padding: 0">
<div id="root" style="background-color: #f5f6f7; width: 100vw; height: 100vh;">
	Logged in...
</div>
</body>
</html>
