

/*
 * User Management (System for Cross-domain Identity Management (SCIM))
 * Provides functions to administrate the Authorization and Trust Management service (XSUAA) of SAP BTP, Cloud Foundry environment. You can provision users from identity providers and manage roles and role collections. Use this API to manage shadow users; users the service provisions from your identity provider to the subaccount. For more information, see [Switch Off Automatic Creation of Shadow Users](https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/d8525671e8b14147b96ef497e1e1af80.html). The System for Cross-domain Identity Management (SCIM) interfaces for users and groups supplement the relevant UAA [users](https://docs.cloudfoundry.org/api/uaa/version/74.0.0/index.html#users)and [groups](https://docs.cloudfoundry.org/api/uaa/version/74.0.0/index.html#groups) interfaces. Groups in the Authorization and Trust Management service are mapped to role collections. See also [SAP Note 2760424]( https://launchpad.support.sap.com/#/notes/2760424). To enable access to this API, create an OAuth 2.0 client for the XSUAA service instance. To create the client, enable the apiaccess plan. For more information, see [Access UAA Admin APIs](https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/ebc9113a520e495ea5fb759b9a7929f2.html).
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.openapi.scim.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * Approval
 */
// CHECKSTYLE:OFF
public class Approval 
// CHECKSTYLE:ON
{
  @JsonProperty("clientId")
  private String clientId;

  @JsonProperty("expiresAt")
  private OffsetDateTime expiresAt;

  @JsonProperty("lastUpdatedAt")
  private OffsetDateTime lastUpdatedAt;

  @JsonProperty("scope")
  private String scope;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    /**
    * The APPROVED option of this Approval
    */
    APPROVED("APPROVED"),
    
    /**
    * The DENIED option of this Approval
    */
    DENIED("DENIED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    /**
    * Get the value of the enum
    * @return The enum value
    */
    @JsonValue
    @Nonnull public String getValue() {
      return value;
    }

    /**
    * Get the String value of the enum value.
    * @return The enum value as String
    */
    @Override
    @Nonnull public String toString() {
      return String.valueOf(value);
    }

    /**
    * Get the enum value from a String value
    * @param value The String value
    * @return The enum value of type Approval
    */
    @JsonCreator
    @Nonnull public static StatusEnum fromValue(@Nonnull final String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  @JsonProperty("status")
  private StatusEnum status;

  @JsonProperty("userId")
  private String userId;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /**
   * Set the clientId of this {@link Approval} instance and return the same instance.
   *
   * @param clientId  The client id on the approval. Represents the application this approval or denial was for.
   * @return The same instance of this {@link Approval} class
   */
  @Nonnull public Approval clientId( @Nullable final String clientId) {
    this.clientId = clientId;
    return this;
  }

  /**
   * The client id on the approval. Represents the application this approval or denial was for.
   * @return clientId  The clientId of this {@link Approval} instance.
   */
  @Nonnull
  public String getClientId() {
    return clientId;
  }

  /**
   * Set the clientId of this {@link Approval} instance.
   *
   * @param clientId  The client id on the approval. Represents the application this approval or denial was for.
   */
  public void setClientId( @Nullable final String clientId) {
    this.clientId = clientId;
  }

  /**
   * Set the expiresAt of this {@link Approval} instance and return the same instance.
   *
   * @param expiresAt  The expiresAt of this {@link Approval}
   * @return The same instance of this {@link Approval} class
   */
  @Nonnull public Approval expiresAt( @Nullable final OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

  /**
   * Get expiresAt
   * @return expiresAt  The expiresAt of this {@link Approval} instance.
   */
  @Nonnull
  public OffsetDateTime getExpiresAt() {
    return expiresAt;
  }

  /**
   * Set the expiresAt of this {@link Approval} instance.
   *
   * @param expiresAt  The expiresAt of this {@link Approval}
   */
  public void setExpiresAt( @Nullable final OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
  }

  /**
   * Set the lastUpdatedAt of this {@link Approval} instance and return the same instance.
   *
   * @param lastUpdatedAt  The lastUpdatedAt of this {@link Approval}
   * @return The same instance of this {@link Approval} class
   */
  @Nonnull public Approval lastUpdatedAt( @Nullable final OffsetDateTime lastUpdatedAt) {
    this.lastUpdatedAt = lastUpdatedAt;
    return this;
  }

  /**
   * Get lastUpdatedAt
   * @return lastUpdatedAt  The lastUpdatedAt of this {@link Approval} instance.
   */
  @Nonnull
  public OffsetDateTime getLastUpdatedAt() {
    return lastUpdatedAt;
  }

  /**
   * Set the lastUpdatedAt of this {@link Approval} instance.
   *
   * @param lastUpdatedAt  The lastUpdatedAt of this {@link Approval}
   */
  public void setLastUpdatedAt( @Nullable final OffsetDateTime lastUpdatedAt) {
    this.lastUpdatedAt = lastUpdatedAt;
  }

  /**
   * Set the scope of this {@link Approval} instance and return the same instance.
   *
   * @param scope  The scope of this {@link Approval}
   * @return The same instance of this {@link Approval} class
   */
  @Nonnull public Approval scope( @Nullable final String scope) {
    this.scope = scope;
    return this;
  }

  /**
   * Get scope
   * @return scope  The scope of this {@link Approval} instance.
   */
  @Nonnull
  public String getScope() {
    return scope;
  }

  /**
   * Set the scope of this {@link Approval} instance.
   *
   * @param scope  The scope of this {@link Approval}
   */
  public void setScope( @Nullable final String scope) {
    this.scope = scope;
  }

  /**
   * Set the status of this {@link Approval} instance and return the same instance.
   *
   * @param status  The status of this {@link Approval}
   * @return The same instance of this {@link Approval} class
   */
  @Nonnull public Approval status( @Nullable final StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status  The status of this {@link Approval} instance.
   */
  @Nonnull
  public StatusEnum getStatus() {
    return status;
  }

  /**
   * Set the status of this {@link Approval} instance.
   *
   * @param status  The status of this {@link Approval}
   */
  public void setStatus( @Nullable final StatusEnum status) {
    this.status = status;
  }

  /**
   * Set the userId of this {@link Approval} instance and return the same instance.
   *
   * @param userId  The ID of the user.
   * @return The same instance of this {@link Approval} class
   */
  @Nonnull public Approval userId( @Nullable final String userId) {
    this.userId = userId;
    return this;
  }

  /**
   * The ID of the user.
   * @return userId  The userId of this {@link Approval} instance.
   */
  @Nonnull
  public String getUserId() {
    return userId;
  }

  /**
   * Set the userId of this {@link Approval} instance.
   *
   * @param userId  The ID of the user.
   */
  public void setUserId( @Nullable final String userId) {
    this.userId = userId;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link Approval}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link Approval} instance.
   * @deprecated Use {@link #toMap()} instead.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField( @Nonnull final String name ) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("Approval has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link Approval} instance including unrecognized properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap()
  {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if( clientId != null ) declaredFields.put("clientId", clientId);
    if( expiresAt != null ) declaredFields.put("expiresAt", expiresAt);
    if( lastUpdatedAt != null ) declaredFields.put("lastUpdatedAt", lastUpdatedAt);
    if( scope != null ) declaredFields.put("scope", scope);
    if( status != null ) declaredFields.put("status", status);
    if( userId != null ) declaredFields.put("userId", userId);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link Approval} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final Approval approval = (Approval) o;
    return Objects.equals(this.cloudSdkCustomFields, approval.cloudSdkCustomFields) &&
        Objects.equals(this.clientId, approval.clientId) &&
        Objects.equals(this.expiresAt, approval.expiresAt) &&
        Objects.equals(this.lastUpdatedAt, approval.lastUpdatedAt) &&
        Objects.equals(this.scope, approval.scope) &&
        Objects.equals(this.status, approval.status) &&
        Objects.equals(this.userId, approval.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientId, expiresAt, lastUpdatedAt, scope, status, userId, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class Approval {\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    lastUpdatedAt: ").append(toIndentedString(lastUpdatedAt)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

