

/*
 * User Management (System for Cross-domain Identity Management (SCIM))
 * Provides functions to administrate the Authorization and Trust Management service (XSUAA) of SAP BTP, Cloud Foundry environment. You can provision users from identity providers and manage roles and role collections. Use this API to manage shadow users; users the service provisions from your identity provider to the subaccount. For more information, see [Switch Off Automatic Creation of Shadow Users](https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/d8525671e8b14147b96ef497e1e1af80.html). The System for Cross-domain Identity Management (SCIM) interfaces for users and groups supplement the relevant UAA [users](https://docs.cloudfoundry.org/api/uaa/version/74.0.0/index.html#users)and [groups](https://docs.cloudfoundry.org/api/uaa/version/74.0.0/index.html#groups) interfaces. Groups in the Authorization and Trust Management service are mapped to role collections. See also [SAP Note 2760424]( https://launchpad.support.sap.com/#/notes/2760424). To enable access to this API, create an OAuth 2.0 client for the XSUAA service instance. To create the client, enable the apiaccess plan. For more information, see [Access UAA Admin APIs](https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/ebc9113a520e495ea5fb759b9a7929f2.html).
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.openapi.scim.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * AuthorizationError
 */
// CHECKSTYLE:OFF
public class AuthorizationError 
// CHECKSTYLE:ON
{
  @JsonProperty("error")
  private String error;

  @JsonProperty("error_description")
  private String errorDescription;

  @JsonProperty("scope")
  private String scope;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /**
   * Set the error of this {@link AuthorizationError} instance and return the same instance.
   *
   * @param error  The error of this {@link AuthorizationError}
   * @return The same instance of this {@link AuthorizationError} class
   */
  @Nonnull public AuthorizationError error( @Nullable final String error) {
    this.error = error;
    return this;
  }

  /**
   * Get error
   * @return error  The error of this {@link AuthorizationError} instance.
   */
  @Nonnull
  public String getError() {
    return error;
  }

  /**
   * Set the error of this {@link AuthorizationError} instance.
   *
   * @param error  The error of this {@link AuthorizationError}
   */
  public void setError( @Nullable final String error) {
    this.error = error;
  }

  /**
   * Set the errorDescription of this {@link AuthorizationError} instance and return the same instance.
   *
   * @param errorDescription  The errorDescription of this {@link AuthorizationError}
   * @return The same instance of this {@link AuthorizationError} class
   */
  @Nonnull public AuthorizationError errorDescription( @Nullable final String errorDescription) {
    this.errorDescription = errorDescription;
    return this;
  }

  /**
   * Get errorDescription
   * @return errorDescription  The errorDescription of this {@link AuthorizationError} instance.
   */
  @Nonnull
  public String getErrorDescription() {
    return errorDescription;
  }

  /**
   * Set the errorDescription of this {@link AuthorizationError} instance.
   *
   * @param errorDescription  The errorDescription of this {@link AuthorizationError}
   */
  public void setErrorDescription( @Nullable final String errorDescription) {
    this.errorDescription = errorDescription;
  }

  /**
   * Set the scope of this {@link AuthorizationError} instance and return the same instance.
   *
   * @param scope  The scope of this {@link AuthorizationError}
   * @return The same instance of this {@link AuthorizationError} class
   */
  @Nonnull public AuthorizationError scope( @Nullable final String scope) {
    this.scope = scope;
    return this;
  }

  /**
   * Get scope
   * @return scope  The scope of this {@link AuthorizationError} instance.
   */
  @Nonnull
  public String getScope() {
    return scope;
  }

  /**
   * Set the scope of this {@link AuthorizationError} instance.
   *
   * @param scope  The scope of this {@link AuthorizationError}
   */
  public void setScope( @Nullable final String scope) {
    this.scope = scope;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link AuthorizationError}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link AuthorizationError} instance.
   * @deprecated Use {@link #toMap()} instead.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField( @Nonnull final String name ) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("AuthorizationError has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link AuthorizationError} instance including unrecognized properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap()
  {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if( error != null ) declaredFields.put("error", error);
    if( errorDescription != null ) declaredFields.put("errorDescription", errorDescription);
    if( scope != null ) declaredFields.put("scope", scope);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link AuthorizationError} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final AuthorizationError authorizationError = (AuthorizationError) o;
    return Objects.equals(this.cloudSdkCustomFields, authorizationError.cloudSdkCustomFields) &&
        Objects.equals(this.error, authorizationError.error) &&
        Objects.equals(this.errorDescription, authorizationError.errorDescription) &&
        Objects.equals(this.scope, authorizationError.scope);
  }

  @Override
  public int hashCode() {
    return Objects.hash(error, errorDescription, scope, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class AuthorizationError {\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    errorDescription: ").append(toIndentedString(errorDescription)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

