

/*
 * User Management (System for Cross-domain Identity Management (SCIM))
 * Provides functions to administrate the Authorization and Trust Management service (XSUAA) of SAP BTP, Cloud Foundry environment. You can provision users from identity providers and manage roles and role collections. Use this API to manage shadow users; users the service provisions from your identity provider to the subaccount. For more information, see [Switch Off Automatic Creation of Shadow Users](https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/d8525671e8b14147b96ef497e1e1af80.html). The System for Cross-domain Identity Management (SCIM) interfaces for users and groups supplement the relevant UAA [users](https://docs.cloudfoundry.org/api/uaa/version/74.0.0/index.html#users)and [groups](https://docs.cloudfoundry.org/api/uaa/version/74.0.0/index.html#groups) interfaces. Groups in the Authorization and Trust Management service are mapped to role collections. See also [SAP Note 2760424]( https://launchpad.support.sap.com/#/notes/2760424). To enable access to this API, create an OAuth 2.0 client for the XSUAA service instance. To create the client, enable the apiaccess plan. For more information, see [Access UAA Admin APIs](https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/ebc9113a520e495ea5fb759b9a7929f2.html).
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.openapi.scim.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sap.openapi.scim.model.Approval;
import com.sap.openapi.scim.model.Email;
import com.sap.openapi.scim.model.Group;
import com.sap.openapi.scim.model.Name;
import com.sap.openapi.scim.model.PhoneNumber;
import com.sap.openapi.scim.model.ScimMeta;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * ScimUser
 */
// CHECKSTYLE:OFF
public class ScimUser 
// CHECKSTYLE:ON
{
  @JsonProperty("id")
  private String id;

  @JsonProperty("externalId")
  private String externalId;

  @JsonProperty("meta")
  private ScimMeta meta;

  @JsonProperty("userName")
  private String userName;

  @JsonProperty("name")
  private Name name;

  @JsonProperty("emails")
  private List<Email> emails = new ArrayList<>();

  @JsonProperty("groups")
  private List<Group> groups = new ArrayList<>();

  @JsonProperty("approvals")
  private List<Approval> approvals = new ArrayList<>();

  @JsonProperty("active")
  private Boolean active;

  @JsonProperty("verified")
  private Boolean verified;

  @JsonProperty("origin")
  private String origin;

  @JsonProperty("zoneId")
  private String zoneId;

  @JsonProperty("displayName")
  private String displayName;

  @JsonProperty("locale")
  private String locale;

  @JsonProperty("nickName")
  private String nickName;

  @JsonProperty("passwordLastModified")
  private OffsetDateTime passwordLastModified;

  @JsonProperty("previousLogonTime")
  private Long previousLogonTime;

  @JsonProperty("lastLogonTime")
  private Long lastLogonTime;

  @JsonProperty("schemas")
  private List<String> schemas = new ArrayList<>();

  @JsonProperty("phoneNumbers")
  private List<PhoneNumber> phoneNumbers = new ArrayList<>();

  @JsonProperty("preferredLanguage")
  private String preferredLanguage;

  @JsonProperty("profileUrl")
  private String profileUrl;

  @JsonProperty("salt")
  private String salt;

  @JsonProperty("timezone")
  private String timezone;

  @JsonProperty("title")
  private String title;

  @JsonProperty("userType")
  private String userType;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /**
   * Set the id of this {@link ScimUser} instance and return the same instance.
   *
   * @param id  The user ID of a SCIM user.
   * @return The same instance of this {@link ScimUser} class
   */
  @Nonnull public ScimUser id( @Nullable final String id) {
    this.id = id;
    return this;
  }

  /**
   * The user ID of a SCIM user.
   * @return id  The id of this {@link ScimUser} instance.
   */
  @Nonnull
  public String getId() {
    return id;
  }

  /**
   * Set the id of this {@link ScimUser} instance.
   *
   * @param id  The user ID of a SCIM user.
   */
  public void setId( @Nullable final String id) {
    this.id = id;
  }

  /**
   * Set the externalId of this {@link ScimUser} instance and return the same instance.
   *
   * @param externalId  The externalId of this {@link ScimUser}
   * @return The same instance of this {@link ScimUser} class
   */
  @Nonnull public ScimUser externalId( @Nullable final String externalId) {
    this.externalId = externalId;
    return this;
  }

  /**
   * Get externalId
   * @return externalId  The externalId of this {@link ScimUser} instance.
   */
  @Nonnull
  public String getExternalId() {
    return externalId;
  }

  /**
   * Set the externalId of this {@link ScimUser} instance.
   *
   * @param externalId  The externalId of this {@link ScimUser}
   */
  public void setExternalId( @Nullable final String externalId) {
    this.externalId = externalId;
  }

  /**
   * Set the meta of this {@link ScimUser} instance and return the same instance.
   *
   * @param meta  The meta of this {@link ScimUser}
   * @return The same instance of this {@link ScimUser} class
   */
  @Nonnull public ScimUser meta( @Nullable final ScimMeta meta) {
    this.meta = meta;
    return this;
  }

  /**
   * Get meta
   * @return meta  The meta of this {@link ScimUser} instance.
   */
  @Nonnull
  public ScimMeta getMeta() {
    return meta;
  }

  /**
   * Set the meta of this {@link ScimUser} instance.
   *
   * @param meta  The meta of this {@link ScimUser}
   */
  public void setMeta( @Nullable final ScimMeta meta) {
    this.meta = meta;
  }

  /**
   * Set the userName of this {@link ScimUser} instance and return the same instance.
   *
   * @param userName  The userName of this {@link ScimUser}
   * @return The same instance of this {@link ScimUser} class
   */
  @Nonnull public ScimUser userName( @Nullable final String userName) {
    this.userName = userName;
    return this;
  }

  /**
   * Get userName
   * @return userName  The userName of this {@link ScimUser} instance.
   */
  @Nonnull
  public String getUserName() {
    return userName;
  }

  /**
   * Set the userName of this {@link ScimUser} instance.
   *
   * @param userName  The userName of this {@link ScimUser}
   */
  public void setUserName( @Nullable final String userName) {
    this.userName = userName;
  }

  /**
   * Set the name of this {@link ScimUser} instance and return the same instance.
   *
   * @param name  The name of this {@link ScimUser}
   * @return The same instance of this {@link ScimUser} class
   */
  @Nonnull public ScimUser name( @Nullable final Name name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name  The name of this {@link ScimUser} instance.
   */
  @Nonnull
  public Name getName() {
    return name;
  }

  /**
   * Set the name of this {@link ScimUser} instance.
   *
   * @param name  The name of this {@link ScimUser}
   */
  public void setName( @Nullable final Name name) {
    this.name = name;
  }

  /**
   * Set the emails of this {@link ScimUser} instance and return the same instance.
   *
   * @param emails  The emails of this {@link ScimUser}
   * @return The same instance of this {@link ScimUser} class
   */
  @Nonnull public ScimUser emails( @Nullable final List<Email> emails) {
    this.emails = emails;
    return this;
  }
  /**
   * Add one emails instance to this {@link ScimUser}.
   * @param emailsItem The emails that should be added
   * @return The same instance of type {@link ScimUser}
   */
  @Nonnull public ScimUser addEmailsItem( @Nonnull final Email emailsItem) {
    if (this.emails == null) {
      this.emails = new ArrayList<>();
    }
    this.emails.add(emailsItem);
    return this;
  }

  /**
   * Get emails
   * @return emails  The emails of this {@link ScimUser} instance.
   */
  @Nonnull
  public List<Email> getEmails() {
    return emails;
  }

  /**
   * Set the emails of this {@link ScimUser} instance.
   *
   * @param emails  The emails of this {@link ScimUser}
   */
  public void setEmails( @Nullable final List<Email> emails) {
    this.emails = emails;
  }

  /**
   * Set the groups of this {@link ScimUser} instance and return the same instance.
   *
   * @param groups  The groups of this {@link ScimUser}
   * @return The same instance of this {@link ScimUser} class
   */
  @Nonnull public ScimUser groups( @Nullable final List<Group> groups) {
    this.groups = groups;
    return this;
  }
  /**
   * Add one groups instance to this {@link ScimUser}.
   * @param groupsItem The groups that should be added
   * @return The same instance of type {@link ScimUser}
   */
  @Nonnull public ScimUser addGroupsItem( @Nonnull final Group groupsItem) {
    if (this.groups == null) {
      this.groups = new ArrayList<>();
    }
    this.groups.add(groupsItem);
    return this;
  }

  /**
   * Get groups
   * @return groups  The groups of this {@link ScimUser} instance.
   */
  @Nonnull
  public List<Group> getGroups() {
    return groups;
  }

  /**
   * Set the groups of this {@link ScimUser} instance.
   *
   * @param groups  The groups of this {@link ScimUser}
   */
  public void setGroups( @Nullable final List<Group> groups) {
    this.groups = groups;
  }

  /**
   * Set the approvals of this {@link ScimUser} instance and return the same instance.
   *
   * @param approvals  A list of approval decisions made by this user. Approvals record the user&#39;s explicit approval or rejection for an application&#39;s request for delegated permissions.
   * @return The same instance of this {@link ScimUser} class
   */
  @Nonnull public ScimUser approvals( @Nullable final List<Approval> approvals) {
    this.approvals = approvals;
    return this;
  }
  /**
   * Add one approvals instance to this {@link ScimUser}.
   * @param approvalsItem The approvals that should be added
   * @return The same instance of type {@link ScimUser}
   */
  @Nonnull public ScimUser addApprovalsItem( @Nonnull final Approval approvalsItem) {
    if (this.approvals == null) {
      this.approvals = new ArrayList<>();
    }
    this.approvals.add(approvalsItem);
    return this;
  }

  /**
   * A list of approval decisions made by this user. Approvals record the user&#39;s explicit approval or rejection for an application&#39;s request for delegated permissions.
   * @return approvals  The approvals of this {@link ScimUser} instance.
   */
  @Nonnull
  public List<Approval> getApprovals() {
    return approvals;
  }

  /**
   * Set the approvals of this {@link ScimUser} instance.
   *
   * @param approvals  A list of approval decisions made by this user. Approvals record the user&#39;s explicit approval or rejection for an application&#39;s request for delegated permissions.
   */
  public void setApprovals( @Nullable final List<Approval> approvals) {
    this.approvals = approvals;
  }

  /**
   * Set the active of this {@link ScimUser} instance and return the same instance.
   *
   * @param active  The active of this {@link ScimUser}
   * @return The same instance of this {@link ScimUser} class
   */
  @Nonnull public ScimUser active( @Nullable final Boolean active) {
    this.active = active;
    return this;
  }

  /**
   * Get active
   * @return active  The active of this {@link ScimUser} instance.
   */
  @Nonnull
  public Boolean isActive() {
    return active;
  }

  /**
   * Set the active of this {@link ScimUser} instance.
   *
   * @param active  The active of this {@link ScimUser}
   */
  public void setActive( @Nullable final Boolean active) {
    this.active = active;
  }

  /**
   * Set the verified of this {@link ScimUser} instance and return the same instance.
   *
   * @param verified  The verified of this {@link ScimUser}
   * @return The same instance of this {@link ScimUser} class
   */
  @Nonnull public ScimUser verified( @Nullable final Boolean verified) {
    this.verified = verified;
    return this;
  }

  /**
   * Get verified
   * @return verified  The verified of this {@link ScimUser} instance.
   */
  @Nonnull
  public Boolean isVerified() {
    return verified;
  }

  /**
   * Set the verified of this {@link ScimUser} instance.
   *
   * @param verified  The verified of this {@link ScimUser}
   */
  public void setVerified( @Nullable final Boolean verified) {
    this.verified = verified;
  }

  /**
   * Set the origin of this {@link ScimUser} instance and return the same instance.
   *
   * @param origin  The identity provider hosting the users. For the default identity provider, use sap.default. Subaccounts created before October 2020 return ldap as the default identity provider. The system accepts both sap.default and ldap for the default identity provider, but returns sap.default or ldap depending on when the subaccount was created.
   * @return The same instance of this {@link ScimUser} class
   */
  @Nonnull public ScimUser origin( @Nullable final String origin) {
    this.origin = origin;
    return this;
  }

  /**
   * The identity provider hosting the users. For the default identity provider, use sap.default. Subaccounts created before October 2020 return ldap as the default identity provider. The system accepts both sap.default and ldap for the default identity provider, but returns sap.default or ldap depending on when the subaccount was created.
   * @return origin  The origin of this {@link ScimUser} instance.
   */
  @Nonnull
  public String getOrigin() {
    return origin;
  }

  /**
   * Set the origin of this {@link ScimUser} instance.
   *
   * @param origin  The identity provider hosting the users. For the default identity provider, use sap.default. Subaccounts created before October 2020 return ldap as the default identity provider. The system accepts both sap.default and ldap for the default identity provider, but returns sap.default or ldap depending on when the subaccount was created.
   */
  public void setOrigin( @Nullable final String origin) {
    this.origin = origin;
  }

  /**
   * Set the zoneId of this {@link ScimUser} instance and return the same instance.
   *
   * @param zoneId  The zoneId of this {@link ScimUser}
   * @return The same instance of this {@link ScimUser} class
   */
  @Nonnull public ScimUser zoneId( @Nullable final String zoneId) {
    this.zoneId = zoneId;
    return this;
  }

  /**
   * Get zoneId
   * @return zoneId  The zoneId of this {@link ScimUser} instance.
   */
  @Nonnull
  public String getZoneId() {
    return zoneId;
  }

  /**
   * Set the zoneId of this {@link ScimUser} instance.
   *
   * @param zoneId  The zoneId of this {@link ScimUser}
   */
  public void setZoneId( @Nullable final String zoneId) {
    this.zoneId = zoneId;
  }

  /**
   * Set the displayName of this {@link ScimUser} instance and return the same instance.
   *
   * @param displayName  The displayName of this {@link ScimUser}
   * @return The same instance of this {@link ScimUser} class
   */
  @Nonnull public ScimUser displayName( @Nullable final String displayName) {
    this.displayName = displayName;
    return this;
  }

  /**
   * Get displayName
   * @return displayName  The displayName of this {@link ScimUser} instance.
   */
  @Nonnull
  public String getDisplayName() {
    return displayName;
  }

  /**
   * Set the displayName of this {@link ScimUser} instance.
   *
   * @param displayName  The displayName of this {@link ScimUser}
   */
  public void setDisplayName( @Nullable final String displayName) {
    this.displayName = displayName;
  }

  /**
   * Set the locale of this {@link ScimUser} instance and return the same instance.
   *
   * @param locale  The locale of this {@link ScimUser}
   * @return The same instance of this {@link ScimUser} class
   */
  @Nonnull public ScimUser locale( @Nullable final String locale) {
    this.locale = locale;
    return this;
  }

  /**
   * Get locale
   * @return locale  The locale of this {@link ScimUser} instance.
   */
  @Nonnull
  public String getLocale() {
    return locale;
  }

  /**
   * Set the locale of this {@link ScimUser} instance.
   *
   * @param locale  The locale of this {@link ScimUser}
   */
  public void setLocale( @Nullable final String locale) {
    this.locale = locale;
  }

  /**
   * Set the nickName of this {@link ScimUser} instance and return the same instance.
   *
   * @param nickName  The nickName of this {@link ScimUser}
   * @return The same instance of this {@link ScimUser} class
   */
  @Nonnull public ScimUser nickName( @Nullable final String nickName) {
    this.nickName = nickName;
    return this;
  }

  /**
   * Get nickName
   * @return nickName  The nickName of this {@link ScimUser} instance.
   */
  @Nonnull
  public String getNickName() {
    return nickName;
  }

  /**
   * Set the nickName of this {@link ScimUser} instance.
   *
   * @param nickName  The nickName of this {@link ScimUser}
   */
  public void setNickName( @Nullable final String nickName) {
    this.nickName = nickName;
  }

  /**
   * Set the passwordLastModified of this {@link ScimUser} instance and return the same instance.
   *
   * @param passwordLastModified  The passwordLastModified of this {@link ScimUser}
   * @return The same instance of this {@link ScimUser} class
   */
  @Nonnull public ScimUser passwordLastModified( @Nullable final OffsetDateTime passwordLastModified) {
    this.passwordLastModified = passwordLastModified;
    return this;
  }

  /**
   * Get passwordLastModified
   * @return passwordLastModified  The passwordLastModified of this {@link ScimUser} instance.
   */
  @Nonnull
  public OffsetDateTime getPasswordLastModified() {
    return passwordLastModified;
  }

  /**
   * Set the passwordLastModified of this {@link ScimUser} instance.
   *
   * @param passwordLastModified  The passwordLastModified of this {@link ScimUser}
   */
  public void setPasswordLastModified( @Nullable final OffsetDateTime passwordLastModified) {
    this.passwordLastModified = passwordLastModified;
  }

  /**
   * Set the previousLogonTime of this {@link ScimUser} instance and return the same instance.
   *
   * @param previousLogonTime  The previousLogonTime of this {@link ScimUser}
   * @return The same instance of this {@link ScimUser} class
   */
  @Nonnull public ScimUser previousLogonTime( @Nullable final Long previousLogonTime) {
    this.previousLogonTime = previousLogonTime;
    return this;
  }

  /**
   * Get previousLogonTime
   * @return previousLogonTime  The previousLogonTime of this {@link ScimUser} instance.
   */
  @Nonnull
  public Long getPreviousLogonTime() {
    return previousLogonTime;
  }

  /**
   * Set the previousLogonTime of this {@link ScimUser} instance.
   *
   * @param previousLogonTime  The previousLogonTime of this {@link ScimUser}
   */
  public void setPreviousLogonTime( @Nullable final Long previousLogonTime) {
    this.previousLogonTime = previousLogonTime;
  }

  /**
   * Set the lastLogonTime of this {@link ScimUser} instance and return the same instance.
   *
   * @param lastLogonTime  The lastLogonTime of this {@link ScimUser}
   * @return The same instance of this {@link ScimUser} class
   */
  @Nonnull public ScimUser lastLogonTime( @Nullable final Long lastLogonTime) {
    this.lastLogonTime = lastLogonTime;
    return this;
  }

  /**
   * Get lastLogonTime
   * @return lastLogonTime  The lastLogonTime of this {@link ScimUser} instance.
   */
  @Nonnull
  public Long getLastLogonTime() {
    return lastLogonTime;
  }

  /**
   * Set the lastLogonTime of this {@link ScimUser} instance.
   *
   * @param lastLogonTime  The lastLogonTime of this {@link ScimUser}
   */
  public void setLastLogonTime( @Nullable final Long lastLogonTime) {
    this.lastLogonTime = lastLogonTime;
  }

  /**
   * Set the schemas of this {@link ScimUser} instance and return the same instance.
   *
   * @param schemas  The schemas of this {@link ScimUser}
   * @return The same instance of this {@link ScimUser} class
   */
  @Nonnull public ScimUser schemas( @Nullable final List<String> schemas) {
    this.schemas = schemas;
    return this;
  }
  /**
   * Add one schemas instance to this {@link ScimUser}.
   * @param schemasItem The schemas that should be added
   * @return The same instance of type {@link ScimUser}
   */
  @Nonnull public ScimUser addSchemasItem( @Nonnull final String schemasItem) {
    if (this.schemas == null) {
      this.schemas = new ArrayList<>();
    }
    this.schemas.add(schemasItem);
    return this;
  }

  /**
   * Get schemas
   * @return schemas  The schemas of this {@link ScimUser} instance.
   */
  @Nonnull
  public List<String> getSchemas() {
    return schemas;
  }

  /**
   * Set the schemas of this {@link ScimUser} instance.
   *
   * @param schemas  The schemas of this {@link ScimUser}
   */
  public void setSchemas( @Nullable final List<String> schemas) {
    this.schemas = schemas;
  }

  /**
   * Set the phoneNumbers of this {@link ScimUser} instance and return the same instance.
   *
   * @param phoneNumbers  The phoneNumbers of this {@link ScimUser}
   * @return The same instance of this {@link ScimUser} class
   */
  @Nonnull public ScimUser phoneNumbers( @Nullable final List<PhoneNumber> phoneNumbers) {
    this.phoneNumbers = phoneNumbers;
    return this;
  }
  /**
   * Add one phoneNumbers instance to this {@link ScimUser}.
   * @param phoneNumbersItem The phoneNumbers that should be added
   * @return The same instance of type {@link ScimUser}
   */
  @Nonnull public ScimUser addPhoneNumbersItem( @Nonnull final PhoneNumber phoneNumbersItem) {
    if (this.phoneNumbers == null) {
      this.phoneNumbers = new ArrayList<>();
    }
    this.phoneNumbers.add(phoneNumbersItem);
    return this;
  }

  /**
   * Get phoneNumbers
   * @return phoneNumbers  The phoneNumbers of this {@link ScimUser} instance.
   */
  @Nonnull
  public List<PhoneNumber> getPhoneNumbers() {
    return phoneNumbers;
  }

  /**
   * Set the phoneNumbers of this {@link ScimUser} instance.
   *
   * @param phoneNumbers  The phoneNumbers of this {@link ScimUser}
   */
  public void setPhoneNumbers( @Nullable final List<PhoneNumber> phoneNumbers) {
    this.phoneNumbers = phoneNumbers;
  }

  /**
   * Set the preferredLanguage of this {@link ScimUser} instance and return the same instance.
   *
   * @param preferredLanguage  The preferredLanguage of this {@link ScimUser}
   * @return The same instance of this {@link ScimUser} class
   */
  @Nonnull public ScimUser preferredLanguage( @Nullable final String preferredLanguage) {
    this.preferredLanguage = preferredLanguage;
    return this;
  }

  /**
   * Get preferredLanguage
   * @return preferredLanguage  The preferredLanguage of this {@link ScimUser} instance.
   */
  @Nonnull
  public String getPreferredLanguage() {
    return preferredLanguage;
  }

  /**
   * Set the preferredLanguage of this {@link ScimUser} instance.
   *
   * @param preferredLanguage  The preferredLanguage of this {@link ScimUser}
   */
  public void setPreferredLanguage( @Nullable final String preferredLanguage) {
    this.preferredLanguage = preferredLanguage;
  }

  /**
   * Set the profileUrl of this {@link ScimUser} instance and return the same instance.
   *
   * @param profileUrl  The profileUrl of this {@link ScimUser}
   * @return The same instance of this {@link ScimUser} class
   */
  @Nonnull public ScimUser profileUrl( @Nullable final String profileUrl) {
    this.profileUrl = profileUrl;
    return this;
  }

  /**
   * Get profileUrl
   * @return profileUrl  The profileUrl of this {@link ScimUser} instance.
   */
  @Nonnull
  public String getProfileUrl() {
    return profileUrl;
  }

  /**
   * Set the profileUrl of this {@link ScimUser} instance.
   *
   * @param profileUrl  The profileUrl of this {@link ScimUser}
   */
  public void setProfileUrl( @Nullable final String profileUrl) {
    this.profileUrl = profileUrl;
  }

  /**
   * Set the salt of this {@link ScimUser} instance and return the same instance.
   *
   * @param salt  The salt of this {@link ScimUser}
   * @return The same instance of this {@link ScimUser} class
   */
  @Nonnull public ScimUser salt( @Nullable final String salt) {
    this.salt = salt;
    return this;
  }

  /**
   * Get salt
   * @return salt  The salt of this {@link ScimUser} instance.
   */
  @Nonnull
  public String getSalt() {
    return salt;
  }

  /**
   * Set the salt of this {@link ScimUser} instance.
   *
   * @param salt  The salt of this {@link ScimUser}
   */
  public void setSalt( @Nullable final String salt) {
    this.salt = salt;
  }

  /**
   * Set the timezone of this {@link ScimUser} instance and return the same instance.
   *
   * @param timezone  The timezone of this {@link ScimUser}
   * @return The same instance of this {@link ScimUser} class
   */
  @Nonnull public ScimUser timezone( @Nullable final String timezone) {
    this.timezone = timezone;
    return this;
  }

  /**
   * Get timezone
   * @return timezone  The timezone of this {@link ScimUser} instance.
   */
  @Nonnull
  public String getTimezone() {
    return timezone;
  }

  /**
   * Set the timezone of this {@link ScimUser} instance.
   *
   * @param timezone  The timezone of this {@link ScimUser}
   */
  public void setTimezone( @Nullable final String timezone) {
    this.timezone = timezone;
  }

  /**
   * Set the title of this {@link ScimUser} instance and return the same instance.
   *
   * @param title  The title of this {@link ScimUser}
   * @return The same instance of this {@link ScimUser} class
   */
  @Nonnull public ScimUser title( @Nullable final String title) {
    this.title = title;
    return this;
  }

  /**
   * Get title
   * @return title  The title of this {@link ScimUser} instance.
   */
  @Nonnull
  public String getTitle() {
    return title;
  }

  /**
   * Set the title of this {@link ScimUser} instance.
   *
   * @param title  The title of this {@link ScimUser}
   */
  public void setTitle( @Nullable final String title) {
    this.title = title;
  }

  /**
   * Set the userType of this {@link ScimUser} instance and return the same instance.
   *
   * @param userType  The userType of this {@link ScimUser}
   * @return The same instance of this {@link ScimUser} class
   */
  @Nonnull public ScimUser userType( @Nullable final String userType) {
    this.userType = userType;
    return this;
  }

  /**
   * Get userType
   * @return userType  The userType of this {@link ScimUser} instance.
   */
  @Nonnull
  public String getUserType() {
    return userType;
  }

  /**
   * Set the userType of this {@link ScimUser} instance.
   *
   * @param userType  The userType of this {@link ScimUser}
   */
  public void setUserType( @Nullable final String userType) {
    this.userType = userType;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link ScimUser}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link ScimUser} instance.
   * @deprecated Use {@link #toMap()} instead.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField( @Nonnull final String name ) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("ScimUser has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link ScimUser} instance including unrecognized properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap()
  {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if( id != null ) declaredFields.put("id", id);
    if( externalId != null ) declaredFields.put("externalId", externalId);
    if( meta != null ) declaredFields.put("meta", meta);
    if( userName != null ) declaredFields.put("userName", userName);
    if( name != null ) declaredFields.put("name", name);
    if( emails != null ) declaredFields.put("emails", emails);
    if( groups != null ) declaredFields.put("groups", groups);
    if( approvals != null ) declaredFields.put("approvals", approvals);
    if( active != null ) declaredFields.put("active", active);
    if( verified != null ) declaredFields.put("verified", verified);
    if( origin != null ) declaredFields.put("origin", origin);
    if( zoneId != null ) declaredFields.put("zoneId", zoneId);
    if( displayName != null ) declaredFields.put("displayName", displayName);
    if( locale != null ) declaredFields.put("locale", locale);
    if( nickName != null ) declaredFields.put("nickName", nickName);
    if( passwordLastModified != null ) declaredFields.put("passwordLastModified", passwordLastModified);
    if( previousLogonTime != null ) declaredFields.put("previousLogonTime", previousLogonTime);
    if( lastLogonTime != null ) declaredFields.put("lastLogonTime", lastLogonTime);
    if( schemas != null ) declaredFields.put("schemas", schemas);
    if( phoneNumbers != null ) declaredFields.put("phoneNumbers", phoneNumbers);
    if( preferredLanguage != null ) declaredFields.put("preferredLanguage", preferredLanguage);
    if( profileUrl != null ) declaredFields.put("profileUrl", profileUrl);
    if( salt != null ) declaredFields.put("salt", salt);
    if( timezone != null ) declaredFields.put("timezone", timezone);
    if( title != null ) declaredFields.put("title", title);
    if( userType != null ) declaredFields.put("userType", userType);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link ScimUser} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final ScimUser scimUser = (ScimUser) o;
    return Objects.equals(this.cloudSdkCustomFields, scimUser.cloudSdkCustomFields) &&
        Objects.equals(this.id, scimUser.id) &&
        Objects.equals(this.externalId, scimUser.externalId) &&
        Objects.equals(this.meta, scimUser.meta) &&
        Objects.equals(this.userName, scimUser.userName) &&
        Objects.equals(this.name, scimUser.name) &&
        Objects.equals(this.emails, scimUser.emails) &&
        Objects.equals(this.groups, scimUser.groups) &&
        Objects.equals(this.approvals, scimUser.approvals) &&
        Objects.equals(this.active, scimUser.active) &&
        Objects.equals(this.verified, scimUser.verified) &&
        Objects.equals(this.origin, scimUser.origin) &&
        Objects.equals(this.zoneId, scimUser.zoneId) &&
        Objects.equals(this.displayName, scimUser.displayName) &&
        Objects.equals(this.locale, scimUser.locale) &&
        Objects.equals(this.nickName, scimUser.nickName) &&
        Objects.equals(this.passwordLastModified, scimUser.passwordLastModified) &&
        Objects.equals(this.previousLogonTime, scimUser.previousLogonTime) &&
        Objects.equals(this.lastLogonTime, scimUser.lastLogonTime) &&
        Objects.equals(this.schemas, scimUser.schemas) &&
        Objects.equals(this.phoneNumbers, scimUser.phoneNumbers) &&
        Objects.equals(this.preferredLanguage, scimUser.preferredLanguage) &&
        Objects.equals(this.profileUrl, scimUser.profileUrl) &&
        Objects.equals(this.salt, scimUser.salt) &&
        Objects.equals(this.timezone, scimUser.timezone) &&
        Objects.equals(this.title, scimUser.title) &&
        Objects.equals(this.userType, scimUser.userType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, externalId, meta, userName, name, emails, groups, approvals, active, verified, origin, zoneId, displayName, locale, nickName, passwordLastModified, previousLogonTime, lastLogonTime, schemas, phoneNumbers, preferredLanguage, profileUrl, salt, timezone, title, userType, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class ScimUser {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    emails: ").append(toIndentedString(emails)).append("\n");
    sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
    sb.append("    approvals: ").append(toIndentedString(approvals)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    verified: ").append(toIndentedString(verified)).append("\n");
    sb.append("    origin: ").append(toIndentedString(origin)).append("\n");
    sb.append("    zoneId: ").append(toIndentedString(zoneId)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("    nickName: ").append(toIndentedString(nickName)).append("\n");
    sb.append("    passwordLastModified: ").append(toIndentedString(passwordLastModified)).append("\n");
    sb.append("    previousLogonTime: ").append(toIndentedString(previousLogonTime)).append("\n");
    sb.append("    lastLogonTime: ").append(toIndentedString(lastLogonTime)).append("\n");
    sb.append("    schemas: ").append(toIndentedString(schemas)).append("\n");
    sb.append("    phoneNumbers: ").append(toIndentedString(phoneNumbers)).append("\n");
    sb.append("    preferredLanguage: ").append(toIndentedString(preferredLanguage)).append("\n");
    sb.append("    profileUrl: ").append(toIndentedString(profileUrl)).append("\n");
    sb.append("    salt: ").append(toIndentedString(salt)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    userType: ").append(toIndentedString(userType)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

