

/*
 * User Management (System for Cross-domain Identity Management (SCIM))
 * Provides functions to administrate the Authorization and Trust Management service (XSUAA) of SAP BTP, Cloud Foundry environment. You can provision users from identity providers and manage roles and role collections. Use this API to manage shadow users; users the service provisions from your identity provider to the subaccount. For more information, see [Switch Off Automatic Creation of Shadow Users](https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/d8525671e8b14147b96ef497e1e1af80.html). The System for Cross-domain Identity Management (SCIM) interfaces for users and groups supplement the relevant UAA [users](https://docs.cloudfoundry.org/api/uaa/version/74.0.0/index.html#users)and [groups](https://docs.cloudfoundry.org/api/uaa/version/74.0.0/index.html#groups) interfaces. Groups in the Authorization and Trust Management service are mapped to role collections. See also [SAP Note 2760424]( https://launchpad.support.sap.com/#/notes/2760424). To enable access to this API, create an OAuth 2.0 client for the XSUAA service instance. To create the client, enable the apiaccess plan. For more information, see [Access UAA Admin APIs](https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/ebc9113a520e495ea5fb759b9a7929f2.html).
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.openapi.scim.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * ScimGroupMemberPatch
 */
// CHECKSTYLE:OFF
public class ScimGroupMemberPatch 
// CHECKSTYLE:ON
{
  @JsonProperty("origin")
  private String origin;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    /**
    * The USER option of this ScimGroupMemberPatch
    */
    USER("USER");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    /**
    * Get the value of the enum
    * @return The enum value
    */
    @JsonValue
    @Nonnull public String getValue() {
      return value;
    }

    /**
    * Get the String value of the enum value.
    * @return The enum value as String
    */
    @Override
    @Nonnull public String toString() {
      return String.valueOf(value);
    }

    /**
    * Get the enum value from a String value
    * @param value The String value
    * @return The enum value of type ScimGroupMemberPatch
    */
    @JsonCreator
    @Nonnull public static TypeEnum fromValue(@Nonnull final String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  @JsonProperty("type")
  private TypeEnum type;

  @JsonProperty("value")
  private String value;

  /**
   * Use this parameter to add or remove users from a group.
   */
  public enum OperationEnum {
    /**
    * The DELETE option of this ScimGroupMemberPatch
    */
    DELETE("delete"),
    
    /**
    * The CREATE option of this ScimGroupMemberPatch
    */
    CREATE("create");

    private String value;

    OperationEnum(String value) {
      this.value = value;
    }

    /**
    * Get the value of the enum
    * @return The enum value
    */
    @JsonValue
    @Nonnull public String getValue() {
      return value;
    }

    /**
    * Get the String value of the enum value.
    * @return The enum value as String
    */
    @Override
    @Nonnull public String toString() {
      return String.valueOf(value);
    }

    /**
    * Get the enum value from a String value
    * @param value The String value
    * @return The enum value of type ScimGroupMemberPatch
    */
    @JsonCreator
    @Nonnull public static OperationEnum fromValue(@Nonnull final String value) {
      for (OperationEnum b : OperationEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  @JsonProperty("operation")
  private OperationEnum operation;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /**
   * Set the origin of this {@link ScimGroupMemberPatch} instance and return the same instance.
   *
   * @param origin  The identity provider hosting the user. For the default identity provider, use sap.default. Subaccounts created before October 2020 return ldap as the default identity provider. The system accepts both sap.default and ldap for the default identity provider, but returns sap.default or ldap depending on when the subaccount was created.
   * @return The same instance of this {@link ScimGroupMemberPatch} class
   */
  @Nonnull public ScimGroupMemberPatch origin( @Nullable final String origin) {
    this.origin = origin;
    return this;
  }

  /**
   * The identity provider hosting the user. For the default identity provider, use sap.default. Subaccounts created before October 2020 return ldap as the default identity provider. The system accepts both sap.default and ldap for the default identity provider, but returns sap.default or ldap depending on when the subaccount was created.
   * @return origin  The origin of this {@link ScimGroupMemberPatch} instance.
   */
  @Nonnull
  public String getOrigin() {
    return origin;
  }

  /**
   * Set the origin of this {@link ScimGroupMemberPatch} instance.
   *
   * @param origin  The identity provider hosting the user. For the default identity provider, use sap.default. Subaccounts created before October 2020 return ldap as the default identity provider. The system accepts both sap.default and ldap for the default identity provider, but returns sap.default or ldap depending on when the subaccount was created.
   */
  public void setOrigin( @Nullable final String origin) {
    this.origin = origin;
  }

  /**
   * Set the type of this {@link ScimGroupMemberPatch} instance and return the same instance.
   *
   * @param type  The type of this {@link ScimGroupMemberPatch}
   * @return The same instance of this {@link ScimGroupMemberPatch} class
   */
  @Nonnull public ScimGroupMemberPatch type( @Nullable final TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type  The type of this {@link ScimGroupMemberPatch} instance.
   */
  @Nonnull
  public TypeEnum getType() {
    return type;
  }

  /**
   * Set the type of this {@link ScimGroupMemberPatch} instance.
   *
   * @param type  The type of this {@link ScimGroupMemberPatch}
   */
  public void setType( @Nullable final TypeEnum type) {
    this.type = type;
  }

  /**
   * Set the value of this {@link ScimGroupMemberPatch} instance and return the same instance.
   *
   * @param value  The ID of a specific user. User IDs can be found using the \&quot;/Users\&quot; endpoint.
   * @return The same instance of this {@link ScimGroupMemberPatch} class
   */
  @Nonnull public ScimGroupMemberPatch value( @Nullable final String value) {
    this.value = value;
    return this;
  }

  /**
   * The ID of a specific user. User IDs can be found using the \&quot;/Users\&quot; endpoint.
   * @return value  The value of this {@link ScimGroupMemberPatch} instance.
   */
  @Nonnull
  public String getValue() {
    return value;
  }

  /**
   * Set the value of this {@link ScimGroupMemberPatch} instance.
   *
   * @param value  The ID of a specific user. User IDs can be found using the \&quot;/Users\&quot; endpoint.
   */
  public void setValue( @Nullable final String value) {
    this.value = value;
  }

  /**
   * Set the operation of this {@link ScimGroupMemberPatch} instance and return the same instance.
   *
   * @param operation  Use this parameter to add or remove users from a group.
   * @return The same instance of this {@link ScimGroupMemberPatch} class
   */
  @Nonnull public ScimGroupMemberPatch operation( @Nullable final OperationEnum operation) {
    this.operation = operation;
    return this;
  }

  /**
   * Use this parameter to add or remove users from a group.
   * @return operation  The operation of this {@link ScimGroupMemberPatch} instance.
   */
  @Nonnull
  public OperationEnum getOperation() {
    return operation;
  }

  /**
   * Set the operation of this {@link ScimGroupMemberPatch} instance.
   *
   * @param operation  Use this parameter to add or remove users from a group.
   */
  public void setOperation( @Nullable final OperationEnum operation) {
    this.operation = operation;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link ScimGroupMemberPatch}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link ScimGroupMemberPatch} instance.
   * @deprecated Use {@link #toMap()} instead.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField( @Nonnull final String name ) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("ScimGroupMemberPatch has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link ScimGroupMemberPatch} instance including unrecognized properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap()
  {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if( origin != null ) declaredFields.put("origin", origin);
    if( type != null ) declaredFields.put("type", type);
    if( value != null ) declaredFields.put("value", value);
    if( operation != null ) declaredFields.put("operation", operation);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link ScimGroupMemberPatch} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final ScimGroupMemberPatch scimGroupMemberPatch = (ScimGroupMemberPatch) o;
    return Objects.equals(this.cloudSdkCustomFields, scimGroupMemberPatch.cloudSdkCustomFields) &&
        Objects.equals(this.origin, scimGroupMemberPatch.origin) &&
        Objects.equals(this.type, scimGroupMemberPatch.type) &&
        Objects.equals(this.value, scimGroupMemberPatch.value) &&
        Objects.equals(this.operation, scimGroupMemberPatch.operation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(origin, type, value, operation, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class ScimGroupMemberPatch {\n");
    sb.append("    origin: ").append(toIndentedString(origin)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    operation: ").append(toIndentedString(operation)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

