

/*
 * User Management (System for Cross-domain Identity Management (SCIM))
 * Provides functions to administrate the Authorization and Trust Management service (XSUAA) of SAP BTP, Cloud Foundry environment. You can provision users from identity providers and manage roles and role collections. Use this API to manage shadow users; users the service provisions from your identity provider to the subaccount. For more information, see [Switch Off Automatic Creation of Shadow Users](https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/d8525671e8b14147b96ef497e1e1af80.html). The System for Cross-domain Identity Management (SCIM) interfaces for users and groups supplement the relevant UAA [users](https://docs.cloudfoundry.org/api/uaa/version/74.0.0/index.html#users)and [groups](https://docs.cloudfoundry.org/api/uaa/version/74.0.0/index.html#groups) interfaces. Groups in the Authorization and Trust Management service are mapped to role collections. See also [SAP Note 2760424]( https://launchpad.support.sap.com/#/notes/2760424). To enable access to this API, create an OAuth 2.0 client for the XSUAA service instance. To create the client, enable the apiaccess plan. For more information, see [Access UAA Admin APIs](https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/ebc9113a520e495ea5fb759b9a7929f2.html).
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.openapi.scim.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sap.openapi.scim.model.ScimGroupMemberPatch;
import com.sap.openapi.scim.model.ScimMeta;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * ScimGroupPatch
 */
// CHECKSTYLE:OFF
public class ScimGroupPatch 
// CHECKSTYLE:ON
{
  @JsonProperty("id")
  private String id;

  @JsonProperty("meta")
  private ScimMeta meta;

  @JsonProperty("displayName")
  private String displayName;

  @JsonProperty("zoneId")
  private String zoneId;

  @JsonProperty("description")
  private String description;

  @JsonProperty("members")
  private List<ScimGroupMemberPatch> members = new ArrayList<>();

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /**
   * Set the id of this {@link ScimGroupPatch} instance and return the same instance.
   *
   * @param id  The group ID of a SCIM group.
   * @return The same instance of this {@link ScimGroupPatch} class
   */
  @Nonnull public ScimGroupPatch id( @Nullable final String id) {
    this.id = id;
    return this;
  }

  /**
   * The group ID of a SCIM group.
   * @return id  The id of this {@link ScimGroupPatch} instance.
   */
  @Nonnull
  public String getId() {
    return id;
  }

  /**
   * Set the id of this {@link ScimGroupPatch} instance.
   *
   * @param id  The group ID of a SCIM group.
   */
  public void setId( @Nullable final String id) {
    this.id = id;
  }

  /**
   * Set the meta of this {@link ScimGroupPatch} instance and return the same instance.
   *
   * @param meta  The meta of this {@link ScimGroupPatch}
   * @return The same instance of this {@link ScimGroupPatch} class
   */
  @Nonnull public ScimGroupPatch meta( @Nullable final ScimMeta meta) {
    this.meta = meta;
    return this;
  }

  /**
   * Get meta
   * @return meta  The meta of this {@link ScimGroupPatch} instance.
   */
  @Nonnull
  public ScimMeta getMeta() {
    return meta;
  }

  /**
   * Set the meta of this {@link ScimGroupPatch} instance.
   *
   * @param meta  The meta of this {@link ScimGroupPatch}
   */
  public void setMeta( @Nullable final ScimMeta meta) {
    this.meta = meta;
  }

  /**
   * Set the displayName of this {@link ScimGroupPatch} instance and return the same instance.
   *
   * @param displayName  The displayName of this {@link ScimGroupPatch}
   * @return The same instance of this {@link ScimGroupPatch} class
   */
  @Nonnull public ScimGroupPatch displayName( @Nullable final String displayName) {
    this.displayName = displayName;
    return this;
  }

  /**
   * Get displayName
   * @return displayName  The displayName of this {@link ScimGroupPatch} instance.
   */
  @Nonnull
  public String getDisplayName() {
    return displayName;
  }

  /**
   * Set the displayName of this {@link ScimGroupPatch} instance.
   *
   * @param displayName  The displayName of this {@link ScimGroupPatch}
   */
  public void setDisplayName( @Nullable final String displayName) {
    this.displayName = displayName;
  }

  /**
   * Set the zoneId of this {@link ScimGroupPatch} instance and return the same instance.
   *
   * @param zoneId  The zoneId of this {@link ScimGroupPatch}
   * @return The same instance of this {@link ScimGroupPatch} class
   */
  @Nonnull public ScimGroupPatch zoneId( @Nullable final String zoneId) {
    this.zoneId = zoneId;
    return this;
  }

  /**
   * Get zoneId
   * @return zoneId  The zoneId of this {@link ScimGroupPatch} instance.
   */
  @Nonnull
  public String getZoneId() {
    return zoneId;
  }

  /**
   * Set the zoneId of this {@link ScimGroupPatch} instance.
   *
   * @param zoneId  The zoneId of this {@link ScimGroupPatch}
   */
  public void setZoneId( @Nullable final String zoneId) {
    this.zoneId = zoneId;
  }

  /**
   * Set the description of this {@link ScimGroupPatch} instance and return the same instance.
   *
   * @param description  The description of this {@link ScimGroupPatch}
   * @return The same instance of this {@link ScimGroupPatch} class
   */
  @Nonnull public ScimGroupPatch description( @Nullable final String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description  The description of this {@link ScimGroupPatch} instance.
   */
  @Nonnull
  public String getDescription() {
    return description;
  }

  /**
   * Set the description of this {@link ScimGroupPatch} instance.
   *
   * @param description  The description of this {@link ScimGroupPatch}
   */
  public void setDescription( @Nullable final String description) {
    this.description = description;
  }

  /**
   * Set the members of this {@link ScimGroupPatch} instance and return the same instance.
   *
   * @param members  The members of this {@link ScimGroupPatch}
   * @return The same instance of this {@link ScimGroupPatch} class
   */
  @Nonnull public ScimGroupPatch members( @Nullable final List<ScimGroupMemberPatch> members) {
    this.members = members;
    return this;
  }
  /**
   * Add one members instance to this {@link ScimGroupPatch}.
   * @param membersItem The members that should be added
   * @return The same instance of type {@link ScimGroupPatch}
   */
  @Nonnull public ScimGroupPatch addMembersItem( @Nonnull final ScimGroupMemberPatch membersItem) {
    if (this.members == null) {
      this.members = new ArrayList<>();
    }
    this.members.add(membersItem);
    return this;
  }

  /**
   * Get members
   * @return members  The members of this {@link ScimGroupPatch} instance.
   */
  @Nonnull
  public List<ScimGroupMemberPatch> getMembers() {
    return members;
  }

  /**
   * Set the members of this {@link ScimGroupPatch} instance.
   *
   * @param members  The members of this {@link ScimGroupPatch}
   */
  public void setMembers( @Nullable final List<ScimGroupMemberPatch> members) {
    this.members = members;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link ScimGroupPatch}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link ScimGroupPatch} instance.
   * @deprecated Use {@link #toMap()} instead.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField( @Nonnull final String name ) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("ScimGroupPatch has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link ScimGroupPatch} instance including unrecognized properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap()
  {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if( id != null ) declaredFields.put("id", id);
    if( meta != null ) declaredFields.put("meta", meta);
    if( displayName != null ) declaredFields.put("displayName", displayName);
    if( zoneId != null ) declaredFields.put("zoneId", zoneId);
    if( description != null ) declaredFields.put("description", description);
    if( members != null ) declaredFields.put("members", members);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link ScimGroupPatch} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final ScimGroupPatch scimGroupPatch = (ScimGroupPatch) o;
    return Objects.equals(this.cloudSdkCustomFields, scimGroupPatch.cloudSdkCustomFields) &&
        Objects.equals(this.id, scimGroupPatch.id) &&
        Objects.equals(this.meta, scimGroupPatch.meta) &&
        Objects.equals(this.displayName, scimGroupPatch.displayName) &&
        Objects.equals(this.zoneId, scimGroupPatch.zoneId) &&
        Objects.equals(this.description, scimGroupPatch.description) &&
        Objects.equals(this.members, scimGroupPatch.members);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, meta, displayName, zoneId, description, members, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class ScimGroupPatch {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    zoneId: ").append(toIndentedString(zoneId)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    members: ").append(toIndentedString(members)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

