

/*
 * User Management (System for Cross-domain Identity Management (SCIM))
 * Provides functions to administrate the Authorization and Trust Management service (XSUAA) of SAP BTP, Cloud Foundry environment. You can provision users from identity providers and manage roles and role collections. Use this API to manage shadow users; users the service provisions from your identity provider to the subaccount. For more information, see [Switch Off Automatic Creation of Shadow Users](https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/d8525671e8b14147b96ef497e1e1af80.html). The System for Cross-domain Identity Management (SCIM) interfaces for users and groups supplement the relevant UAA [users](https://docs.cloudfoundry.org/api/uaa/version/74.0.0/index.html#users)and [groups](https://docs.cloudfoundry.org/api/uaa/version/74.0.0/index.html#groups) interfaces. Groups in the Authorization and Trust Management service are mapped to role collections. See also [SAP Note 2760424]( https://launchpad.support.sap.com/#/notes/2760424). To enable access to this API, create an OAuth 2.0 client for the XSUAA service instance. To create the client, enable the apiaccess plan. For more information, see [Access UAA Admin APIs](https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/ebc9113a520e495ea5fb759b9a7929f2.html).
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.openapi.scim.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sap.openapi.scim.model.ScimGroup;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * ScimGroups
 */
// CHECKSTYLE:OFF
public class ScimGroups 
// CHECKSTYLE:ON
{
  @JsonProperty("resources")
  private List<ScimGroup> resources = new ArrayList<>();

  @JsonProperty("startIndex")
  private Integer startIndex;

  @JsonProperty("itemsPerPage")
  private Integer itemsPerPage;

  @JsonProperty("totalResults")
  private Integer totalResults;

  @JsonProperty("schemas")
  private List<String> schemas = new ArrayList<>();

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /**
   * Set the resources of this {@link ScimGroups} instance and return the same instance.
   *
   * @param resources  The resources of this {@link ScimGroups}
   * @return The same instance of this {@link ScimGroups} class
   */
  @Nonnull public ScimGroups resources( @Nullable final List<ScimGroup> resources) {
    this.resources = resources;
    return this;
  }
  /**
   * Add one resources instance to this {@link ScimGroups}.
   * @param resourcesItem The resources that should be added
   * @return The same instance of type {@link ScimGroups}
   */
  @Nonnull public ScimGroups addResourcesItem( @Nonnull final ScimGroup resourcesItem) {
    if (this.resources == null) {
      this.resources = new ArrayList<>();
    }
    this.resources.add(resourcesItem);
    return this;
  }

  /**
   * Get resources
   * @return resources  The resources of this {@link ScimGroups} instance.
   */
  @Nonnull
  public List<ScimGroup> getResources() {
    return resources;
  }

  /**
   * Set the resources of this {@link ScimGroups} instance.
   *
   * @param resources  The resources of this {@link ScimGroups}
   */
  public void setResources( @Nullable final List<ScimGroup> resources) {
    this.resources = resources;
  }

  /**
   * Set the startIndex of this {@link ScimGroups} instance and return the same instance.
   *
   * @param startIndex  Specifies the index of the first resource in the current set of search results.
   * @return The same instance of this {@link ScimGroups} class
   */
  @Nonnull public ScimGroups startIndex( @Nullable final Integer startIndex) {
    this.startIndex = startIndex;
    return this;
  }

  /**
   * Specifies the index of the first resource in the current set of search results.
   * @return startIndex  The startIndex of this {@link ScimGroups} instance.
   */
  @Nonnull
  public Integer getStartIndex() {
    return startIndex;
  }

  /**
   * Set the startIndex of this {@link ScimGroups} instance.
   *
   * @param startIndex  Specifies the index of the first resource in the current set of search results.
   */
  public void setStartIndex( @Nullable final Integer startIndex) {
    this.startIndex = startIndex;
  }

  /**
   * Set the itemsPerPage of this {@link ScimGroups} instance and return the same instance.
   *
   * @param itemsPerPage  Specifies the maximum number of search results returned per response page.
   * @return The same instance of this {@link ScimGroups} class
   */
  @Nonnull public ScimGroups itemsPerPage( @Nullable final Integer itemsPerPage) {
    this.itemsPerPage = itemsPerPage;
    return this;
  }

  /**
   * Specifies the maximum number of search results returned per response page.
   * @return itemsPerPage  The itemsPerPage of this {@link ScimGroups} instance.
   */
  @Nonnull
  public Integer getItemsPerPage() {
    return itemsPerPage;
  }

  /**
   * Set the itemsPerPage of this {@link ScimGroups} instance.
   *
   * @param itemsPerPage  Specifies the maximum number of search results returned per response page.
   */
  public void setItemsPerPage( @Nullable final Integer itemsPerPage) {
    this.itemsPerPage = itemsPerPage;
  }

  /**
   * Set the totalResults of this {@link ScimGroups} instance and return the same instance.
   *
   * @param totalResults  Specifies the total number of results matching the query. The service returns a maximum of 500 results.
   * @return The same instance of this {@link ScimGroups} class
   */
  @Nonnull public ScimGroups totalResults( @Nullable final Integer totalResults) {
    this.totalResults = totalResults;
    return this;
  }

  /**
   * Specifies the total number of results matching the query. The service returns a maximum of 500 results.
   * @return totalResults  The totalResults of this {@link ScimGroups} instance.
   */
  @Nonnull
  public Integer getTotalResults() {
    return totalResults;
  }

  /**
   * Set the totalResults of this {@link ScimGroups} instance.
   *
   * @param totalResults  Specifies the total number of results matching the query. The service returns a maximum of 500 results.
   */
  public void setTotalResults( @Nullable final Integer totalResults) {
    this.totalResults = totalResults;
  }

  /**
   * Set the schemas of this {@link ScimGroups} instance and return the same instance.
   *
   * @param schemas  The schemas of this {@link ScimGroups}
   * @return The same instance of this {@link ScimGroups} class
   */
  @Nonnull public ScimGroups schemas( @Nullable final List<String> schemas) {
    this.schemas = schemas;
    return this;
  }
  /**
   * Add one schemas instance to this {@link ScimGroups}.
   * @param schemasItem The schemas that should be added
   * @return The same instance of type {@link ScimGroups}
   */
  @Nonnull public ScimGroups addSchemasItem( @Nonnull final String schemasItem) {
    if (this.schemas == null) {
      this.schemas = new ArrayList<>();
    }
    this.schemas.add(schemasItem);
    return this;
  }

  /**
   * Get schemas
   * @return schemas  The schemas of this {@link ScimGroups} instance.
   */
  @Nonnull
  public List<String> getSchemas() {
    return schemas;
  }

  /**
   * Set the schemas of this {@link ScimGroups} instance.
   *
   * @param schemas  The schemas of this {@link ScimGroups}
   */
  public void setSchemas( @Nullable final List<String> schemas) {
    this.schemas = schemas;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link ScimGroups}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link ScimGroups} instance.
   * @deprecated Use {@link #toMap()} instead.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField( @Nonnull final String name ) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("ScimGroups has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link ScimGroups} instance including unrecognized properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap()
  {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if( resources != null ) declaredFields.put("resources", resources);
    if( startIndex != null ) declaredFields.put("startIndex", startIndex);
    if( itemsPerPage != null ) declaredFields.put("itemsPerPage", itemsPerPage);
    if( totalResults != null ) declaredFields.put("totalResults", totalResults);
    if( schemas != null ) declaredFields.put("schemas", schemas);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link ScimGroups} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final ScimGroups scimGroups = (ScimGroups) o;
    return Objects.equals(this.cloudSdkCustomFields, scimGroups.cloudSdkCustomFields) &&
        Objects.equals(this.resources, scimGroups.resources) &&
        Objects.equals(this.startIndex, scimGroups.startIndex) &&
        Objects.equals(this.itemsPerPage, scimGroups.itemsPerPage) &&
        Objects.equals(this.totalResults, scimGroups.totalResults) &&
        Objects.equals(this.schemas, scimGroups.schemas);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resources, startIndex, itemsPerPage, totalResults, schemas, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class ScimGroups {\n");
    sb.append("    resources: ").append(toIndentedString(resources)).append("\n");
    sb.append("    startIndex: ").append(toIndentedString(startIndex)).append("\n");
    sb.append("    itemsPerPage: ").append(toIndentedString(itemsPerPage)).append("\n");
    sb.append("    totalResults: ").append(toIndentedString(totalResults)).append("\n");
    sb.append("    schemas: ").append(toIndentedString(schemas)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

