

/*
 * Workflow
 * This API uses the workflow capability of SAP Build Process Automation. With the API, you can, for example, start new workflow instances and work with tasks.  Note: These APIs are designed for loosely coupled clients. This means:  - If SAP Build Process Automation adds fields to responses, the API version number does not increase. Your client must ignore new fields. - The order of fields in responses and of entries in arrays may change. This applies unless the API provides an explicit means to specify the desired order. 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.openapi.sbpaworkflow.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * JobError
 */
// CHECKSTYLE:OFF
public class JobError 
// CHECKSTYLE:ON
{
  @JsonProperty("code")
  private String code;

  @JsonProperty("message")
  private String message;

  @JsonProperty("logId")
  private String logId;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /**
   * Set the code of this {@link JobError} instance and return the same instance.
   *
   * @param code  The error category.
   * @return The same instance of this {@link JobError} class
   */
  @Nonnull public JobError code( @Nullable final String code) {
    this.code = code;
    return this;
  }

  /**
   * The error category.
   * @return code  The code of this {@link JobError} instance.
   */
  @Nonnull
  public String getCode() {
    return code;
  }

  /**
   * Set the code of this {@link JobError} instance.
   *
   * @param code  The error category.
   */
  public void setCode( @Nullable final String code) {
    this.code = code;
  }

  /**
   * Set the message of this {@link JobError} instance and return the same instance.
   *
   * @param message  The error message.
   * @return The same instance of this {@link JobError} class
   */
  @Nonnull public JobError message( @Nullable final String message) {
    this.message = message;
    return this;
  }

  /**
   * The error message.
   * @return message  The message of this {@link JobError} instance.
   */
  @Nonnull
  public String getMessage() {
    return message;
  }

  /**
   * Set the message of this {@link JobError} instance.
   *
   * @param message  The error message.
   */
  public void setMessage( @Nullable final String message) {
    this.message = message;
  }

  /**
   * Set the logId of this {@link JobError} instance and return the same instance.
   *
   * @param logId  The log ID referring to the error.
   * @return The same instance of this {@link JobError} class
   */
  @Nonnull public JobError logId( @Nullable final String logId) {
    this.logId = logId;
    return this;
  }

  /**
   * The log ID referring to the error.
   * @return logId  The logId of this {@link JobError} instance.
   */
  @Nonnull
  public String getLogId() {
    return logId;
  }

  /**
   * Set the logId of this {@link JobError} instance.
   *
   * @param logId  The log ID referring to the error.
   */
  public void setLogId( @Nullable final String logId) {
    this.logId = logId;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link JobError}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link JobError} instance.
   * @deprecated Use {@link #toMap()} instead.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField( @Nonnull final String name ) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("JobError has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link JobError} instance including unrecognized properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap()
  {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if( code != null ) declaredFields.put("code", code);
    if( message != null ) declaredFields.put("message", message);
    if( logId != null ) declaredFields.put("logId", logId);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link JobError} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final JobError jobError = (JobError) o;
    return Objects.equals(this.cloudSdkCustomFields, jobError.cloudSdkCustomFields) &&
        Objects.equals(this.code, jobError.code) &&
        Objects.equals(this.message, jobError.message) &&
        Objects.equals(this.logId, jobError.logId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, message, logId, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class JobError {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    logId: ").append(toIndentedString(logId)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

