

/*
 * Inbox
 * This API provides the functionality for building \"own inbox\" capabilities on top of SAP Build Process Automation. It is based on the task consumption model (TCM) as documented in SAP Note [2304317](https://launchpad.support.sap.com/#/notes/2304317/E).  Only users who have the ProcessAutomationParticipant role assigned are able to use the Inbox API.  SAP Build Process Automation currently supports only a subset of the Task Consumption Model capabilities. Only the functionality included in this document is available.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.openapi.sbpaworkflow.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sap.openapi.sbpaworkflow.model.SubstitutionError400ErrorMessage;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * SubstitutionError500Error
 */
// CHECKSTYLE:OFF
public class SubstitutionError500Error 
// CHECKSTYLE:ON
{
  /**
   * The error category.
   */
  public enum CodeEnum {
    /**
    * The SUBSTITUTION_INVALID_STATE_TRANSITION option of this SubstitutionError500Error
    */
    SUBSTITUTION_INVALID_STATE_TRANSITION("SUBSTITUTION_INVALID_STATE_TRANSITION"),
    
    /**
    * The INVALID_DATA option of this SubstitutionError500Error
    */
    INVALID_DATA("INVALID_DATA");

    private String value;

    CodeEnum(String value) {
      this.value = value;
    }

    /**
    * Get the value of the enum
    * @return The enum value
    */
    @JsonValue
    @Nonnull public String getValue() {
      return value;
    }

    /**
    * Get the String value of the enum value.
    * @return The enum value as String
    */
    @Override
    @Nonnull public String toString() {
      return String.valueOf(value);
    }

    /**
    * Get the enum value from a String value
    * @param value The String value
    * @return The enum value of type SubstitutionError500Error
    */
    @JsonCreator
    @Nonnull public static CodeEnum fromValue(@Nonnull final String value) {
      for (CodeEnum b : CodeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  @JsonProperty("code")
  private CodeEnum code;

  @JsonProperty("message")
  private SubstitutionError400ErrorMessage message;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /**
   * Set the code of this {@link SubstitutionError500Error} instance and return the same instance.
   *
   * @param code  The error category.
   * @return The same instance of this {@link SubstitutionError500Error} class
   */
  @Nonnull public SubstitutionError500Error code( @Nullable final CodeEnum code) {
    this.code = code;
    return this;
  }

  /**
   * The error category.
   * @return code  The code of this {@link SubstitutionError500Error} instance.
   */
  @Nonnull
  public CodeEnum getCode() {
    return code;
  }

  /**
   * Set the code of this {@link SubstitutionError500Error} instance.
   *
   * @param code  The error category.
   */
  public void setCode( @Nullable final CodeEnum code) {
    this.code = code;
  }

  /**
   * Set the message of this {@link SubstitutionError500Error} instance and return the same instance.
   *
   * @param message  The message of this {@link SubstitutionError500Error}
   * @return The same instance of this {@link SubstitutionError500Error} class
   */
  @Nonnull public SubstitutionError500Error message( @Nullable final SubstitutionError400ErrorMessage message) {
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message  The message of this {@link SubstitutionError500Error} instance.
   */
  @Nonnull
  public SubstitutionError400ErrorMessage getMessage() {
    return message;
  }

  /**
   * Set the message of this {@link SubstitutionError500Error} instance.
   *
   * @param message  The message of this {@link SubstitutionError500Error}
   */
  public void setMessage( @Nullable final SubstitutionError400ErrorMessage message) {
    this.message = message;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link SubstitutionError500Error}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link SubstitutionError500Error} instance.
   * @deprecated Use {@link #toMap()} instead.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField( @Nonnull final String name ) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("SubstitutionError500Error has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link SubstitutionError500Error} instance including unrecognized properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap()
  {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if( code != null ) declaredFields.put("code", code);
    if( message != null ) declaredFields.put("message", message);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link SubstitutionError500Error} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final SubstitutionError500Error substitutionError500Error = (SubstitutionError500Error) o;
    return Objects.equals(this.cloudSdkCustomFields, substitutionError500Error.cloudSdkCustomFields) &&
        Objects.equals(this.code, substitutionError500Error.code) &&
        Objects.equals(this.message, substitutionError500Error.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, message, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class SubstitutionError500Error {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

