

/*
 * Inbox
 * This API provides the functionality for building \"own inbox\" capabilities on top of SAP Build Process Automation. It is based on the task consumption model (TCM) as documented in SAP Note [2304317](https://launchpad.support.sap.com/#/notes/2304317/E).  Only users who have the ProcessAutomationParticipant role assigned are able to use the Inbox API.  SAP Build Process Automation currently supports only a subset of the Task Consumption Model capabilities. Only the functionality included in this document is available.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.openapi.sbpaworkflow.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.sap.openapi.sbpaworkflow.customserializer.OffsetDateTimeDeserializer;
import com.sap.openapi.sbpaworkflow.model.SubstitutionRuleDMetadata;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * SubstitutesRuleD
 */
// CHECKSTYLE:OFF
public class SubstitutesRuleD 
// CHECKSTYLE:ON
{
  @JsonProperty("__metadata")
  private SubstitutionRuleDMetadata metadata;

  @JsonProperty("SubstitutionRuleID")
  private String substitutionRuleID;

  @JsonProperty("SAP__Origin")
  private String saPOrigin;

  @JsonProperty("User")
  private String user;

  @JsonProperty("BeginDate")
  @JsonDeserialize(using = OffsetDateTimeDeserializer.class)
  private OffsetDateTime beginDate;

  @JsonProperty("EndDate")
  @JsonDeserialize(using = OffsetDateTimeDeserializer.class)
  private OffsetDateTime endDate;

  @JsonProperty("FullName")
  private String fullName;

  /**
   * The mode of the substitution rule.
   */
  public enum ModeEnum {
    /**
    * The RECEIVE_TASKS option of this SubstitutesRuleD
    */
    RECEIVE_TASKS("RECEIVE_TASKS"),
    
    /**
    * The TAKE_OVER option of this SubstitutesRuleD
    */
    TAKE_OVER("TAKE_OVER");

    private String value;

    ModeEnum(String value) {
      this.value = value;
    }

    /**
    * Get the value of the enum
    * @return The enum value
    */
    @JsonValue
    @Nonnull public String getValue() {
      return value;
    }

    /**
    * Get the String value of the enum value.
    * @return The enum value as String
    */
    @Override
    @Nonnull public String toString() {
      return String.valueOf(value);
    }

    /**
    * Get the enum value from a String value
    * @param value The String value
    * @return The enum value of type SubstitutesRuleD
    */
    @JsonCreator
    @Nonnull public static ModeEnum fromValue(@Nonnull final String value) {
      for (ModeEnum b : ModeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  @JsonProperty("Mode")
  private ModeEnum mode;

  @JsonProperty("IsEnabled")
  private Boolean isEnabled;

  @JsonProperty("SupportsDeleteSubstitutionRule")
  private Boolean supportsDeleteSubstitutionRule;

  @JsonProperty("SupportsEnableSubstitutionRule")
  private Boolean supportsEnableSubstitutionRule;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /**
   * Set the metadata of this {@link SubstitutesRuleD} instance and return the same instance.
   *
   * @param metadata  The metadata of this {@link SubstitutesRuleD}
   * @return The same instance of this {@link SubstitutesRuleD} class
   */
  @Nonnull public SubstitutesRuleD metadata( @Nullable final SubstitutionRuleDMetadata metadata) {
    this.metadata = metadata;
    return this;
  }

  /**
   * Get metadata
   * @return metadata  The metadata of this {@link SubstitutesRuleD} instance.
   */
  @Nonnull
  public SubstitutionRuleDMetadata getMetadata() {
    return metadata;
  }

  /**
   * Set the metadata of this {@link SubstitutesRuleD} instance.
   *
   * @param metadata  The metadata of this {@link SubstitutesRuleD}
   */
  public void setMetadata( @Nullable final SubstitutionRuleDMetadata metadata) {
    this.metadata = metadata;
  }

  /**
   * Set the substitutionRuleID of this {@link SubstitutesRuleD} instance and return the same instance.
   *
   * @param substitutionRuleID  The ID of the substitution rule.
   * @return The same instance of this {@link SubstitutesRuleD} class
   */
  @Nonnull public SubstitutesRuleD substitutionRuleID( @Nullable final String substitutionRuleID) {
    this.substitutionRuleID = substitutionRuleID;
    return this;
  }

  /**
   * The ID of the substitution rule.
   * @return substitutionRuleID  The substitutionRuleID of this {@link SubstitutesRuleD} instance.
   */
  @Nonnull
  public String getSubstitutionRuleID() {
    return substitutionRuleID;
  }

  /**
   * Set the substitutionRuleID of this {@link SubstitutesRuleD} instance.
   *
   * @param substitutionRuleID  The ID of the substitution rule.
   */
  public void setSubstitutionRuleID( @Nullable final String substitutionRuleID) {
    this.substitutionRuleID = substitutionRuleID;
  }

  /**
   * Set the saPOrigin of this {@link SubstitutesRuleD} instance and return the same instance.
   *
   * @param saPOrigin  The SID discriminator. Set to &#39;NA&#39; for all entities. For more information, see the Task Consumption Model documentation in SAP Note [2304317](https://launchpad.support.sap.com/#/notes/2304317/E).
   * @return The same instance of this {@link SubstitutesRuleD} class
   */
  @Nonnull public SubstitutesRuleD saPOrigin( @Nullable final String saPOrigin) {
    this.saPOrigin = saPOrigin;
    return this;
  }

  /**
   * The SID discriminator. Set to &#39;NA&#39; for all entities. For more information, see the Task Consumption Model documentation in SAP Note [2304317](https://launchpad.support.sap.com/#/notes/2304317/E).
   * @return saPOrigin  The saPOrigin of this {@link SubstitutesRuleD} instance.
   */
  @Nonnull
  public String getSaPOrigin() {
    return saPOrigin;
  }

  /**
   * Set the saPOrigin of this {@link SubstitutesRuleD} instance.
   *
   * @param saPOrigin  The SID discriminator. Set to &#39;NA&#39; for all entities. For more information, see the Task Consumption Model documentation in SAP Note [2304317](https://launchpad.support.sap.com/#/notes/2304317/E).
   */
  public void setSaPOrigin( @Nullable final String saPOrigin) {
    this.saPOrigin = saPOrigin;
  }

  /**
   * Set the user of this {@link SubstitutesRuleD} instance and return the same instance.
   *
   * @param user  The user who is substituted by the currently logged-in user.
   * @return The same instance of this {@link SubstitutesRuleD} class
   */
  @Nonnull public SubstitutesRuleD user( @Nullable final String user) {
    this.user = user;
    return this;
  }

  /**
   * The user who is substituted by the currently logged-in user.
   * @return user  The user of this {@link SubstitutesRuleD} instance.
   */
  @Nonnull
  public String getUser() {
    return user;
  }

  /**
   * Set the user of this {@link SubstitutesRuleD} instance.
   *
   * @param user  The user who is substituted by the currently logged-in user.
   */
  public void setUser( @Nullable final String user) {
    this.user = user;
  }

  /**
   * Set the beginDate of this {@link SubstitutesRuleD} instance and return the same instance.
   *
   * @param beginDate  The date on which the substitution begins (UTC time).
   * @return The same instance of this {@link SubstitutesRuleD} class
   */
  @Nonnull public SubstitutesRuleD beginDate( @Nullable final OffsetDateTime beginDate) {
    this.beginDate = beginDate;
    return this;
  }

  /**
   * The date on which the substitution begins (UTC time).
   * @return beginDate  The beginDate of this {@link SubstitutesRuleD} instance.
   */
  @Nonnull
  public OffsetDateTime getBeginDate() {
    return beginDate;
  }

  /**
   * Set the beginDate of this {@link SubstitutesRuleD} instance.
   *
   * @param beginDate  The date on which the substitution begins (UTC time).
   */
  public void setBeginDate( @Nullable final OffsetDateTime beginDate) {
    this.beginDate = beginDate;
  }

  /**
   * Set the endDate of this {@link SubstitutesRuleD} instance and return the same instance.
   *
   * @param endDate  The date on which the substitution ends (UTC time).
   * @return The same instance of this {@link SubstitutesRuleD} class
   */
  @Nonnull public SubstitutesRuleD endDate( @Nullable final OffsetDateTime endDate) {
    this.endDate = endDate;
    return this;
  }

  /**
   * The date on which the substitution ends (UTC time).
   * @return endDate  The endDate of this {@link SubstitutesRuleD} instance.
   */
  @Nonnull
  public OffsetDateTime getEndDate() {
    return endDate;
  }

  /**
   * Set the endDate of this {@link SubstitutesRuleD} instance.
   *
   * @param endDate  The date on which the substitution ends (UTC time).
   */
  public void setEndDate( @Nullable final OffsetDateTime endDate) {
    this.endDate = endDate;
  }

  /**
   * Set the fullName of this {@link SubstitutesRuleD} instance and return the same instance.
   *
   * @param fullName  The user who substitutes the current user. The user name is identical with the value of the User field. The value of this field may change in future, so if you currently work with fullName you should consider to use the field \&quot;User\&quot; instead.
   * @return The same instance of this {@link SubstitutesRuleD} class
   */
  @Nonnull public SubstitutesRuleD fullName( @Nullable final String fullName) {
    this.fullName = fullName;
    return this;
  }

  /**
   * The user who substitutes the current user. The user name is identical with the value of the User field. The value of this field may change in future, so if you currently work with fullName you should consider to use the field \&quot;User\&quot; instead.
   * @return fullName  The fullName of this {@link SubstitutesRuleD} instance.
   */
  @Nonnull
  public String getFullName() {
    return fullName;
  }

  /**
   * Set the fullName of this {@link SubstitutesRuleD} instance.
   *
   * @param fullName  The user who substitutes the current user. The user name is identical with the value of the User field. The value of this field may change in future, so if you currently work with fullName you should consider to use the field \&quot;User\&quot; instead.
   */
  public void setFullName( @Nullable final String fullName) {
    this.fullName = fullName;
  }

  /**
   * Set the mode of this {@link SubstitutesRuleD} instance and return the same instance.
   *
   * @param mode  The mode of the substitution rule.
   * @return The same instance of this {@link SubstitutesRuleD} class
   */
  @Nonnull public SubstitutesRuleD mode( @Nullable final ModeEnum mode) {
    this.mode = mode;
    return this;
  }

  /**
   * The mode of the substitution rule.
   * @return mode  The mode of this {@link SubstitutesRuleD} instance.
   */
  @Nonnull
  public ModeEnum getMode() {
    return mode;
  }

  /**
   * Set the mode of this {@link SubstitutesRuleD} instance.
   *
   * @param mode  The mode of the substitution rule.
   */
  public void setMode( @Nullable final ModeEnum mode) {
    this.mode = mode;
  }

  /**
   * Set the isEnabled of this {@link SubstitutesRuleD} instance and return the same instance.
   *
   * @param isEnabled  Indicates whether the substitution rule is enabled.
   * @return The same instance of this {@link SubstitutesRuleD} class
   */
  @Nonnull public SubstitutesRuleD isEnabled( @Nullable final Boolean isEnabled) {
    this.isEnabled = isEnabled;
    return this;
  }

  /**
   * Indicates whether the substitution rule is enabled.
   * @return isEnabled  The isEnabled of this {@link SubstitutesRuleD} instance.
   */
  @Nonnull
  public Boolean isIsEnabled() {
    return isEnabled;
  }

  /**
   * Set the isEnabled of this {@link SubstitutesRuleD} instance.
   *
   * @param isEnabled  Indicates whether the substitution rule is enabled.
   */
  public void setIsEnabled( @Nullable final Boolean isEnabled) {
    this.isEnabled = isEnabled;
  }

  /**
   * Set the supportsDeleteSubstitutionRule of this {@link SubstitutesRuleD} instance and return the same instance.
   *
   * @param supportsDeleteSubstitutionRule  Indicates whether the substitution rule can be deleted.
   * @return The same instance of this {@link SubstitutesRuleD} class
   */
  @Nonnull public SubstitutesRuleD supportsDeleteSubstitutionRule( @Nullable final Boolean supportsDeleteSubstitutionRule) {
    this.supportsDeleteSubstitutionRule = supportsDeleteSubstitutionRule;
    return this;
  }

  /**
   * Indicates whether the substitution rule can be deleted.
   * @return supportsDeleteSubstitutionRule  The supportsDeleteSubstitutionRule of this {@link SubstitutesRuleD} instance.
   */
  @Nonnull
  public Boolean isSupportsDeleteSubstitutionRule() {
    return supportsDeleteSubstitutionRule;
  }

  /**
   * Set the supportsDeleteSubstitutionRule of this {@link SubstitutesRuleD} instance.
   *
   * @param supportsDeleteSubstitutionRule  Indicates whether the substitution rule can be deleted.
   */
  public void setSupportsDeleteSubstitutionRule( @Nullable final Boolean supportsDeleteSubstitutionRule) {
    this.supportsDeleteSubstitutionRule = supportsDeleteSubstitutionRule;
  }

  /**
   * Set the supportsEnableSubstitutionRule of this {@link SubstitutesRuleD} instance and return the same instance.
   *
   * @param supportsEnableSubstitutionRule  Indicates whether the substitution rule can be enabled/disabled.
   * @return The same instance of this {@link SubstitutesRuleD} class
   */
  @Nonnull public SubstitutesRuleD supportsEnableSubstitutionRule( @Nullable final Boolean supportsEnableSubstitutionRule) {
    this.supportsEnableSubstitutionRule = supportsEnableSubstitutionRule;
    return this;
  }

  /**
   * Indicates whether the substitution rule can be enabled/disabled.
   * @return supportsEnableSubstitutionRule  The supportsEnableSubstitutionRule of this {@link SubstitutesRuleD} instance.
   */
  @Nonnull
  public Boolean isSupportsEnableSubstitutionRule() {
    return supportsEnableSubstitutionRule;
  }

  /**
   * Set the supportsEnableSubstitutionRule of this {@link SubstitutesRuleD} instance.
   *
   * @param supportsEnableSubstitutionRule  Indicates whether the substitution rule can be enabled/disabled.
   */
  public void setSupportsEnableSubstitutionRule( @Nullable final Boolean supportsEnableSubstitutionRule) {
    this.supportsEnableSubstitutionRule = supportsEnableSubstitutionRule;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link SubstitutesRuleD}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link SubstitutesRuleD} instance.
   * @deprecated Use {@link #toMap()} instead.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField( @Nonnull final String name ) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("SubstitutesRuleD has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link SubstitutesRuleD} instance including unrecognized properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap()
  {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if( metadata != null ) declaredFields.put("metadata", metadata);
    if( substitutionRuleID != null ) declaredFields.put("substitutionRuleID", substitutionRuleID);
    if( saPOrigin != null ) declaredFields.put("saPOrigin", saPOrigin);
    if( user != null ) declaredFields.put("user", user);
    if( beginDate != null ) declaredFields.put("beginDate", beginDate);
    if( endDate != null ) declaredFields.put("endDate", endDate);
    if( fullName != null ) declaredFields.put("fullName", fullName);
    if( mode != null ) declaredFields.put("mode", mode);
    if( isEnabled != null ) declaredFields.put("isEnabled", isEnabled);
    if( supportsDeleteSubstitutionRule != null ) declaredFields.put("supportsDeleteSubstitutionRule", supportsDeleteSubstitutionRule);
    if( supportsEnableSubstitutionRule != null ) declaredFields.put("supportsEnableSubstitutionRule", supportsEnableSubstitutionRule);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link SubstitutesRuleD} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final SubstitutesRuleD substitutesRuleD = (SubstitutesRuleD) o;
    return Objects.equals(this.cloudSdkCustomFields, substitutesRuleD.cloudSdkCustomFields) &&
        Objects.equals(this.metadata, substitutesRuleD.metadata) &&
        Objects.equals(this.substitutionRuleID, substitutesRuleD.substitutionRuleID) &&
        Objects.equals(this.saPOrigin, substitutesRuleD.saPOrigin) &&
        Objects.equals(this.user, substitutesRuleD.user) &&
        Objects.equals(this.beginDate, substitutesRuleD.beginDate) &&
        Objects.equals(this.endDate, substitutesRuleD.endDate) &&
        Objects.equals(this.fullName, substitutesRuleD.fullName) &&
        Objects.equals(this.mode, substitutesRuleD.mode) &&
        Objects.equals(this.isEnabled, substitutesRuleD.isEnabled) &&
        Objects.equals(this.supportsDeleteSubstitutionRule, substitutesRuleD.supportsDeleteSubstitutionRule) &&
        Objects.equals(this.supportsEnableSubstitutionRule, substitutesRuleD.supportsEnableSubstitutionRule);
  }

  @Override
  public int hashCode() {
    return Objects.hash(metadata, substitutionRuleID, saPOrigin, user, beginDate, endDate, fullName, mode, isEnabled, supportsDeleteSubstitutionRule, supportsEnableSubstitutionRule, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class SubstitutesRuleD {\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    substitutionRuleID: ").append(toIndentedString(substitutionRuleID)).append("\n");
    sb.append("    saPOrigin: ").append(toIndentedString(saPOrigin)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    beginDate: ").append(toIndentedString(beginDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    isEnabled: ").append(toIndentedString(isEnabled)).append("\n");
    sb.append("    supportsDeleteSubstitutionRule: ").append(toIndentedString(supportsDeleteSubstitutionRule)).append("\n");
    sb.append("    supportsEnableSubstitutionRule: ").append(toIndentedString(supportsEnableSubstitutionRule)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

