

/*
 * Inbox
 * This API provides the functionality for building \"own inbox\" capabilities on top of SAP Build Process Automation. It is based on the task consumption model (TCM) as documented in SAP Note [2304317](https://launchpad.support.sap.com/#/notes/2304317/E).  Only users who have the ProcessAutomationParticipant role assigned are able to use the Inbox API.  SAP Build Process Automation currently supports only a subset of the Task Consumption Model capabilities. Only the functionality included in this document is available.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.openapi.sbpaworkflow.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sap.openapi.sbpaworkflow.model.SubstitutionDeleteRuleDDeleteSubstitutionRuleMetadata;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * SubstitutionDeleteRuleDDeleteSubstitutionRule
 */
// CHECKSTYLE:OFF
public class SubstitutionDeleteRuleDDeleteSubstitutionRule 
// CHECKSTYLE:ON
{
  @JsonProperty("__metadata")
  private SubstitutionDeleteRuleDDeleteSubstitutionRuleMetadata metadata;

  @JsonProperty("Deleted")
  private Boolean deleted;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /**
   * Set the metadata of this {@link SubstitutionDeleteRuleDDeleteSubstitutionRule} instance and return the same instance.
   *
   * @param metadata  The metadata of this {@link SubstitutionDeleteRuleDDeleteSubstitutionRule}
   * @return The same instance of this {@link SubstitutionDeleteRuleDDeleteSubstitutionRule} class
   */
  @Nonnull public SubstitutionDeleteRuleDDeleteSubstitutionRule metadata( @Nullable final SubstitutionDeleteRuleDDeleteSubstitutionRuleMetadata metadata) {
    this.metadata = metadata;
    return this;
  }

  /**
   * Get metadata
   * @return metadata  The metadata of this {@link SubstitutionDeleteRuleDDeleteSubstitutionRule} instance.
   */
  @Nonnull
  public SubstitutionDeleteRuleDDeleteSubstitutionRuleMetadata getMetadata() {
    return metadata;
  }

  /**
   * Set the metadata of this {@link SubstitutionDeleteRuleDDeleteSubstitutionRule} instance.
   *
   * @param metadata  The metadata of this {@link SubstitutionDeleteRuleDDeleteSubstitutionRule}
   */
  public void setMetadata( @Nullable final SubstitutionDeleteRuleDDeleteSubstitutionRuleMetadata metadata) {
    this.metadata = metadata;
  }

  /**
   * Set the deleted of this {@link SubstitutionDeleteRuleDDeleteSubstitutionRule} instance and return the same instance.
   *
   * @param deleted  Indicates whether the substitution rule with specified id is removed or not.
   * @return The same instance of this {@link SubstitutionDeleteRuleDDeleteSubstitutionRule} class
   */
  @Nonnull public SubstitutionDeleteRuleDDeleteSubstitutionRule deleted( @Nullable final Boolean deleted) {
    this.deleted = deleted;
    return this;
  }

  /**
   * Indicates whether the substitution rule with specified id is removed or not.
   * @return deleted  The deleted of this {@link SubstitutionDeleteRuleDDeleteSubstitutionRule} instance.
   */
  @Nonnull
  public Boolean isDeleted() {
    return deleted;
  }

  /**
   * Set the deleted of this {@link SubstitutionDeleteRuleDDeleteSubstitutionRule} instance.
   *
   * @param deleted  Indicates whether the substitution rule with specified id is removed or not.
   */
  public void setDeleted( @Nullable final Boolean deleted) {
    this.deleted = deleted;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link SubstitutionDeleteRuleDDeleteSubstitutionRule}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link SubstitutionDeleteRuleDDeleteSubstitutionRule} instance.
   * @deprecated Use {@link #toMap()} instead.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField( @Nonnull final String name ) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("SubstitutionDeleteRuleDDeleteSubstitutionRule has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link SubstitutionDeleteRuleDDeleteSubstitutionRule} instance including unrecognized properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap()
  {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if( metadata != null ) declaredFields.put("metadata", metadata);
    if( deleted != null ) declaredFields.put("deleted", deleted);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link SubstitutionDeleteRuleDDeleteSubstitutionRule} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final SubstitutionDeleteRuleDDeleteSubstitutionRule substitutionDeleteRuleDDeleteSubstitutionRule = (SubstitutionDeleteRuleDDeleteSubstitutionRule) o;
    return Objects.equals(this.cloudSdkCustomFields, substitutionDeleteRuleDDeleteSubstitutionRule.cloudSdkCustomFields) &&
        Objects.equals(this.metadata, substitutionDeleteRuleDDeleteSubstitutionRule.metadata) &&
        Objects.equals(this.deleted, substitutionDeleteRuleDDeleteSubstitutionRule.deleted);
  }

  @Override
  public int hashCode() {
    return Objects.hash(metadata, deleted, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class SubstitutionDeleteRuleDDeleteSubstitutionRule {\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

