

/*
 * Inbox
 * This API provides the functionality for building \"own inbox\" capabilities on top of SAP Build Process Automation. It is based on the task consumption model (TCM) as documented in SAP Note [2304317](https://launchpad.support.sap.com/#/notes/2304317/E).  Only users who have the ProcessAutomationParticipant role assigned are able to use the Inbox API.  SAP Build Process Automation currently supports only a subset of the Task Consumption Model capabilities. Only the functionality included in this document is available.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.openapi.sbpaworkflow.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sap.openapi.sbpaworkflow.model.SubstitutionDeleteRuleDDeleteSubstitutionRule;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * SubstitutionDeleteRuleD
 */
// CHECKSTYLE:OFF
public class SubstitutionDeleteRuleD 
// CHECKSTYLE:ON
{
  @JsonProperty("DeleteSubstitutionRule")
  private SubstitutionDeleteRuleDDeleteSubstitutionRule deleteSubstitutionRule;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /**
   * Set the deleteSubstitutionRule of this {@link SubstitutionDeleteRuleD} instance and return the same instance.
   *
   * @param deleteSubstitutionRule  The deleteSubstitutionRule of this {@link SubstitutionDeleteRuleD}
   * @return The same instance of this {@link SubstitutionDeleteRuleD} class
   */
  @Nonnull public SubstitutionDeleteRuleD deleteSubstitutionRule( @Nullable final SubstitutionDeleteRuleDDeleteSubstitutionRule deleteSubstitutionRule) {
    this.deleteSubstitutionRule = deleteSubstitutionRule;
    return this;
  }

  /**
   * Get deleteSubstitutionRule
   * @return deleteSubstitutionRule  The deleteSubstitutionRule of this {@link SubstitutionDeleteRuleD} instance.
   */
  @Nonnull
  public SubstitutionDeleteRuleDDeleteSubstitutionRule getDeleteSubstitutionRule() {
    return deleteSubstitutionRule;
  }

  /**
   * Set the deleteSubstitutionRule of this {@link SubstitutionDeleteRuleD} instance.
   *
   * @param deleteSubstitutionRule  The deleteSubstitutionRule of this {@link SubstitutionDeleteRuleD}
   */
  public void setDeleteSubstitutionRule( @Nullable final SubstitutionDeleteRuleDDeleteSubstitutionRule deleteSubstitutionRule) {
    this.deleteSubstitutionRule = deleteSubstitutionRule;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link SubstitutionDeleteRuleD}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link SubstitutionDeleteRuleD} instance.
   * @deprecated Use {@link #toMap()} instead.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField( @Nonnull final String name ) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("SubstitutionDeleteRuleD has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link SubstitutionDeleteRuleD} instance including unrecognized properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap()
  {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if( deleteSubstitutionRule != null ) declaredFields.put("deleteSubstitutionRule", deleteSubstitutionRule);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link SubstitutionDeleteRuleD} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final SubstitutionDeleteRuleD substitutionDeleteRuleD = (SubstitutionDeleteRuleD) o;
    return Objects.equals(this.cloudSdkCustomFields, substitutionDeleteRuleD.cloudSdkCustomFields) &&
        Objects.equals(this.deleteSubstitutionRule, substitutionDeleteRuleD.deleteSubstitutionRule);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deleteSubstitutionRule, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class SubstitutionDeleteRuleD {\n");
    sb.append("    deleteSubstitutionRule: ").append(toIndentedString(deleteSubstitutionRule)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

