

/*
 * Inbox
 * This API provides the functionality for building \"own inbox\" capabilities on top of SAP Build Process Automation. It is based on the task consumption model (TCM) as documented in SAP Note [2304317](https://launchpad.support.sap.com/#/notes/2304317/E).  Only users who have the ProcessAutomationParticipant role assigned are able to use the Inbox API.  SAP Build Process Automation currently supports only a subset of the Task Consumption Model capabilities. Only the functionality included in this document is available.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.openapi.sbpaworkflow.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.sap.openapi.sbpaworkflow.customserializer.OffsetDateTimeSerializer;
import com.sap.openapi.sbpaworkflow.model.SubstitutionRuleCreatePayloadMetadata;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * SubstitutionRuleCreatePayload
 */
// CHECKSTYLE:OFF
public class SubstitutionRuleCreatePayload 
// CHECKSTYLE:ON
{
  @JsonProperty("__metadata")
  private SubstitutionRuleCreatePayloadMetadata metadata;

  @JsonProperty("SAP__Origin")
  private String saPOrigin;

  @JsonProperty("User")
  private String user;

  @JsonProperty("BeginDate")
  @JsonSerialize(using = OffsetDateTimeSerializer.class)
  private OffsetDateTime beginDate;

  @JsonProperty("EndDate")
  @JsonSerialize(using = OffsetDateTimeSerializer.class)
  private OffsetDateTime endDate;

  /**
   * The mode of the new substitution rule.  - RECEIVE_TASKS (planned substitution): The substitution rule is enabled immediately. The substitute receives the tasks of the substituted user in the defined period. - TAKE_OVER (unplanned substitution): The substitution rule is disabled by default and can be enabled by the substitute when needed (unplanned absence of substituted user). If enabled, the substitute receives the tasks of the substituted user starting on the defined begin date.
   */
  public enum ModeEnum {
    /**
    * The RECEIVE_TASKS option of this SubstitutionRuleCreatePayload
    */
    RECEIVE_TASKS("RECEIVE_TASKS"),
    
    /**
    * The TAKE_OVER option of this SubstitutionRuleCreatePayload
    */
    TAKE_OVER("TAKE_OVER");

    private String value;

    ModeEnum(String value) {
      this.value = value;
    }

    /**
    * Get the value of the enum
    * @return The enum value
    */
    @JsonValue
    @Nonnull public String getValue() {
      return value;
    }

    /**
    * Get the String value of the enum value.
    * @return The enum value as String
    */
    @Override
    @Nonnull public String toString() {
      return String.valueOf(value);
    }

    /**
    * Get the enum value from a String value
    * @param value The String value
    * @return The enum value of type SubstitutionRuleCreatePayload
    */
    @JsonCreator
    @Nonnull public static ModeEnum fromValue(@Nonnull final String value) {
      for (ModeEnum b : ModeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  @JsonProperty("Mode")
  private ModeEnum mode;

  @JsonProperty("IsEnabled")
  private Boolean isEnabled;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /**
   * Set the metadata of this {@link SubstitutionRuleCreatePayload} instance and return the same instance.
   *
   * @param metadata  The metadata of this {@link SubstitutionRuleCreatePayload}
   * @return The same instance of this {@link SubstitutionRuleCreatePayload} class
   */
  @Nonnull public SubstitutionRuleCreatePayload metadata( @Nullable final SubstitutionRuleCreatePayloadMetadata metadata) {
    this.metadata = metadata;
    return this;
  }

  /**
   * Get metadata
   * @return metadata  The metadata of this {@link SubstitutionRuleCreatePayload} instance.
   */
  @Nonnull
  public SubstitutionRuleCreatePayloadMetadata getMetadata() {
    return metadata;
  }

  /**
   * Set the metadata of this {@link SubstitutionRuleCreatePayload} instance.
   *
   * @param metadata  The metadata of this {@link SubstitutionRuleCreatePayload}
   */
  public void setMetadata( @Nullable final SubstitutionRuleCreatePayloadMetadata metadata) {
    this.metadata = metadata;
  }

  /**
   * Set the saPOrigin of this {@link SubstitutionRuleCreatePayload} instance and return the same instance.
   *
   * @param saPOrigin  The SID discriminator. Set to &#39;NA&#39; for all entities. For more information, see the Task Consumption Model documentation in SAP Note [2304317](https://launchpad.support.sap.com/#/notes/2304317/E).
   * @return The same instance of this {@link SubstitutionRuleCreatePayload} class
   */
  @Nonnull public SubstitutionRuleCreatePayload saPOrigin( @Nonnull final String saPOrigin) {
    this.saPOrigin = saPOrigin;
    return this;
  }

  /**
   * The SID discriminator. Set to &#39;NA&#39; for all entities. For more information, see the Task Consumption Model documentation in SAP Note [2304317](https://launchpad.support.sap.com/#/notes/2304317/E).
   * @return saPOrigin  The saPOrigin of this {@link SubstitutionRuleCreatePayload} instance.
   */
  @Nonnull
  public String getSaPOrigin() {
    return saPOrigin;
  }

  /**
   * Set the saPOrigin of this {@link SubstitutionRuleCreatePayload} instance.
   *
   * @param saPOrigin  The SID discriminator. Set to &#39;NA&#39; for all entities. For more information, see the Task Consumption Model documentation in SAP Note [2304317](https://launchpad.support.sap.com/#/notes/2304317/E).
   */
  public void setSaPOrigin( @Nonnull final String saPOrigin) {
    this.saPOrigin = saPOrigin;
  }

  /**
   * Set the user of this {@link SubstitutionRuleCreatePayload} instance and return the same instance.
   *
   * @param user  The user who should substitute the current user.
   * @return The same instance of this {@link SubstitutionRuleCreatePayload} class
   */
  @Nonnull public SubstitutionRuleCreatePayload user( @Nonnull final String user) {
    this.user = user;
    return this;
  }

  /**
   * The user who should substitute the current user.
   * @return user  The user of this {@link SubstitutionRuleCreatePayload} instance.
   */
  @Nonnull
  public String getUser() {
    return user;
  }

  /**
   * Set the user of this {@link SubstitutionRuleCreatePayload} instance.
   *
   * @param user  The user who should substitute the current user.
   */
  public void setUser( @Nonnull final String user) {
    this.user = user;
  }

  /**
   * Set the beginDate of this {@link SubstitutionRuleCreatePayload} instance and return the same instance.
   *
   * @param beginDate  The date on which the substitution should begin. It expects a UTC date. Please make sure to convert your timezone to UTC before sending a request.  Additional requirements apply: - It must be yesterday, today or in the future.
   * @return The same instance of this {@link SubstitutionRuleCreatePayload} class
   */
  @Nonnull public SubstitutionRuleCreatePayload beginDate( @Nonnull final OffsetDateTime beginDate) {
    this.beginDate = beginDate;
    return this;
  }

  /**
   * The date on which the substitution should begin. It expects a UTC date. Please make sure to convert your timezone to UTC before sending a request.  Additional requirements apply: - It must be yesterday, today or in the future.
   * @return beginDate  The beginDate of this {@link SubstitutionRuleCreatePayload} instance.
   */
  @Nonnull
  public OffsetDateTime getBeginDate() {
    return beginDate;
  }

  /**
   * Set the beginDate of this {@link SubstitutionRuleCreatePayload} instance.
   *
   * @param beginDate  The date on which the substitution should begin. It expects a UTC date. Please make sure to convert your timezone to UTC before sending a request.  Additional requirements apply: - It must be yesterday, today or in the future.
   */
  public void setBeginDate( @Nonnull final OffsetDateTime beginDate) {
    this.beginDate = beginDate;
  }

  /**
   * Set the endDate of this {@link SubstitutionRuleCreatePayload} instance and return the same instance.
   *
   * @param endDate  The date on which the substitution should end. It expects a UTC date.  Additional requirements apply: - If the mode is &#39;RECEIVE_TASKS&#39;, it is required. Otherwise, it is ignored and set to null. - It must be equal to the begin date or be more recent. But it cannot be in the past.
   * @return The same instance of this {@link SubstitutionRuleCreatePayload} class
   */
  @Nonnull public SubstitutionRuleCreatePayload endDate( @Nullable final OffsetDateTime endDate) {
    this.endDate = endDate;
    return this;
  }

  /**
   * The date on which the substitution should end. It expects a UTC date.  Additional requirements apply: - If the mode is &#39;RECEIVE_TASKS&#39;, it is required. Otherwise, it is ignored and set to null. - It must be equal to the begin date or be more recent. But it cannot be in the past.
   * @return endDate  The endDate of this {@link SubstitutionRuleCreatePayload} instance.
   */
  @Nonnull
  public OffsetDateTime getEndDate() {
    return endDate;
  }

  /**
   * Set the endDate of this {@link SubstitutionRuleCreatePayload} instance.
   *
   * @param endDate  The date on which the substitution should end. It expects a UTC date.  Additional requirements apply: - If the mode is &#39;RECEIVE_TASKS&#39;, it is required. Otherwise, it is ignored and set to null. - It must be equal to the begin date or be more recent. But it cannot be in the past.
   */
  public void setEndDate( @Nullable final OffsetDateTime endDate) {
    this.endDate = endDate;
  }

  /**
   * Set the mode of this {@link SubstitutionRuleCreatePayload} instance and return the same instance.
   *
   * @param mode  The mode of the new substitution rule.  - RECEIVE_TASKS (planned substitution): The substitution rule is enabled immediately. The substitute receives the tasks of the substituted user in the defined period. - TAKE_OVER (unplanned substitution): The substitution rule is disabled by default and can be enabled by the substitute when needed (unplanned absence of substituted user). If enabled, the substitute receives the tasks of the substituted user starting on the defined begin date.
   * @return The same instance of this {@link SubstitutionRuleCreatePayload} class
   */
  @Nonnull public SubstitutionRuleCreatePayload mode( @Nonnull final ModeEnum mode) {
    this.mode = mode;
    return this;
  }

  /**
   * The mode of the new substitution rule.  - RECEIVE_TASKS (planned substitution): The substitution rule is enabled immediately. The substitute receives the tasks of the substituted user in the defined period. - TAKE_OVER (unplanned substitution): The substitution rule is disabled by default and can be enabled by the substitute when needed (unplanned absence of substituted user). If enabled, the substitute receives the tasks of the substituted user starting on the defined begin date.
   * @return mode  The mode of this {@link SubstitutionRuleCreatePayload} instance.
   */
  @Nonnull
  public ModeEnum getMode() {
    return mode;
  }

  /**
   * Set the mode of this {@link SubstitutionRuleCreatePayload} instance.
   *
   * @param mode  The mode of the new substitution rule.  - RECEIVE_TASKS (planned substitution): The substitution rule is enabled immediately. The substitute receives the tasks of the substituted user in the defined period. - TAKE_OVER (unplanned substitution): The substitution rule is disabled by default and can be enabled by the substitute when needed (unplanned absence of substituted user). If enabled, the substitute receives the tasks of the substituted user starting on the defined begin date.
   */
  public void setMode( @Nonnull final ModeEnum mode) {
    this.mode = mode;
  }

  /**
   * Set the isEnabled of this {@link SubstitutionRuleCreatePayload} instance and return the same instance.
   *
   * @param isEnabled  Indicates whether the new substitution rule should be enabled.  Additional requirements apply: - If mode is &#39;RECEIVE_TASKS&#39;, it must be &#39;true&#39;. - If mode is &#39;TAKE_OVER&#39;, it must be &#39;false&#39;.
   * @return The same instance of this {@link SubstitutionRuleCreatePayload} class
   */
  @Nonnull public SubstitutionRuleCreatePayload isEnabled( @Nonnull final Boolean isEnabled) {
    this.isEnabled = isEnabled;
    return this;
  }

  /**
   * Indicates whether the new substitution rule should be enabled.  Additional requirements apply: - If mode is &#39;RECEIVE_TASKS&#39;, it must be &#39;true&#39;. - If mode is &#39;TAKE_OVER&#39;, it must be &#39;false&#39;.
   * @return isEnabled  The isEnabled of this {@link SubstitutionRuleCreatePayload} instance.
   */
  @Nonnull
  public Boolean isIsEnabled() {
    return isEnabled;
  }

  /**
   * Set the isEnabled of this {@link SubstitutionRuleCreatePayload} instance.
   *
   * @param isEnabled  Indicates whether the new substitution rule should be enabled.  Additional requirements apply: - If mode is &#39;RECEIVE_TASKS&#39;, it must be &#39;true&#39;. - If mode is &#39;TAKE_OVER&#39;, it must be &#39;false&#39;.
   */
  public void setIsEnabled( @Nonnull final Boolean isEnabled) {
    this.isEnabled = isEnabled;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link SubstitutionRuleCreatePayload}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link SubstitutionRuleCreatePayload} instance.
   * @deprecated Use {@link #toMap()} instead.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField( @Nonnull final String name ) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("SubstitutionRuleCreatePayload has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link SubstitutionRuleCreatePayload} instance including unrecognized properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap()
  {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if( metadata != null ) declaredFields.put("metadata", metadata);
    if( saPOrigin != null ) declaredFields.put("saPOrigin", saPOrigin);
    if( user != null ) declaredFields.put("user", user);
    if( beginDate != null ) declaredFields.put("beginDate", beginDate);
    if( endDate != null ) declaredFields.put("endDate", endDate);
    if( mode != null ) declaredFields.put("mode", mode);
    if( isEnabled != null ) declaredFields.put("isEnabled", isEnabled);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link SubstitutionRuleCreatePayload} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final SubstitutionRuleCreatePayload substitutionRuleCreatePayload = (SubstitutionRuleCreatePayload) o;
    return Objects.equals(this.cloudSdkCustomFields, substitutionRuleCreatePayload.cloudSdkCustomFields) &&
        Objects.equals(this.metadata, substitutionRuleCreatePayload.metadata) &&
        Objects.equals(this.saPOrigin, substitutionRuleCreatePayload.saPOrigin) &&
        Objects.equals(this.user, substitutionRuleCreatePayload.user) &&
        Objects.equals(this.beginDate, substitutionRuleCreatePayload.beginDate) &&
        Objects.equals(this.endDate, substitutionRuleCreatePayload.endDate) &&
        Objects.equals(this.mode, substitutionRuleCreatePayload.mode) &&
        Objects.equals(this.isEnabled, substitutionRuleCreatePayload.isEnabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(metadata, saPOrigin, user, beginDate, endDate, mode, isEnabled, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class SubstitutionRuleCreatePayload {\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    saPOrigin: ").append(toIndentedString(saPOrigin)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    beginDate: ").append(toIndentedString(beginDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    isEnabled: ").append(toIndentedString(isEnabled)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

