

/*
 * Inbox
 * This API provides the functionality for building \"own inbox\" capabilities on top of SAP Build Process Automation. It is based on the task consumption model (TCM) as documented in SAP Note [2304317](https://launchpad.support.sap.com/#/notes/2304317/E).  Only users who have the ProcessAutomationParticipant role assigned are able to use the Inbox API.  SAP Build Process Automation currently supports only a subset of the Task Consumption Model capabilities. Only the functionality included in this document is available.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.openapi.sbpaworkflow.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sap.openapi.sbpaworkflow.model.TaskDescriptionDMetadata;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * TaskDescriptionD
 */
// CHECKSTYLE:OFF
public class TaskDescriptionD 
// CHECKSTYLE:ON
{
  @JsonProperty("__metadata")
  private TaskDescriptionDMetadata metadata;

  @JsonProperty("InstanceID")
  private String instanceID;

  @JsonProperty("SAP__Origin")
  private String saPOrigin = "NA";

  @JsonProperty("Description")
  private String description;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /**
   * Set the metadata of this {@link TaskDescriptionD} instance and return the same instance.
   *
   * @param metadata  The metadata of this {@link TaskDescriptionD}
   * @return The same instance of this {@link TaskDescriptionD} class
   */
  @Nonnull public TaskDescriptionD metadata( @Nullable final TaskDescriptionDMetadata metadata) {
    this.metadata = metadata;
    return this;
  }

  /**
   * Get metadata
   * @return metadata  The metadata of this {@link TaskDescriptionD} instance.
   */
  @Nonnull
  public TaskDescriptionDMetadata getMetadata() {
    return metadata;
  }

  /**
   * Set the metadata of this {@link TaskDescriptionD} instance.
   *
   * @param metadata  The metadata of this {@link TaskDescriptionD}
   */
  public void setMetadata( @Nullable final TaskDescriptionDMetadata metadata) {
    this.metadata = metadata;
  }

  /**
   * Set the instanceID of this {@link TaskDescriptionD} instance and return the same instance.
   *
   * @param instanceID  The ID of the task to which the description belongs.
   * @return The same instance of this {@link TaskDescriptionD} class
   */
  @Nonnull public TaskDescriptionD instanceID( @Nullable final String instanceID) {
    this.instanceID = instanceID;
    return this;
  }

  /**
   * The ID of the task to which the description belongs.
   * @return instanceID  The instanceID of this {@link TaskDescriptionD} instance.
   */
  @Nonnull
  public String getInstanceID() {
    return instanceID;
  }

  /**
   * Set the instanceID of this {@link TaskDescriptionD} instance.
   *
   * @param instanceID  The ID of the task to which the description belongs.
   */
  public void setInstanceID( @Nullable final String instanceID) {
    this.instanceID = instanceID;
  }

  /**
   * Set the saPOrigin of this {@link TaskDescriptionD} instance and return the same instance.
   *
   * @param saPOrigin  The SID discriminator. Set to &#39;NA&#39; for all entities. For more information, see the Task Consumption Model documentation in SAP Note [2304317](https://launchpad.support.sap.com/#/notes/2304317/E).
   * @return The same instance of this {@link TaskDescriptionD} class
   */
  @Nonnull public TaskDescriptionD saPOrigin( @Nullable final String saPOrigin) {
    this.saPOrigin = saPOrigin;
    return this;
  }

  /**
   * The SID discriminator. Set to &#39;NA&#39; for all entities. For more information, see the Task Consumption Model documentation in SAP Note [2304317](https://launchpad.support.sap.com/#/notes/2304317/E).
   * @return saPOrigin  The saPOrigin of this {@link TaskDescriptionD} instance.
   */
  @Nonnull
  public String getSaPOrigin() {
    return saPOrigin;
  }

  /**
   * Set the saPOrigin of this {@link TaskDescriptionD} instance.
   *
   * @param saPOrigin  The SID discriminator. Set to &#39;NA&#39; for all entities. For more information, see the Task Consumption Model documentation in SAP Note [2304317](https://launchpad.support.sap.com/#/notes/2304317/E).
   */
  public void setSaPOrigin( @Nullable final String saPOrigin) {
    this.saPOrigin = saPOrigin;
  }

  /**
   * Set the description of this {@link TaskDescriptionD} instance and return the same instance.
   *
   * @param description  The description of the task.
   * @return The same instance of this {@link TaskDescriptionD} class
   */
  @Nonnull public TaskDescriptionD description( @Nullable final String description) {
    this.description = description;
    return this;
  }

  /**
   * The description of the task.
   * @return description  The description of this {@link TaskDescriptionD} instance.
   */
  @Nonnull
  public String getDescription() {
    return description;
  }

  /**
   * Set the description of this {@link TaskDescriptionD} instance.
   *
   * @param description  The description of the task.
   */
  public void setDescription( @Nullable final String description) {
    this.description = description;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link TaskDescriptionD}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link TaskDescriptionD} instance.
   * @deprecated Use {@link #toMap()} instead.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField( @Nonnull final String name ) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("TaskDescriptionD has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link TaskDescriptionD} instance including unrecognized properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap()
  {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if( metadata != null ) declaredFields.put("metadata", metadata);
    if( instanceID != null ) declaredFields.put("instanceID", instanceID);
    if( saPOrigin != null ) declaredFields.put("saPOrigin", saPOrigin);
    if( description != null ) declaredFields.put("description", description);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link TaskDescriptionD} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final TaskDescriptionD taskDescriptionD = (TaskDescriptionD) o;
    return Objects.equals(this.cloudSdkCustomFields, taskDescriptionD.cloudSdkCustomFields) &&
        Objects.equals(this.metadata, taskDescriptionD.metadata) &&
        Objects.equals(this.instanceID, taskDescriptionD.instanceID) &&
        Objects.equals(this.saPOrigin, taskDescriptionD.saPOrigin) &&
        Objects.equals(this.description, taskDescriptionD.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(metadata, instanceID, saPOrigin, description, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class TaskDescriptionD {\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    instanceID: ").append(toIndentedString(instanceID)).append("\n");
    sb.append("    saPOrigin: ").append(toIndentedString(saPOrigin)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

