

/*
 * Inbox
 * This API provides the functionality for building \"own inbox\" capabilities on top of SAP Build Process Automation. It is based on the task consumption model (TCM) as documented in SAP Note [2304317](https://launchpad.support.sap.com/#/notes/2304317/E).  Only users who have the ProcessAutomationParticipant role assigned are able to use the Inbox API.  SAP Build Process Automation currently supports only a subset of the Task Consumption Model capabilities. Only the functionality included in this document is available.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.openapi.sbpaworkflow.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.sap.openapi.sbpaworkflow.customserializer.OffsetDateTimeDeserializer;
import com.sap.openapi.sbpaworkflow.model.TaskInstanceDDescription;
import com.sap.openapi.sbpaworkflow.model.TaskInstanceDMetadata;
import com.sap.openapi.sbpaworkflow.model.TaskInstanceDTaskSupports;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * TaskInstanceD
 */
// CHECKSTYLE:OFF
public class TaskInstanceD 
// CHECKSTYLE:ON
{
  @JsonProperty("__metadata")
  private TaskInstanceDMetadata metadata;

  @JsonProperty("InstanceID")
  private String instanceID;

  @JsonProperty("SAP__Origin")
  private String saPOrigin = "NA";

  @JsonProperty("TaskDefinitionID")
  private String taskDefinitionID;

  @JsonProperty("TaskDefinitionName")
  private String taskDefinitionName;

  /**
   * The current status of the task.
   */
  public enum StatusEnum {
    /**
    * The READY option of this TaskInstanceD
    */
    READY("READY"),
    
    /**
    * The RESERVED option of this TaskInstanceD
    */
    RESERVED("RESERVED"),
    
    /**
    * The CANCELED option of this TaskInstanceD
    */
    CANCELED("CANCELED"),
    
    /**
    * The COMPLETED option of this TaskInstanceD
    */
    COMPLETED("COMPLETED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    /**
    * Get the value of the enum
    * @return The enum value
    */
    @JsonValue
    @Nonnull public String getValue() {
      return value;
    }

    /**
    * Get the String value of the enum value.
    * @return The enum value as String
    */
    @Override
    @Nonnull public String toString() {
      return String.valueOf(value);
    }

    /**
    * Get the enum value from a String value
    * @param value The String value
    * @return The enum value of type TaskInstanceD
    */
    @JsonCreator
    @Nonnull public static StatusEnum fromValue(@Nonnull final String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  @JsonProperty("Status")
  private StatusEnum status;

  @JsonProperty("TaskTitle")
  private String taskTitle;

  @JsonProperty("HasComments")
  private Boolean hasComments = false;

  @JsonProperty("HasAttachments")
  private Boolean hasAttachments = false;

  @JsonProperty("HasPotentialOwners")
  private Boolean hasPotentialOwners = false;

  @JsonProperty("SupportsClaim")
  private Boolean supportsClaim;

  @JsonProperty("SupportsRelease")
  private Boolean supportsRelease;

  @JsonProperty("SupportsForward")
  private Boolean supportsForward = false;

  @JsonProperty("SupportsComments")
  private Boolean supportsComments = false;

  @JsonProperty("SupportsAttachments")
  private Boolean supportsAttachments = false;

  @JsonProperty("CreatedOn")
  @JsonDeserialize(using = OffsetDateTimeDeserializer.class)
  private OffsetDateTime createdOn;

  @JsonProperty("CreatedBy")
  private String createdBy;

  @JsonProperty("CreatedByName")
  private String createdByName;

  @JsonProperty("Processor")
  private String processor;

  @JsonProperty("CompletionDeadLine")
  @JsonDeserialize(using = OffsetDateTimeDeserializer.class)
  private OffsetDateTime completionDeadLine;

  @JsonProperty("SubstitutedUserName")
  private String substitutedUserName;

  /**
   * The priority of the task.
   */
  public enum PriorityEnum {
    /**
    * The LOW option of this TaskInstanceD
    */
    LOW("LOW"),
    
    /**
    * The MEDIUM option of this TaskInstanceD
    */
    MEDIUM("MEDIUM"),
    
    /**
    * The HIGH option of this TaskInstanceD
    */
    HIGH("HIGH"),
    
    /**
    * The VERY_HIGH option of this TaskInstanceD
    */
    VERY_HIGH("VERY_HIGH");

    private String value;

    PriorityEnum(String value) {
      this.value = value;
    }

    /**
    * Get the value of the enum
    * @return The enum value
    */
    @JsonValue
    @Nonnull public String getValue() {
      return value;
    }

    /**
    * Get the String value of the enum value.
    * @return The enum value as String
    */
    @Override
    @Nonnull public String toString() {
      return String.valueOf(value);
    }

    /**
    * Get the enum value from a String value
    * @param value The String value
    * @return The enum value of type TaskInstanceD
    */
    @JsonCreator
    @Nonnull public static PriorityEnum fromValue(@Nonnull final String value) {
      for (PriorityEnum b : PriorityEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  @JsonProperty("Priority")
  private PriorityEnum priority;

  @JsonProperty("PriorityNumber")
  private Integer priorityNumber;

  @JsonProperty("TaskSupports")
  private TaskInstanceDTaskSupports taskSupports;

  @JsonProperty("GUI_Link")
  private String guILink;

  @JsonProperty("Description")
  private TaskInstanceDDescription description;

  @JsonProperty("TaskDefinitionData")
  private TaskInstanceDDescription taskDefinitionData;

  @JsonProperty("CustomAttributeData")
  private TaskInstanceDDescription customAttributeData;

  @JsonProperty("WorkflowLogs")
  private TaskInstanceDDescription workflowLogs;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /**
   * Set the metadata of this {@link TaskInstanceD} instance and return the same instance.
   *
   * @param metadata  The metadata of this {@link TaskInstanceD}
   * @return The same instance of this {@link TaskInstanceD} class
   */
  @Nonnull public TaskInstanceD metadata( @Nullable final TaskInstanceDMetadata metadata) {
    this.metadata = metadata;
    return this;
  }

  /**
   * Get metadata
   * @return metadata  The metadata of this {@link TaskInstanceD} instance.
   */
  @Nonnull
  public TaskInstanceDMetadata getMetadata() {
    return metadata;
  }

  /**
   * Set the metadata of this {@link TaskInstanceD} instance.
   *
   * @param metadata  The metadata of this {@link TaskInstanceD}
   */
  public void setMetadata( @Nullable final TaskInstanceDMetadata metadata) {
    this.metadata = metadata;
  }

  /**
   * Set the instanceID of this {@link TaskInstanceD} instance and return the same instance.
   *
   * @param instanceID  The ID of the task.
   * @return The same instance of this {@link TaskInstanceD} class
   */
  @Nonnull public TaskInstanceD instanceID( @Nullable final String instanceID) {
    this.instanceID = instanceID;
    return this;
  }

  /**
   * The ID of the task.
   * @return instanceID  The instanceID of this {@link TaskInstanceD} instance.
   */
  @Nonnull
  public String getInstanceID() {
    return instanceID;
  }

  /**
   * Set the instanceID of this {@link TaskInstanceD} instance.
   *
   * @param instanceID  The ID of the task.
   */
  public void setInstanceID( @Nullable final String instanceID) {
    this.instanceID = instanceID;
  }

  /**
   * Set the saPOrigin of this {@link TaskInstanceD} instance and return the same instance.
   *
   * @param saPOrigin  The SID discriminator. Set to &#39;NA&#39; for all entities. For more information, see the Task Consumption Model documentation in SAP Note [2304317](https://launchpad.support.sap.com/#/notes/2304317/E).
   * @return The same instance of this {@link TaskInstanceD} class
   */
  @Nonnull public TaskInstanceD saPOrigin( @Nullable final String saPOrigin) {
    this.saPOrigin = saPOrigin;
    return this;
  }

  /**
   * The SID discriminator. Set to &#39;NA&#39; for all entities. For more information, see the Task Consumption Model documentation in SAP Note [2304317](https://launchpad.support.sap.com/#/notes/2304317/E).
   * @return saPOrigin  The saPOrigin of this {@link TaskInstanceD} instance.
   */
  @Nonnull
  public String getSaPOrigin() {
    return saPOrigin;
  }

  /**
   * Set the saPOrigin of this {@link TaskInstanceD} instance.
   *
   * @param saPOrigin  The SID discriminator. Set to &#39;NA&#39; for all entities. For more information, see the Task Consumption Model documentation in SAP Note [2304317](https://launchpad.support.sap.com/#/notes/2304317/E).
   */
  public void setSaPOrigin( @Nullable final String saPOrigin) {
    this.saPOrigin = saPOrigin;
  }

  /**
   * Set the taskDefinitionID of this {@link TaskInstanceD} instance and return the same instance.
   *
   * @param taskDefinitionID  The ID of the task definition this task belongs to. The ID consists of the task definition name and the workflow definition ID  in lowercase using the following format: {task definition name}@{workflow definition ID}.
   * @return The same instance of this {@link TaskInstanceD} class
   */
  @Nonnull public TaskInstanceD taskDefinitionID( @Nullable final String taskDefinitionID) {
    this.taskDefinitionID = taskDefinitionID;
    return this;
  }

  /**
   * The ID of the task definition this task belongs to. The ID consists of the task definition name and the workflow definition ID  in lowercase using the following format: {task definition name}@{workflow definition ID}.
   * @return taskDefinitionID  The taskDefinitionID of this {@link TaskInstanceD} instance.
   */
  @Nonnull
  public String getTaskDefinitionID() {
    return taskDefinitionID;
  }

  /**
   * Set the taskDefinitionID of this {@link TaskInstanceD} instance.
   *
   * @param taskDefinitionID  The ID of the task definition this task belongs to. The ID consists of the task definition name and the workflow definition ID  in lowercase using the following format: {task definition name}@{workflow definition ID}.
   */
  public void setTaskDefinitionID( @Nullable final String taskDefinitionID) {
    this.taskDefinitionID = taskDefinitionID;
  }

  /**
   * Set the taskDefinitionName of this {@link TaskInstanceD} instance and return the same instance.
   *
   * @param taskDefinitionName  The modeled task definition name.
   * @return The same instance of this {@link TaskInstanceD} class
   */
  @Nonnull public TaskInstanceD taskDefinitionName( @Nullable final String taskDefinitionName) {
    this.taskDefinitionName = taskDefinitionName;
    return this;
  }

  /**
   * The modeled task definition name.
   * @return taskDefinitionName  The taskDefinitionName of this {@link TaskInstanceD} instance.
   */
  @Nonnull
  public String getTaskDefinitionName() {
    return taskDefinitionName;
  }

  /**
   * Set the taskDefinitionName of this {@link TaskInstanceD} instance.
   *
   * @param taskDefinitionName  The modeled task definition name.
   */
  public void setTaskDefinitionName( @Nullable final String taskDefinitionName) {
    this.taskDefinitionName = taskDefinitionName;
  }

  /**
   * Set the status of this {@link TaskInstanceD} instance and return the same instance.
   *
   * @param status  The current status of the task.
   * @return The same instance of this {@link TaskInstanceD} class
   */
  @Nonnull public TaskInstanceD status( @Nullable final StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * The current status of the task.
   * @return status  The status of this {@link TaskInstanceD} instance.
   */
  @Nonnull
  public StatusEnum getStatus() {
    return status;
  }

  /**
   * Set the status of this {@link TaskInstanceD} instance.
   *
   * @param status  The current status of the task.
   */
  public void setStatus( @Nullable final StatusEnum status) {
    this.status = status;
  }

  /**
   * Set the taskTitle of this {@link TaskInstanceD} instance and return the same instance.
   *
   * @param taskTitle  The title of the task as it appears in the inbox. Translation of this text is currently not supported.
   * @return The same instance of this {@link TaskInstanceD} class
   */
  @Nonnull public TaskInstanceD taskTitle( @Nullable final String taskTitle) {
    this.taskTitle = taskTitle;
    return this;
  }

  /**
   * The title of the task as it appears in the inbox. Translation of this text is currently not supported.
   * @return taskTitle  The taskTitle of this {@link TaskInstanceD} instance.
   */
  @Nonnull
  public String getTaskTitle() {
    return taskTitle;
  }

  /**
   * Set the taskTitle of this {@link TaskInstanceD} instance.
   *
   * @param taskTitle  The title of the task as it appears in the inbox. Translation of this text is currently not supported.
   */
  public void setTaskTitle( @Nullable final String taskTitle) {
    this.taskTitle = taskTitle;
  }

  /**
   * Set the hasComments of this {@link TaskInstanceD} instance and return the same instance.
   *
   * @param hasComments  Indicates whether a task has comments. This is currently not implemented in SAP Workflow service and will always return false. This is subject to change.
   * @return The same instance of this {@link TaskInstanceD} class
   */
  @Nonnull public TaskInstanceD hasComments( @Nullable final Boolean hasComments) {
    this.hasComments = hasComments;
    return this;
  }

  /**
   * Indicates whether a task has comments. This is currently not implemented in SAP Workflow service and will always return false. This is subject to change.
   * @return hasComments  The hasComments of this {@link TaskInstanceD} instance.
   */
  @Nonnull
  public Boolean isHasComments() {
    return hasComments;
  }

  /**
   * Set the hasComments of this {@link TaskInstanceD} instance.
   *
   * @param hasComments  Indicates whether a task has comments. This is currently not implemented in SAP Workflow service and will always return false. This is subject to change.
   */
  public void setHasComments( @Nullable final Boolean hasComments) {
    this.hasComments = hasComments;
  }

  /**
   * Set the hasAttachments of this {@link TaskInstanceD} instance and return the same instance.
   *
   * @param hasAttachments  Indicates whether a task has attachments. This is currently not implemented in SAP Workflow service and will always return false. This is subject to change.
   * @return The same instance of this {@link TaskInstanceD} class
   */
  @Nonnull public TaskInstanceD hasAttachments( @Nullable final Boolean hasAttachments) {
    this.hasAttachments = hasAttachments;
    return this;
  }

  /**
   * Indicates whether a task has attachments. This is currently not implemented in SAP Workflow service and will always return false. This is subject to change.
   * @return hasAttachments  The hasAttachments of this {@link TaskInstanceD} instance.
   */
  @Nonnull
  public Boolean isHasAttachments() {
    return hasAttachments;
  }

  /**
   * Set the hasAttachments of this {@link TaskInstanceD} instance.
   *
   * @param hasAttachments  Indicates whether a task has attachments. This is currently not implemented in SAP Workflow service and will always return false. This is subject to change.
   */
  public void setHasAttachments( @Nullable final Boolean hasAttachments) {
    this.hasAttachments = hasAttachments;
  }

  /**
   * Set the hasPotentialOwners of this {@link TaskInstanceD} instance and return the same instance.
   *
   * @param hasPotentialOwners  Indicates whether a task has potential owners. This is currently not implemented in SAP Workflow service and will always return false. This is subject to change.
   * @return The same instance of this {@link TaskInstanceD} class
   */
  @Nonnull public TaskInstanceD hasPotentialOwners( @Nullable final Boolean hasPotentialOwners) {
    this.hasPotentialOwners = hasPotentialOwners;
    return this;
  }

  /**
   * Indicates whether a task has potential owners. This is currently not implemented in SAP Workflow service and will always return false. This is subject to change.
   * @return hasPotentialOwners  The hasPotentialOwners of this {@link TaskInstanceD} instance.
   */
  @Nonnull
  public Boolean isHasPotentialOwners() {
    return hasPotentialOwners;
  }

  /**
   * Set the hasPotentialOwners of this {@link TaskInstanceD} instance.
   *
   * @param hasPotentialOwners  Indicates whether a task has potential owners. This is currently not implemented in SAP Workflow service and will always return false. This is subject to change.
   */
  public void setHasPotentialOwners( @Nullable final Boolean hasPotentialOwners) {
    this.hasPotentialOwners = hasPotentialOwners;
  }

  /**
   * Set the supportsClaim of this {@link TaskInstanceD} instance and return the same instance.
   *
   * @param supportsClaim  Indicates whether a claim operation on this task is possible. This depends on the life cycle of the task. See [Status Changes for Task Instances](https://help.sap.com/viewer/e157c391253b4ecd93647bf232d18a83/Cloud/en-US/539ab87c451e4c0aa8321d2f226c44d0.html).
   * @return The same instance of this {@link TaskInstanceD} class
   */
  @Nonnull public TaskInstanceD supportsClaim( @Nullable final Boolean supportsClaim) {
    this.supportsClaim = supportsClaim;
    return this;
  }

  /**
   * Indicates whether a claim operation on this task is possible. This depends on the life cycle of the task. See [Status Changes for Task Instances](https://help.sap.com/viewer/e157c391253b4ecd93647bf232d18a83/Cloud/en-US/539ab87c451e4c0aa8321d2f226c44d0.html).
   * @return supportsClaim  The supportsClaim of this {@link TaskInstanceD} instance.
   */
  @Nonnull
  public Boolean isSupportsClaim() {
    return supportsClaim;
  }

  /**
   * Set the supportsClaim of this {@link TaskInstanceD} instance.
   *
   * @param supportsClaim  Indicates whether a claim operation on this task is possible. This depends on the life cycle of the task. See [Status Changes for Task Instances](https://help.sap.com/viewer/e157c391253b4ecd93647bf232d18a83/Cloud/en-US/539ab87c451e4c0aa8321d2f226c44d0.html).
   */
  public void setSupportsClaim( @Nullable final Boolean supportsClaim) {
    this.supportsClaim = supportsClaim;
  }

  /**
   * Set the supportsRelease of this {@link TaskInstanceD} instance and return the same instance.
   *
   * @param supportsRelease  Indicates whether a release operation on this task is possible. This depends on the life cycle of the task. See [Status Changes for Task Instances](https://help.sap.com/viewer/e157c391253b4ecd93647bf232d18a83/Cloud/en-US/539ab87c451e4c0aa8321d2f226c44d0.html).
   * @return The same instance of this {@link TaskInstanceD} class
   */
  @Nonnull public TaskInstanceD supportsRelease( @Nullable final Boolean supportsRelease) {
    this.supportsRelease = supportsRelease;
    return this;
  }

  /**
   * Indicates whether a release operation on this task is possible. This depends on the life cycle of the task. See [Status Changes for Task Instances](https://help.sap.com/viewer/e157c391253b4ecd93647bf232d18a83/Cloud/en-US/539ab87c451e4c0aa8321d2f226c44d0.html).
   * @return supportsRelease  The supportsRelease of this {@link TaskInstanceD} instance.
   */
  @Nonnull
  public Boolean isSupportsRelease() {
    return supportsRelease;
  }

  /**
   * Set the supportsRelease of this {@link TaskInstanceD} instance.
   *
   * @param supportsRelease  Indicates whether a release operation on this task is possible. This depends on the life cycle of the task. See [Status Changes for Task Instances](https://help.sap.com/viewer/e157c391253b4ecd93647bf232d18a83/Cloud/en-US/539ab87c451e4c0aa8321d2f226c44d0.html).
   */
  public void setSupportsRelease( @Nullable final Boolean supportsRelease) {
    this.supportsRelease = supportsRelease;
  }

  /**
   * Set the supportsForward of this {@link TaskInstanceD} instance and return the same instance.
   *
   * @param supportsForward  Indicates whether a forward operation on this task is possible.
   * @return The same instance of this {@link TaskInstanceD} class
   */
  @Nonnull public TaskInstanceD supportsForward( @Nullable final Boolean supportsForward) {
    this.supportsForward = supportsForward;
    return this;
  }

  /**
   * Indicates whether a forward operation on this task is possible.
   * @return supportsForward  The supportsForward of this {@link TaskInstanceD} instance.
   */
  @Nonnull
  public Boolean isSupportsForward() {
    return supportsForward;
  }

  /**
   * Set the supportsForward of this {@link TaskInstanceD} instance.
   *
   * @param supportsForward  Indicates whether a forward operation on this task is possible.
   */
  public void setSupportsForward( @Nullable final Boolean supportsForward) {
    this.supportsForward = supportsForward;
  }

  /**
   * Set the supportsComments of this {@link TaskInstanceD} instance and return the same instance.
   *
   * @param supportsComments  Indicates whether comments on this task are supported. This is currently not implemented in SAP Workflow service and will always return false. This is subject to change.
   * @return The same instance of this {@link TaskInstanceD} class
   */
  @Nonnull public TaskInstanceD supportsComments( @Nullable final Boolean supportsComments) {
    this.supportsComments = supportsComments;
    return this;
  }

  /**
   * Indicates whether comments on this task are supported. This is currently not implemented in SAP Workflow service and will always return false. This is subject to change.
   * @return supportsComments  The supportsComments of this {@link TaskInstanceD} instance.
   */
  @Nonnull
  public Boolean isSupportsComments() {
    return supportsComments;
  }

  /**
   * Set the supportsComments of this {@link TaskInstanceD} instance.
   *
   * @param supportsComments  Indicates whether comments on this task are supported. This is currently not implemented in SAP Workflow service and will always return false. This is subject to change.
   */
  public void setSupportsComments( @Nullable final Boolean supportsComments) {
    this.supportsComments = supportsComments;
  }

  /**
   * Set the supportsAttachments of this {@link TaskInstanceD} instance and return the same instance.
   *
   * @param supportsAttachments  Indicates whether attachments on this task are supported. This is currently not implemented in SAP Workflow service and will always return false. This is subject to change.
   * @return The same instance of this {@link TaskInstanceD} class
   */
  @Nonnull public TaskInstanceD supportsAttachments( @Nullable final Boolean supportsAttachments) {
    this.supportsAttachments = supportsAttachments;
    return this;
  }

  /**
   * Indicates whether attachments on this task are supported. This is currently not implemented in SAP Workflow service and will always return false. This is subject to change.
   * @return supportsAttachments  The supportsAttachments of this {@link TaskInstanceD} instance.
   */
  @Nonnull
  public Boolean isSupportsAttachments() {
    return supportsAttachments;
  }

  /**
   * Set the supportsAttachments of this {@link TaskInstanceD} instance.
   *
   * @param supportsAttachments  Indicates whether attachments on this task are supported. This is currently not implemented in SAP Workflow service and will always return false. This is subject to change.
   */
  public void setSupportsAttachments( @Nullable final Boolean supportsAttachments) {
    this.supportsAttachments = supportsAttachments;
  }

  /**
   * Set the createdOn of this {@link TaskInstanceD} instance and return the same instance.
   *
   * @param createdOn  The time the task was created.
   * @return The same instance of this {@link TaskInstanceD} class
   */
  @Nonnull public TaskInstanceD createdOn( @Nullable final OffsetDateTime createdOn) {
    this.createdOn = createdOn;
    return this;
  }

  /**
   * The time the task was created.
   * @return createdOn  The createdOn of this {@link TaskInstanceD} instance.
   */
  @Nonnull
  public OffsetDateTime getCreatedOn() {
    return createdOn;
  }

  /**
   * Set the createdOn of this {@link TaskInstanceD} instance.
   *
   * @param createdOn  The time the task was created.
   */
  public void setCreatedOn( @Nullable final OffsetDateTime createdOn) {
    this.createdOn = createdOn;
  }

  /**
   * Set the createdBy of this {@link TaskInstanceD} instance and return the same instance.
   *
   * @param createdBy  The user who created the task. The user ID is at most 255 characters long.
   * @return The same instance of this {@link TaskInstanceD} class
   */
  @Nonnull public TaskInstanceD createdBy( @Nullable final String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

  /**
   * The user who created the task. The user ID is at most 255 characters long.
   * @return createdBy  The createdBy of this {@link TaskInstanceD} instance.
   */
  @Nonnull
  public String getCreatedBy() {
    return createdBy;
  }

  /**
   * Set the createdBy of this {@link TaskInstanceD} instance.
   *
   * @param createdBy  The user who created the task. The user ID is at most 255 characters long.
   */
  public void setCreatedBy( @Nullable final String createdBy) {
    this.createdBy = createdBy;
  }

  /**
   * Set the createdByName of this {@link TaskInstanceD} instance and return the same instance.
   *
   * @param createdByName  As of now, this returns the same value as the CreatedBy property. This is subject to change.
   * @return The same instance of this {@link TaskInstanceD} class
   */
  @Nonnull public TaskInstanceD createdByName( @Nullable final String createdByName) {
    this.createdByName = createdByName;
    return this;
  }

  /**
   * As of now, this returns the same value as the CreatedBy property. This is subject to change.
   * @return createdByName  The createdByName of this {@link TaskInstanceD} instance.
   */
  @Nonnull
  public String getCreatedByName() {
    return createdByName;
  }

  /**
   * Set the createdByName of this {@link TaskInstanceD} instance.
   *
   * @param createdByName  As of now, this returns the same value as the CreatedBy property. This is subject to change.
   */
  public void setCreatedByName( @Nullable final String createdByName) {
    this.createdByName = createdByName;
  }

  /**
   * Set the processor of this {@link TaskInstanceD} instance and return the same instance.
   *
   * @param processor  The user who works on the task. The user ID is at most 255 characters long
   * @return The same instance of this {@link TaskInstanceD} class
   */
  @Nonnull public TaskInstanceD processor( @Nullable final String processor) {
    this.processor = processor;
    return this;
  }

  /**
   * The user who works on the task. The user ID is at most 255 characters long
   * @return processor  The processor of this {@link TaskInstanceD} instance.
   */
  @Nonnull
  public String getProcessor() {
    return processor;
  }

  /**
   * Set the processor of this {@link TaskInstanceD} instance.
   *
   * @param processor  The user who works on the task. The user ID is at most 255 characters long
   */
  public void setProcessor( @Nullable final String processor) {
    this.processor = processor;
  }

  /**
   * Set the completionDeadLine of this {@link TaskInstanceD} instance and return the same instance.
   *
   * @param completionDeadLine  The time by which the task must be completed.
   * @return The same instance of this {@link TaskInstanceD} class
   */
  @Nonnull public TaskInstanceD completionDeadLine( @Nullable final OffsetDateTime completionDeadLine) {
    this.completionDeadLine = completionDeadLine;
    return this;
  }

  /**
   * The time by which the task must be completed.
   * @return completionDeadLine  The completionDeadLine of this {@link TaskInstanceD} instance.
   */
  @Nonnull
  public OffsetDateTime getCompletionDeadLine() {
    return completionDeadLine;
  }

  /**
   * Set the completionDeadLine of this {@link TaskInstanceD} instance.
   *
   * @param completionDeadLine  The time by which the task must be completed.
   */
  public void setCompletionDeadLine( @Nullable final OffsetDateTime completionDeadLine) {
    this.completionDeadLine = completionDeadLine;
  }

  /**
   * Set the substitutedUserName of this {@link TaskInstanceD} instance and return the same instance.
   *
   * @param substitutedUserName  The name of the user who is substituted. This is currently not implemented in SAP Workflow service and will always return null. This is subject to change.
   * @return The same instance of this {@link TaskInstanceD} class
   */
  @Nonnull public TaskInstanceD substitutedUserName( @Nullable final String substitutedUserName) {
    this.substitutedUserName = substitutedUserName;
    return this;
  }

  /**
   * The name of the user who is substituted. This is currently not implemented in SAP Workflow service and will always return null. This is subject to change.
   * @return substitutedUserName  The substitutedUserName of this {@link TaskInstanceD} instance.
   */
  @Nonnull
  public String getSubstitutedUserName() {
    return substitutedUserName;
  }

  /**
   * Set the substitutedUserName of this {@link TaskInstanceD} instance.
   *
   * @param substitutedUserName  The name of the user who is substituted. This is currently not implemented in SAP Workflow service and will always return null. This is subject to change.
   */
  public void setSubstitutedUserName( @Nullable final String substitutedUserName) {
    this.substitutedUserName = substitutedUserName;
  }

  /**
   * Set the priority of this {@link TaskInstanceD} instance and return the same instance.
   *
   * @param priority  The priority of the task.
   * @return The same instance of this {@link TaskInstanceD} class
   */
  @Nonnull public TaskInstanceD priority( @Nullable final PriorityEnum priority) {
    this.priority = priority;
    return this;
  }

  /**
   * The priority of the task.
   * @return priority  The priority of this {@link TaskInstanceD} instance.
   */
  @Nonnull
  public PriorityEnum getPriority() {
    return priority;
  }

  /**
   * Set the priority of this {@link TaskInstanceD} instance.
   *
   * @param priority  The priority of the task.
   */
  public void setPriority( @Nullable final PriorityEnum priority) {
    this.priority = priority;
  }

  /**
   * Set the priorityNumber of this {@link TaskInstanceD} instance and return the same instance.
   *
   * @param priorityNumber  The numerical representation of the priority of the task.
   * @return The same instance of this {@link TaskInstanceD} class
   */
  @Nonnull public TaskInstanceD priorityNumber( @Nullable final Integer priorityNumber) {
    this.priorityNumber = priorityNumber;
    return this;
  }

  /**
   * The numerical representation of the priority of the task.
   * @return priorityNumber  The priorityNumber of this {@link TaskInstanceD} instance.
   */
  @Nonnull
  public Integer getPriorityNumber() {
    return priorityNumber;
  }

  /**
   * Set the priorityNumber of this {@link TaskInstanceD} instance.
   *
   * @param priorityNumber  The numerical representation of the priority of the task.
   */
  public void setPriorityNumber( @Nullable final Integer priorityNumber) {
    this.priorityNumber = priorityNumber;
  }

  /**
   * Set the taskSupports of this {@link TaskInstanceD} instance and return the same instance.
   *
   * @param taskSupports  The taskSupports of this {@link TaskInstanceD}
   * @return The same instance of this {@link TaskInstanceD} class
   */
  @Nonnull public TaskInstanceD taskSupports( @Nullable final TaskInstanceDTaskSupports taskSupports) {
    this.taskSupports = taskSupports;
    return this;
  }

  /**
   * Get taskSupports
   * @return taskSupports  The taskSupports of this {@link TaskInstanceD} instance.
   */
  @Nonnull
  public TaskInstanceDTaskSupports getTaskSupports() {
    return taskSupports;
  }

  /**
   * Set the taskSupports of this {@link TaskInstanceD} instance.
   *
   * @param taskSupports  The taskSupports of this {@link TaskInstanceD}
   */
  public void setTaskSupports( @Nullable final TaskInstanceDTaskSupports taskSupports) {
    this.taskSupports = taskSupports;
  }

  /**
   * Set the guILink of this {@link TaskInstanceD} instance and return the same instance.
   *
   * @param guILink  The URI of the task execution UI.
   * @return The same instance of this {@link TaskInstanceD} class
   */
  @Nonnull public TaskInstanceD guILink( @Nullable final String guILink) {
    this.guILink = guILink;
    return this;
  }

  /**
   * The URI of the task execution UI.
   * @return guILink  The guILink of this {@link TaskInstanceD} instance.
   */
  @Nonnull
  public String getGuILink() {
    return guILink;
  }

  /**
   * Set the guILink of this {@link TaskInstanceD} instance.
   *
   * @param guILink  The URI of the task execution UI.
   */
  public void setGuILink( @Nullable final String guILink) {
    this.guILink = guILink;
  }

  /**
   * Set the description of this {@link TaskInstanceD} instance and return the same instance.
   *
   * @param description  The description of this {@link TaskInstanceD}
   * @return The same instance of this {@link TaskInstanceD} class
   */
  @Nonnull public TaskInstanceD description( @Nullable final TaskInstanceDDescription description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description  The description of this {@link TaskInstanceD} instance.
   */
  @Nonnull
  public TaskInstanceDDescription getDescription() {
    return description;
  }

  /**
   * Set the description of this {@link TaskInstanceD} instance.
   *
   * @param description  The description of this {@link TaskInstanceD}
   */
  public void setDescription( @Nullable final TaskInstanceDDescription description) {
    this.description = description;
  }

  /**
   * Set the taskDefinitionData of this {@link TaskInstanceD} instance and return the same instance.
   *
   * @param taskDefinitionData  The taskDefinitionData of this {@link TaskInstanceD}
   * @return The same instance of this {@link TaskInstanceD} class
   */
  @Nonnull public TaskInstanceD taskDefinitionData( @Nullable final TaskInstanceDDescription taskDefinitionData) {
    this.taskDefinitionData = taskDefinitionData;
    return this;
  }

  /**
   * Get taskDefinitionData
   * @return taskDefinitionData  The taskDefinitionData of this {@link TaskInstanceD} instance.
   */
  @Nonnull
  public TaskInstanceDDescription getTaskDefinitionData() {
    return taskDefinitionData;
  }

  /**
   * Set the taskDefinitionData of this {@link TaskInstanceD} instance.
   *
   * @param taskDefinitionData  The taskDefinitionData of this {@link TaskInstanceD}
   */
  public void setTaskDefinitionData( @Nullable final TaskInstanceDDescription taskDefinitionData) {
    this.taskDefinitionData = taskDefinitionData;
  }

  /**
   * Set the customAttributeData of this {@link TaskInstanceD} instance and return the same instance.
   *
   * @param customAttributeData  The customAttributeData of this {@link TaskInstanceD}
   * @return The same instance of this {@link TaskInstanceD} class
   */
  @Nonnull public TaskInstanceD customAttributeData( @Nullable final TaskInstanceDDescription customAttributeData) {
    this.customAttributeData = customAttributeData;
    return this;
  }

  /**
   * Get customAttributeData
   * @return customAttributeData  The customAttributeData of this {@link TaskInstanceD} instance.
   */
  @Nonnull
  public TaskInstanceDDescription getCustomAttributeData() {
    return customAttributeData;
  }

  /**
   * Set the customAttributeData of this {@link TaskInstanceD} instance.
   *
   * @param customAttributeData  The customAttributeData of this {@link TaskInstanceD}
   */
  public void setCustomAttributeData( @Nullable final TaskInstanceDDescription customAttributeData) {
    this.customAttributeData = customAttributeData;
  }

  /**
   * Set the workflowLogs of this {@link TaskInstanceD} instance and return the same instance.
   *
   * @param workflowLogs  The workflowLogs of this {@link TaskInstanceD}
   * @return The same instance of this {@link TaskInstanceD} class
   */
  @Nonnull public TaskInstanceD workflowLogs( @Nullable final TaskInstanceDDescription workflowLogs) {
    this.workflowLogs = workflowLogs;
    return this;
  }

  /**
   * Get workflowLogs
   * @return workflowLogs  The workflowLogs of this {@link TaskInstanceD} instance.
   */
  @Nonnull
  public TaskInstanceDDescription getWorkflowLogs() {
    return workflowLogs;
  }

  /**
   * Set the workflowLogs of this {@link TaskInstanceD} instance.
   *
   * @param workflowLogs  The workflowLogs of this {@link TaskInstanceD}
   */
  public void setWorkflowLogs( @Nullable final TaskInstanceDDescription workflowLogs) {
    this.workflowLogs = workflowLogs;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link TaskInstanceD}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link TaskInstanceD} instance.
   * @deprecated Use {@link #toMap()} instead.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField( @Nonnull final String name ) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("TaskInstanceD has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link TaskInstanceD} instance including unrecognized properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap()
  {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if( metadata != null ) declaredFields.put("metadata", metadata);
    if( instanceID != null ) declaredFields.put("instanceID", instanceID);
    if( saPOrigin != null ) declaredFields.put("saPOrigin", saPOrigin);
    if( taskDefinitionID != null ) declaredFields.put("taskDefinitionID", taskDefinitionID);
    if( taskDefinitionName != null ) declaredFields.put("taskDefinitionName", taskDefinitionName);
    if( status != null ) declaredFields.put("status", status);
    if( taskTitle != null ) declaredFields.put("taskTitle", taskTitle);
    if( hasComments != null ) declaredFields.put("hasComments", hasComments);
    if( hasAttachments != null ) declaredFields.put("hasAttachments", hasAttachments);
    if( hasPotentialOwners != null ) declaredFields.put("hasPotentialOwners", hasPotentialOwners);
    if( supportsClaim != null ) declaredFields.put("supportsClaim", supportsClaim);
    if( supportsRelease != null ) declaredFields.put("supportsRelease", supportsRelease);
    if( supportsForward != null ) declaredFields.put("supportsForward", supportsForward);
    if( supportsComments != null ) declaredFields.put("supportsComments", supportsComments);
    if( supportsAttachments != null ) declaredFields.put("supportsAttachments", supportsAttachments);
    if( createdOn != null ) declaredFields.put("createdOn", createdOn);
    if( createdBy != null ) declaredFields.put("createdBy", createdBy);
    if( createdByName != null ) declaredFields.put("createdByName", createdByName);
    if( processor != null ) declaredFields.put("processor", processor);
    if( completionDeadLine != null ) declaredFields.put("completionDeadLine", completionDeadLine);
    if( substitutedUserName != null ) declaredFields.put("substitutedUserName", substitutedUserName);
    if( priority != null ) declaredFields.put("priority", priority);
    if( priorityNumber != null ) declaredFields.put("priorityNumber", priorityNumber);
    if( taskSupports != null ) declaredFields.put("taskSupports", taskSupports);
    if( guILink != null ) declaredFields.put("guILink", guILink);
    if( description != null ) declaredFields.put("description", description);
    if( taskDefinitionData != null ) declaredFields.put("taskDefinitionData", taskDefinitionData);
    if( customAttributeData != null ) declaredFields.put("customAttributeData", customAttributeData);
    if( workflowLogs != null ) declaredFields.put("workflowLogs", workflowLogs);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link TaskInstanceD} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final TaskInstanceD taskInstanceD = (TaskInstanceD) o;
    return Objects.equals(this.cloudSdkCustomFields, taskInstanceD.cloudSdkCustomFields) &&
        Objects.equals(this.metadata, taskInstanceD.metadata) &&
        Objects.equals(this.instanceID, taskInstanceD.instanceID) &&
        Objects.equals(this.saPOrigin, taskInstanceD.saPOrigin) &&
        Objects.equals(this.taskDefinitionID, taskInstanceD.taskDefinitionID) &&
        Objects.equals(this.taskDefinitionName, taskInstanceD.taskDefinitionName) &&
        Objects.equals(this.status, taskInstanceD.status) &&
        Objects.equals(this.taskTitle, taskInstanceD.taskTitle) &&
        Objects.equals(this.hasComments, taskInstanceD.hasComments) &&
        Objects.equals(this.hasAttachments, taskInstanceD.hasAttachments) &&
        Objects.equals(this.hasPotentialOwners, taskInstanceD.hasPotentialOwners) &&
        Objects.equals(this.supportsClaim, taskInstanceD.supportsClaim) &&
        Objects.equals(this.supportsRelease, taskInstanceD.supportsRelease) &&
        Objects.equals(this.supportsForward, taskInstanceD.supportsForward) &&
        Objects.equals(this.supportsComments, taskInstanceD.supportsComments) &&
        Objects.equals(this.supportsAttachments, taskInstanceD.supportsAttachments) &&
        Objects.equals(this.createdOn, taskInstanceD.createdOn) &&
        Objects.equals(this.createdBy, taskInstanceD.createdBy) &&
        Objects.equals(this.createdByName, taskInstanceD.createdByName) &&
        Objects.equals(this.processor, taskInstanceD.processor) &&
        Objects.equals(this.completionDeadLine, taskInstanceD.completionDeadLine) &&
        Objects.equals(this.substitutedUserName, taskInstanceD.substitutedUserName) &&
        Objects.equals(this.priority, taskInstanceD.priority) &&
        Objects.equals(this.priorityNumber, taskInstanceD.priorityNumber) &&
        Objects.equals(this.taskSupports, taskInstanceD.taskSupports) &&
        Objects.equals(this.guILink, taskInstanceD.guILink) &&
        Objects.equals(this.description, taskInstanceD.description) &&
        Objects.equals(this.taskDefinitionData, taskInstanceD.taskDefinitionData) &&
        Objects.equals(this.customAttributeData, taskInstanceD.customAttributeData) &&
        Objects.equals(this.workflowLogs, taskInstanceD.workflowLogs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(metadata, instanceID, saPOrigin, taskDefinitionID, taskDefinitionName, status, taskTitle, hasComments, hasAttachments, hasPotentialOwners, supportsClaim, supportsRelease, supportsForward, supportsComments, supportsAttachments, createdOn, createdBy, createdByName, processor, completionDeadLine, substitutedUserName, priority, priorityNumber, taskSupports, guILink, description, taskDefinitionData, customAttributeData, workflowLogs, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class TaskInstanceD {\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    instanceID: ").append(toIndentedString(instanceID)).append("\n");
    sb.append("    saPOrigin: ").append(toIndentedString(saPOrigin)).append("\n");
    sb.append("    taskDefinitionID: ").append(toIndentedString(taskDefinitionID)).append("\n");
    sb.append("    taskDefinitionName: ").append(toIndentedString(taskDefinitionName)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    taskTitle: ").append(toIndentedString(taskTitle)).append("\n");
    sb.append("    hasComments: ").append(toIndentedString(hasComments)).append("\n");
    sb.append("    hasAttachments: ").append(toIndentedString(hasAttachments)).append("\n");
    sb.append("    hasPotentialOwners: ").append(toIndentedString(hasPotentialOwners)).append("\n");
    sb.append("    supportsClaim: ").append(toIndentedString(supportsClaim)).append("\n");
    sb.append("    supportsRelease: ").append(toIndentedString(supportsRelease)).append("\n");
    sb.append("    supportsForward: ").append(toIndentedString(supportsForward)).append("\n");
    sb.append("    supportsComments: ").append(toIndentedString(supportsComments)).append("\n");
    sb.append("    supportsAttachments: ").append(toIndentedString(supportsAttachments)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdByName: ").append(toIndentedString(createdByName)).append("\n");
    sb.append("    processor: ").append(toIndentedString(processor)).append("\n");
    sb.append("    completionDeadLine: ").append(toIndentedString(completionDeadLine)).append("\n");
    sb.append("    substitutedUserName: ").append(toIndentedString(substitutedUserName)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    priorityNumber: ").append(toIndentedString(priorityNumber)).append("\n");
    sb.append("    taskSupports: ").append(toIndentedString(taskSupports)).append("\n");
    sb.append("    guILink: ").append(toIndentedString(guILink)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    taskDefinitionData: ").append(toIndentedString(taskDefinitionData)).append("\n");
    sb.append("    customAttributeData: ").append(toIndentedString(customAttributeData)).append("\n");
    sb.append("    workflowLogs: ").append(toIndentedString(workflowLogs)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

