

/*
 * Inbox
 * This API provides the functionality for building \"own inbox\" capabilities on top of SAP Build Process Automation. It is based on the task consumption model (TCM) as documented in SAP Note [2304317](https://launchpad.support.sap.com/#/notes/2304317/E).  Only users who have the ProcessAutomationParticipant role assigned are able to use the Inbox API.  SAP Build Process Automation currently supports only a subset of the Task Consumption Model capabilities. Only the functionality included in this document is available.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.openapi.sbpaworkflow.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sap.openapi.sbpaworkflow.model.TaskCustomAttributeDataMetadata;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * TaskCustomAttributeDatasDResultsInner
 */
// CHECKSTYLE:OFF
public class TaskCustomAttributeDatasDResultsInner 
// CHECKSTYLE:ON
{
  @JsonProperty("__metadata")
  private TaskCustomAttributeDataMetadata metadata;

  @JsonProperty("SAP__Origin")
  private String saPOrigin = "NA";

  @JsonProperty("InstanceID")
  private String instanceID;

  @JsonProperty("Name")
  private String name;

  @JsonProperty("Value")
  private String value;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /**
   * Set the metadata of this {@link TaskCustomAttributeDatasDResultsInner} instance and return the same instance.
   *
   * @param metadata  The metadata of this {@link TaskCustomAttributeDatasDResultsInner}
   * @return The same instance of this {@link TaskCustomAttributeDatasDResultsInner} class
   */
  @Nonnull public TaskCustomAttributeDatasDResultsInner metadata( @Nullable final TaskCustomAttributeDataMetadata metadata) {
    this.metadata = metadata;
    return this;
  }

  /**
   * Get metadata
   * @return metadata  The metadata of this {@link TaskCustomAttributeDatasDResultsInner} instance.
   */
  @Nonnull
  public TaskCustomAttributeDataMetadata getMetadata() {
    return metadata;
  }

  /**
   * Set the metadata of this {@link TaskCustomAttributeDatasDResultsInner} instance.
   *
   * @param metadata  The metadata of this {@link TaskCustomAttributeDatasDResultsInner}
   */
  public void setMetadata( @Nullable final TaskCustomAttributeDataMetadata metadata) {
    this.metadata = metadata;
  }

  /**
   * Set the saPOrigin of this {@link TaskCustomAttributeDatasDResultsInner} instance and return the same instance.
   *
   * @param saPOrigin  The SID discriminator. Set to &#39;NA&#39; for all entities. For more information, see the Task Consumption Model documentation in SAP Note [2304317](https://launchpad.support.sap.com/#/notes/2304317/E).
   * @return The same instance of this {@link TaskCustomAttributeDatasDResultsInner} class
   */
  @Nonnull public TaskCustomAttributeDatasDResultsInner saPOrigin( @Nullable final String saPOrigin) {
    this.saPOrigin = saPOrigin;
    return this;
  }

  /**
   * The SID discriminator. Set to &#39;NA&#39; for all entities. For more information, see the Task Consumption Model documentation in SAP Note [2304317](https://launchpad.support.sap.com/#/notes/2304317/E).
   * @return saPOrigin  The saPOrigin of this {@link TaskCustomAttributeDatasDResultsInner} instance.
   */
  @Nonnull
  public String getSaPOrigin() {
    return saPOrigin;
  }

  /**
   * Set the saPOrigin of this {@link TaskCustomAttributeDatasDResultsInner} instance.
   *
   * @param saPOrigin  The SID discriminator. Set to &#39;NA&#39; for all entities. For more information, see the Task Consumption Model documentation in SAP Note [2304317](https://launchpad.support.sap.com/#/notes/2304317/E).
   */
  public void setSaPOrigin( @Nullable final String saPOrigin) {
    this.saPOrigin = saPOrigin;
  }

  /**
   * Set the instanceID of this {@link TaskCustomAttributeDatasDResultsInner} instance and return the same instance.
   *
   * @param instanceID  The ID of the task.
   * @return The same instance of this {@link TaskCustomAttributeDatasDResultsInner} class
   */
  @Nonnull public TaskCustomAttributeDatasDResultsInner instanceID( @Nullable final String instanceID) {
    this.instanceID = instanceID;
    return this;
  }

  /**
   * The ID of the task.
   * @return instanceID  The instanceID of this {@link TaskCustomAttributeDatasDResultsInner} instance.
   */
  @Nonnull
  public String getInstanceID() {
    return instanceID;
  }

  /**
   * Set the instanceID of this {@link TaskCustomAttributeDatasDResultsInner} instance.
   *
   * @param instanceID  The ID of the task.
   */
  public void setInstanceID( @Nullable final String instanceID) {
    this.instanceID = instanceID;
  }

  /**
   * Set the name of this {@link TaskCustomAttributeDatasDResultsInner} instance and return the same instance.
   *
   * @param name  The name of the custom attribute
   * @return The same instance of this {@link TaskCustomAttributeDatasDResultsInner} class
   */
  @Nonnull public TaskCustomAttributeDatasDResultsInner name( @Nullable final String name) {
    this.name = name;
    return this;
  }

  /**
   * The name of the custom attribute
   * @return name  The name of this {@link TaskCustomAttributeDatasDResultsInner} instance.
   */
  @Nonnull
  public String getName() {
    return name;
  }

  /**
   * Set the name of this {@link TaskCustomAttributeDatasDResultsInner} instance.
   *
   * @param name  The name of the custom attribute
   */
  public void setName( @Nullable final String name) {
    this.name = name;
  }

  /**
   * Set the value of this {@link TaskCustomAttributeDatasDResultsInner} instance and return the same instance.
   *
   * @param value  The value of the custom attribute for the given task instance
   * @return The same instance of this {@link TaskCustomAttributeDatasDResultsInner} class
   */
  @Nonnull public TaskCustomAttributeDatasDResultsInner value( @Nullable final String value) {
    this.value = value;
    return this;
  }

  /**
   * The value of the custom attribute for the given task instance
   * @return value  The value of this {@link TaskCustomAttributeDatasDResultsInner} instance.
   */
  @Nonnull
  public String getValue() {
    return value;
  }

  /**
   * Set the value of this {@link TaskCustomAttributeDatasDResultsInner} instance.
   *
   * @param value  The value of the custom attribute for the given task instance
   */
  public void setValue( @Nullable final String value) {
    this.value = value;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link TaskCustomAttributeDatasDResultsInner}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link TaskCustomAttributeDatasDResultsInner} instance.
   * @deprecated Use {@link #toMap()} instead.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField( @Nonnull final String name ) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("TaskCustomAttributeDatasDResultsInner has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link TaskCustomAttributeDatasDResultsInner} instance including unrecognized properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap()
  {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if( metadata != null ) declaredFields.put("metadata", metadata);
    if( saPOrigin != null ) declaredFields.put("saPOrigin", saPOrigin);
    if( instanceID != null ) declaredFields.put("instanceID", instanceID);
    if( name != null ) declaredFields.put("name", name);
    if( value != null ) declaredFields.put("value", value);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link TaskCustomAttributeDatasDResultsInner} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final TaskCustomAttributeDatasDResultsInner taskCustomAttributeDatasDResultsInner = (TaskCustomAttributeDatasDResultsInner) o;
    return Objects.equals(this.cloudSdkCustomFields, taskCustomAttributeDatasDResultsInner.cloudSdkCustomFields) &&
        Objects.equals(this.metadata, taskCustomAttributeDatasDResultsInner.metadata) &&
        Objects.equals(this.saPOrigin, taskCustomAttributeDatasDResultsInner.saPOrigin) &&
        Objects.equals(this.instanceID, taskCustomAttributeDatasDResultsInner.instanceID) &&
        Objects.equals(this.name, taskCustomAttributeDatasDResultsInner.name) &&
        Objects.equals(this.value, taskCustomAttributeDatasDResultsInner.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(metadata, saPOrigin, instanceID, name, value, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class TaskCustomAttributeDatasDResultsInner {\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    saPOrigin: ").append(toIndentedString(saPOrigin)).append("\n");
    sb.append("    instanceID: ").append(toIndentedString(instanceID)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

