

/*
 * Inbox
 * This API provides the functionality for building \"own inbox\" capabilities on top of SAP Build Process Automation. It is based on the task consumption model (TCM) as documented in SAP Note [2304317](https://launchpad.support.sap.com/#/notes/2304317/E).  Only users who have the ProcessAutomationParticipant role assigned are able to use the Inbox API.  SAP Build Process Automation currently supports only a subset of the Task Consumption Model capabilities. Only the functionality included in this document is available.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.openapi.sbpaworkflow.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sap.openapi.sbpaworkflow.model.TaskCustomAttributeDefinitionMetadata;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * TaskCustomAttributeDefinitionsDResultsInner
 */
// CHECKSTYLE:OFF
public class TaskCustomAttributeDefinitionsDResultsInner 
// CHECKSTYLE:ON
{
  @JsonProperty("__metadata")
  private TaskCustomAttributeDefinitionMetadata metadata;

  @JsonProperty("SAP__Origin")
  private String saPOrigin = "NA";

  @JsonProperty("TaskDefinitionID")
  private String taskDefinitionID;

  @JsonProperty("Name")
  private String name;

  @JsonProperty("Type")
  private String type;

  @JsonProperty("Label")
  private String label;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /**
   * Set the metadata of this {@link TaskCustomAttributeDefinitionsDResultsInner} instance and return the same instance.
   *
   * @param metadata  The metadata of this {@link TaskCustomAttributeDefinitionsDResultsInner}
   * @return The same instance of this {@link TaskCustomAttributeDefinitionsDResultsInner} class
   */
  @Nonnull public TaskCustomAttributeDefinitionsDResultsInner metadata( @Nullable final TaskCustomAttributeDefinitionMetadata metadata) {
    this.metadata = metadata;
    return this;
  }

  /**
   * Get metadata
   * @return metadata  The metadata of this {@link TaskCustomAttributeDefinitionsDResultsInner} instance.
   */
  @Nonnull
  public TaskCustomAttributeDefinitionMetadata getMetadata() {
    return metadata;
  }

  /**
   * Set the metadata of this {@link TaskCustomAttributeDefinitionsDResultsInner} instance.
   *
   * @param metadata  The metadata of this {@link TaskCustomAttributeDefinitionsDResultsInner}
   */
  public void setMetadata( @Nullable final TaskCustomAttributeDefinitionMetadata metadata) {
    this.metadata = metadata;
  }

  /**
   * Set the saPOrigin of this {@link TaskCustomAttributeDefinitionsDResultsInner} instance and return the same instance.
   *
   * @param saPOrigin  The SID discriminator. Set to &#39;NA&#39; for all entities. For more information, see the Task Consumption Model documentation in SAP Note [2304317](https://launchpad.support.sap.com/#/notes/2304317/E).
   * @return The same instance of this {@link TaskCustomAttributeDefinitionsDResultsInner} class
   */
  @Nonnull public TaskCustomAttributeDefinitionsDResultsInner saPOrigin( @Nullable final String saPOrigin) {
    this.saPOrigin = saPOrigin;
    return this;
  }

  /**
   * The SID discriminator. Set to &#39;NA&#39; for all entities. For more information, see the Task Consumption Model documentation in SAP Note [2304317](https://launchpad.support.sap.com/#/notes/2304317/E).
   * @return saPOrigin  The saPOrigin of this {@link TaskCustomAttributeDefinitionsDResultsInner} instance.
   */
  @Nonnull
  public String getSaPOrigin() {
    return saPOrigin;
  }

  /**
   * Set the saPOrigin of this {@link TaskCustomAttributeDefinitionsDResultsInner} instance.
   *
   * @param saPOrigin  The SID discriminator. Set to &#39;NA&#39; for all entities. For more information, see the Task Consumption Model documentation in SAP Note [2304317](https://launchpad.support.sap.com/#/notes/2304317/E).
   */
  public void setSaPOrigin( @Nullable final String saPOrigin) {
    this.saPOrigin = saPOrigin;
  }

  /**
   * Set the taskDefinitionID of this {@link TaskCustomAttributeDefinitionsDResultsInner} instance and return the same instance.
   *
   * @param taskDefinitionID  The ID of the task definition this task belongs to. Is constructed out of the task definition name and the workflow definition ID in the form {task definition name}@{workflow definition ID} in lowercase.
   * @return The same instance of this {@link TaskCustomAttributeDefinitionsDResultsInner} class
   */
  @Nonnull public TaskCustomAttributeDefinitionsDResultsInner taskDefinitionID( @Nullable final String taskDefinitionID) {
    this.taskDefinitionID = taskDefinitionID;
    return this;
  }

  /**
   * The ID of the task definition this task belongs to. Is constructed out of the task definition name and the workflow definition ID in the form {task definition name}@{workflow definition ID} in lowercase.
   * @return taskDefinitionID  The taskDefinitionID of this {@link TaskCustomAttributeDefinitionsDResultsInner} instance.
   */
  @Nonnull
  public String getTaskDefinitionID() {
    return taskDefinitionID;
  }

  /**
   * Set the taskDefinitionID of this {@link TaskCustomAttributeDefinitionsDResultsInner} instance.
   *
   * @param taskDefinitionID  The ID of the task definition this task belongs to. Is constructed out of the task definition name and the workflow definition ID in the form {task definition name}@{workflow definition ID} in lowercase.
   */
  public void setTaskDefinitionID( @Nullable final String taskDefinitionID) {
    this.taskDefinitionID = taskDefinitionID;
  }

  /**
   * Set the name of this {@link TaskCustomAttributeDefinitionsDResultsInner} instance and return the same instance.
   *
   * @param name  The name of the custom attribute definition
   * @return The same instance of this {@link TaskCustomAttributeDefinitionsDResultsInner} class
   */
  @Nonnull public TaskCustomAttributeDefinitionsDResultsInner name( @Nullable final String name) {
    this.name = name;
    return this;
  }

  /**
   * The name of the custom attribute definition
   * @return name  The name of this {@link TaskCustomAttributeDefinitionsDResultsInner} instance.
   */
  @Nonnull
  public String getName() {
    return name;
  }

  /**
   * Set the name of this {@link TaskCustomAttributeDefinitionsDResultsInner} instance.
   *
   * @param name  The name of the custom attribute definition
   */
  public void setName( @Nullable final String name) {
    this.name = name;
  }

  /**
   * Set the type of this {@link TaskCustomAttributeDefinitionsDResultsInner} instance and return the same instance.
   *
   * @param type  The type of this {@link TaskCustomAttributeDefinitionsDResultsInner}
   * @return The same instance of this {@link TaskCustomAttributeDefinitionsDResultsInner} class
   */
  @Nonnull public TaskCustomAttributeDefinitionsDResultsInner type( @Nullable final String type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type  The type of this {@link TaskCustomAttributeDefinitionsDResultsInner} instance.
   */
  @Nonnull
  public String getType() {
    return type;
  }

  /**
   * Set the type of this {@link TaskCustomAttributeDefinitionsDResultsInner} instance.
   *
   * @param type  The type of this {@link TaskCustomAttributeDefinitionsDResultsInner}
   */
  public void setType( @Nullable final String type) {
    this.type = type;
  }

  /**
   * Set the label of this {@link TaskCustomAttributeDefinitionsDResultsInner} instance and return the same instance.
   *
   * @param label  The label of this {@link TaskCustomAttributeDefinitionsDResultsInner}
   * @return The same instance of this {@link TaskCustomAttributeDefinitionsDResultsInner} class
   */
  @Nonnull public TaskCustomAttributeDefinitionsDResultsInner label( @Nullable final String label) {
    this.label = label;
    return this;
  }

  /**
   * Get label
   * @return label  The label of this {@link TaskCustomAttributeDefinitionsDResultsInner} instance.
   */
  @Nonnull
  public String getLabel() {
    return label;
  }

  /**
   * Set the label of this {@link TaskCustomAttributeDefinitionsDResultsInner} instance.
   *
   * @param label  The label of this {@link TaskCustomAttributeDefinitionsDResultsInner}
   */
  public void setLabel( @Nullable final String label) {
    this.label = label;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link TaskCustomAttributeDefinitionsDResultsInner}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link TaskCustomAttributeDefinitionsDResultsInner} instance.
   * @deprecated Use {@link #toMap()} instead.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField( @Nonnull final String name ) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("TaskCustomAttributeDefinitionsDResultsInner has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link TaskCustomAttributeDefinitionsDResultsInner} instance including unrecognized properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap()
  {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if( metadata != null ) declaredFields.put("metadata", metadata);
    if( saPOrigin != null ) declaredFields.put("saPOrigin", saPOrigin);
    if( taskDefinitionID != null ) declaredFields.put("taskDefinitionID", taskDefinitionID);
    if( name != null ) declaredFields.put("name", name);
    if( type != null ) declaredFields.put("type", type);
    if( label != null ) declaredFields.put("label", label);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link TaskCustomAttributeDefinitionsDResultsInner} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final TaskCustomAttributeDefinitionsDResultsInner taskCustomAttributeDefinitionsDResultsInner = (TaskCustomAttributeDefinitionsDResultsInner) o;
    return Objects.equals(this.cloudSdkCustomFields, taskCustomAttributeDefinitionsDResultsInner.cloudSdkCustomFields) &&
        Objects.equals(this.metadata, taskCustomAttributeDefinitionsDResultsInner.metadata) &&
        Objects.equals(this.saPOrigin, taskCustomAttributeDefinitionsDResultsInner.saPOrigin) &&
        Objects.equals(this.taskDefinitionID, taskCustomAttributeDefinitionsDResultsInner.taskDefinitionID) &&
        Objects.equals(this.name, taskCustomAttributeDefinitionsDResultsInner.name) &&
        Objects.equals(this.type, taskCustomAttributeDefinitionsDResultsInner.type) &&
        Objects.equals(this.label, taskCustomAttributeDefinitionsDResultsInner.label);
  }

  @Override
  public int hashCode() {
    return Objects.hash(metadata, saPOrigin, taskDefinitionID, name, type, label, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class TaskCustomAttributeDefinitionsDResultsInner {\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    saPOrigin: ").append(toIndentedString(saPOrigin)).append("\n");
    sb.append("    taskDefinitionID: ").append(toIndentedString(taskDefinitionID)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

