

/*
 * Inbox
 * This API provides the functionality for building \"own inbox\" capabilities on top of SAP Build Process Automation. It is based on the task consumption model (TCM) as documented in SAP Note [2304317](https://launchpad.support.sap.com/#/notes/2304317/E).  Only users who have the ProcessAutomationParticipant role assigned are able to use the Inbox API.  SAP Build Process Automation currently supports only a subset of the Task Consumption Model capabilities. Only the functionality included in this document is available.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.openapi.sbpaworkflow.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sap.openapi.sbpaworkflow.model.TaskInstanceDTaskSupportsMetadata;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * TaskSupports
 */
// CHECKSTYLE:OFF
public class TaskSupports 
// CHECKSTYLE:ON
{
  @JsonProperty("__metadata")
  private TaskInstanceDTaskSupportsMetadata metadata;

  @JsonProperty("Description")
  private Boolean description;

  @JsonProperty("UIExecutionLink")
  private Boolean uiExecutionLink;

  @JsonProperty("WorkflowLog")
  private Boolean workflowLog;

  @JsonProperty("Claim")
  private Boolean claim;

  @JsonProperty("Release")
  private Boolean release;

  @JsonProperty("Forward")
  private Boolean forward;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /**
   * Set the metadata of this {@link TaskSupports} instance and return the same instance.
   *
   * @param metadata  The metadata of this {@link TaskSupports}
   * @return The same instance of this {@link TaskSupports} class
   */
  @Nonnull public TaskSupports metadata( @Nullable final TaskInstanceDTaskSupportsMetadata metadata) {
    this.metadata = metadata;
    return this;
  }

  /**
   * Get metadata
   * @return metadata  The metadata of this {@link TaskSupports} instance.
   */
  @Nonnull
  public TaskInstanceDTaskSupportsMetadata getMetadata() {
    return metadata;
  }

  /**
   * Set the metadata of this {@link TaskSupports} instance.
   *
   * @param metadata  The metadata of this {@link TaskSupports}
   */
  public void setMetadata( @Nullable final TaskInstanceDTaskSupportsMetadata metadata) {
    this.metadata = metadata;
  }

  /**
   * Set the description of this {@link TaskSupports} instance and return the same instance.
   *
   * @param description  Indicates whether a description is supported on this task.
   * @return The same instance of this {@link TaskSupports} class
   */
  @Nonnull public TaskSupports description( @Nullable final Boolean description) {
    this.description = description;
    return this;
  }

  /**
   * Indicates whether a description is supported on this task.
   * @return description  The description of this {@link TaskSupports} instance.
   */
  @Nonnull
  public Boolean isDescription() {
    return description;
  }

  /**
   * Set the description of this {@link TaskSupports} instance.
   *
   * @param description  Indicates whether a description is supported on this task.
   */
  public void setDescription( @Nullable final Boolean description) {
    this.description = description;
  }

  /**
   * Set the uiExecutionLink of this {@link TaskSupports} instance and return the same instance.
   *
   * @param uiExecutionLink  Indicates whether an UI execution link is supported on this task.
   * @return The same instance of this {@link TaskSupports} class
   */
  @Nonnull public TaskSupports uiExecutionLink( @Nullable final Boolean uiExecutionLink) {
    this.uiExecutionLink = uiExecutionLink;
    return this;
  }

  /**
   * Indicates whether an UI execution link is supported on this task.
   * @return uiExecutionLink  The uiExecutionLink of this {@link TaskSupports} instance.
   */
  @Nonnull
  public Boolean isUiExecutionLink() {
    return uiExecutionLink;
  }

  /**
   * Set the uiExecutionLink of this {@link TaskSupports} instance.
   *
   * @param uiExecutionLink  Indicates whether an UI execution link is supported on this task.
   */
  public void setUiExecutionLink( @Nullable final Boolean uiExecutionLink) {
    this.uiExecutionLink = uiExecutionLink;
  }

  /**
   * Set the workflowLog of this {@link TaskSupports} instance and return the same instance.
   *
   * @param workflowLog  Indicates whether a workflow log is supported on this task.
   * @return The same instance of this {@link TaskSupports} class
   */
  @Nonnull public TaskSupports workflowLog( @Nullable final Boolean workflowLog) {
    this.workflowLog = workflowLog;
    return this;
  }

  /**
   * Indicates whether a workflow log is supported on this task.
   * @return workflowLog  The workflowLog of this {@link TaskSupports} instance.
   */
  @Nonnull
  public Boolean isWorkflowLog() {
    return workflowLog;
  }

  /**
   * Set the workflowLog of this {@link TaskSupports} instance.
   *
   * @param workflowLog  Indicates whether a workflow log is supported on this task.
   */
  public void setWorkflowLog( @Nullable final Boolean workflowLog) {
    this.workflowLog = workflowLog;
  }

  /**
   * Set the claim of this {@link TaskSupports} instance and return the same instance.
   *
   * @param claim  Indicates whether a claim operation on this task is possible. This depends on the life cycle of the task. See [Status Changes for Task Instances ](https://help.sap.com/viewer/e157c391253b4ecd93647bf232d18a83/Cloud/en-US/539ab87c451e4c0aa8321d2f226c44d0.html).
   * @return The same instance of this {@link TaskSupports} class
   */
  @Nonnull public TaskSupports claim( @Nullable final Boolean claim) {
    this.claim = claim;
    return this;
  }

  /**
   * Indicates whether a claim operation on this task is possible. This depends on the life cycle of the task. See [Status Changes for Task Instances ](https://help.sap.com/viewer/e157c391253b4ecd93647bf232d18a83/Cloud/en-US/539ab87c451e4c0aa8321d2f226c44d0.html).
   * @return claim  The claim of this {@link TaskSupports} instance.
   */
  @Nonnull
  public Boolean isClaim() {
    return claim;
  }

  /**
   * Set the claim of this {@link TaskSupports} instance.
   *
   * @param claim  Indicates whether a claim operation on this task is possible. This depends on the life cycle of the task. See [Status Changes for Task Instances ](https://help.sap.com/viewer/e157c391253b4ecd93647bf232d18a83/Cloud/en-US/539ab87c451e4c0aa8321d2f226c44d0.html).
   */
  public void setClaim( @Nullable final Boolean claim) {
    this.claim = claim;
  }

  /**
   * Set the release of this {@link TaskSupports} instance and return the same instance.
   *
   * @param release  Indicates whether a release operation on this task is possible. This depends on the life cycle of the task. See [Status Changes for Task Instances ](https://help.sap.com/viewer/e157c391253b4ecd93647bf232d18a83/Cloud/en-US/539ab87c451e4c0aa8321d2f226c44d0.html).
   * @return The same instance of this {@link TaskSupports} class
   */
  @Nonnull public TaskSupports release( @Nullable final Boolean release) {
    this.release = release;
    return this;
  }

  /**
   * Indicates whether a release operation on this task is possible. This depends on the life cycle of the task. See [Status Changes for Task Instances ](https://help.sap.com/viewer/e157c391253b4ecd93647bf232d18a83/Cloud/en-US/539ab87c451e4c0aa8321d2f226c44d0.html).
   * @return release  The release of this {@link TaskSupports} instance.
   */
  @Nonnull
  public Boolean isRelease() {
    return release;
  }

  /**
   * Set the release of this {@link TaskSupports} instance.
   *
   * @param release  Indicates whether a release operation on this task is possible. This depends on the life cycle of the task. See [Status Changes for Task Instances ](https://help.sap.com/viewer/e157c391253b4ecd93647bf232d18a83/Cloud/en-US/539ab87c451e4c0aa8321d2f226c44d0.html).
   */
  public void setRelease( @Nullable final Boolean release) {
    this.release = release;
  }

  /**
   * Set the forward of this {@link TaskSupports} instance and return the same instance.
   *
   * @param forward  Indicates whether a forward operation on this task is possible. This depends on the life cycle of the task. See [Status Changes for Task Instances ](https://help.sap.com/viewer/e157c391253b4ecd93647bf232d18a83/Cloud/en-US/539ab87c451e4c0aa8321d2f226c44d0.html).
   * @return The same instance of this {@link TaskSupports} class
   */
  @Nonnull public TaskSupports forward( @Nullable final Boolean forward) {
    this.forward = forward;
    return this;
  }

  /**
   * Indicates whether a forward operation on this task is possible. This depends on the life cycle of the task. See [Status Changes for Task Instances ](https://help.sap.com/viewer/e157c391253b4ecd93647bf232d18a83/Cloud/en-US/539ab87c451e4c0aa8321d2f226c44d0.html).
   * @return forward  The forward of this {@link TaskSupports} instance.
   */
  @Nonnull
  public Boolean isForward() {
    return forward;
  }

  /**
   * Set the forward of this {@link TaskSupports} instance.
   *
   * @param forward  Indicates whether a forward operation on this task is possible. This depends on the life cycle of the task. See [Status Changes for Task Instances ](https://help.sap.com/viewer/e157c391253b4ecd93647bf232d18a83/Cloud/en-US/539ab87c451e4c0aa8321d2f226c44d0.html).
   */
  public void setForward( @Nullable final Boolean forward) {
    this.forward = forward;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link TaskSupports}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link TaskSupports} instance.
   * @deprecated Use {@link #toMap()} instead.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField( @Nonnull final String name ) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("TaskSupports has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link TaskSupports} instance including unrecognized properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap()
  {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if( metadata != null ) declaredFields.put("metadata", metadata);
    if( description != null ) declaredFields.put("description", description);
    if( uiExecutionLink != null ) declaredFields.put("uiExecutionLink", uiExecutionLink);
    if( workflowLog != null ) declaredFields.put("workflowLog", workflowLog);
    if( claim != null ) declaredFields.put("claim", claim);
    if( release != null ) declaredFields.put("release", release);
    if( forward != null ) declaredFields.put("forward", forward);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link TaskSupports} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final TaskSupports taskSupports = (TaskSupports) o;
    return Objects.equals(this.cloudSdkCustomFields, taskSupports.cloudSdkCustomFields) &&
        Objects.equals(this.metadata, taskSupports.metadata) &&
        Objects.equals(this.description, taskSupports.description) &&
        Objects.equals(this.uiExecutionLink, taskSupports.uiExecutionLink) &&
        Objects.equals(this.workflowLog, taskSupports.workflowLog) &&
        Objects.equals(this.claim, taskSupports.claim) &&
        Objects.equals(this.release, taskSupports.release) &&
        Objects.equals(this.forward, taskSupports.forward);
  }

  @Override
  public int hashCode() {
    return Objects.hash(metadata, description, uiExecutionLink, workflowLog, claim, release, forward, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class TaskSupports {\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    uiExecutionLink: ").append(toIndentedString(uiExecutionLink)).append("\n");
    sb.append("    workflowLog: ").append(toIndentedString(workflowLog)).append("\n");
    sb.append("    claim: ").append(toIndentedString(claim)).append("\n");
    sb.append("    release: ").append(toIndentedString(release)).append("\n");
    sb.append("    forward: ").append(toIndentedString(forward)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

