

/*
 * Inbox
 * This API provides the functionality for building \"own inbox\" capabilities on top of SAP Build Process Automation. It is based on the task consumption model (TCM) as documented in SAP Note [2304317](https://launchpad.support.sap.com/#/notes/2304317/E).  Only users who have the ProcessAutomationParticipant role assigned are able to use the Inbox API.  SAP Build Process Automation currently supports only a subset of the Task Consumption Model capabilities. Only the functionality included in this document is available.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.openapi.sbpaworkflow.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sap.openapi.sbpaworkflow.model.TCMError400ErrorMessage;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * TCMError405Error
 */
// CHECKSTYLE:OFF
public class TCMError405Error 
// CHECKSTYLE:ON
{
  /**
   * The error category.
   */
  public enum CodeEnum {
    /**
    * The NULL option of this TCMError405Error
    */
    NULL("null");

    private String value;

    CodeEnum(String value) {
      this.value = value;
    }

    /**
    * Get the value of the enum
    * @return The enum value
    */
    @JsonValue
    @Nonnull public String getValue() {
      return value;
    }

    /**
    * Get the String value of the enum value.
    * @return The enum value as String
    */
    @Override
    @Nonnull public String toString() {
      return String.valueOf(value);
    }

    /**
    * Get the enum value from a String value
    * @param value The String value
    * @return The enum value of type TCMError405Error
    */
    @JsonCreator
    @Nonnull public static CodeEnum fromValue(@Nonnull final String value) {
      for (CodeEnum b : CodeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  @JsonProperty("code")
  private CodeEnum code;

  @JsonProperty("message")
  private TCMError400ErrorMessage message;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /**
   * Set the code of this {@link TCMError405Error} instance and return the same instance.
   *
   * @param code  The error category.
   * @return The same instance of this {@link TCMError405Error} class
   */
  @Nonnull public TCMError405Error code( @Nullable final CodeEnum code) {
    this.code = code;
    return this;
  }

  /**
   * The error category.
   * @return code  The code of this {@link TCMError405Error} instance.
   */
  @Nonnull
  public CodeEnum getCode() {
    return code;
  }

  /**
   * Set the code of this {@link TCMError405Error} instance.
   *
   * @param code  The error category.
   */
  public void setCode( @Nullable final CodeEnum code) {
    this.code = code;
  }

  /**
   * Set the message of this {@link TCMError405Error} instance and return the same instance.
   *
   * @param message  The message of this {@link TCMError405Error}
   * @return The same instance of this {@link TCMError405Error} class
   */
  @Nonnull public TCMError405Error message( @Nullable final TCMError400ErrorMessage message) {
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message  The message of this {@link TCMError405Error} instance.
   */
  @Nonnull
  public TCMError400ErrorMessage getMessage() {
    return message;
  }

  /**
   * Set the message of this {@link TCMError405Error} instance.
   *
   * @param message  The message of this {@link TCMError405Error}
   */
  public void setMessage( @Nullable final TCMError400ErrorMessage message) {
    this.message = message;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link TCMError405Error}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link TCMError405Error} instance.
   * @deprecated Use {@link #toMap()} instead.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField( @Nonnull final String name ) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("TCMError405Error has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link TCMError405Error} instance including unrecognized properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap()
  {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if( code != null ) declaredFields.put("code", code);
    if( message != null ) declaredFields.put("message", message);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link TCMError405Error} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final TCMError405Error tcMError405Error = (TCMError405Error) o;
    return Objects.equals(this.cloudSdkCustomFields, tcMError405Error.cloudSdkCustomFields) &&
        Objects.equals(this.code, tcMError405Error.code) &&
        Objects.equals(this.message, tcMError405Error.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, message, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class TCMError405Error {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

