

/*
 * Workflow
 * This API uses the workflow capability of SAP Build Process Automation. With the API, you can, for example, start new workflow instances and work with tasks.  Note: These APIs are designed for loosely coupled clients. This means:  - If SAP Build Process Automation adds fields to responses, the API version number does not increase. Your client must ignore new fields. - The order of fields in responses and of entries in arrays may change. This applies unless the API provides an explicit means to specify the desired order. 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.openapi.sbpaworkflow.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * UpdateTaskInstancesPayload
 */
// CHECKSTYLE:OFF
public class UpdateTaskInstancesPayload 
// CHECKSTYLE:ON
{
  @JsonProperty("id")
  private String id;

  @JsonProperty("subject")
  private String subject;

  @JsonProperty("description")
  private String description;

  @JsonProperty("recipientUsers")
  private String recipientUsers;

  @JsonProperty("recipientGroups")
  private String recipientGroups;

  @JsonProperty("processor")
  private String processor;

  @JsonProperty("dueDate")
  private OffsetDateTime dueDate;

  /**
   * Specify the new priority of the task instance.
   */
  public enum PriorityEnum {
    /**
    * The VERY_HIGH option of this UpdateTaskInstancesPayload
    */
    VERY_HIGH("VERY_HIGH"),
    
    /**
    * The HIGH option of this UpdateTaskInstancesPayload
    */
    HIGH("HIGH"),
    
    /**
    * The MEDIUM option of this UpdateTaskInstancesPayload
    */
    MEDIUM("MEDIUM"),
    
    /**
    * The LOW option of this UpdateTaskInstancesPayload
    */
    LOW("LOW");

    private String value;

    PriorityEnum(String value) {
      this.value = value;
    }

    /**
    * Get the value of the enum
    * @return The enum value
    */
    @JsonValue
    @Nonnull public String getValue() {
      return value;
    }

    /**
    * Get the String value of the enum value.
    * @return The enum value as String
    */
    @Override
    @Nonnull public String toString() {
      return String.valueOf(value);
    }

    /**
    * Get the enum value from a String value
    * @param value The String value
    * @return The enum value of type UpdateTaskInstancesPayload
    */
    @JsonCreator
    @Nonnull public static PriorityEnum fromValue(@Nonnull final String value) {
      for (PriorityEnum b : PriorityEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  @JsonProperty("priority")
  private PriorityEnum priority;

  @JsonProperty("confidenceLevel")
  private Double confidenceLevel;

  @JsonProperty("userInterfaceUri")
  private String userInterfaceUri;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /**
   * Set the id of this {@link UpdateTaskInstancesPayload} instance and return the same instance.
   *
   * @param id  The ID of the user task instance. The ID is at least 36 characters long.
   * @return The same instance of this {@link UpdateTaskInstancesPayload} class
   */
  @Nonnull public UpdateTaskInstancesPayload id( @Nonnull final String id) {
    this.id = id;
    return this;
  }

  /**
   * The ID of the user task instance. The ID is at least 36 characters long.
   * @return id  The id of this {@link UpdateTaskInstancesPayload} instance.
   */
  @Nonnull
  public String getId() {
    return id;
  }

  /**
   * Set the id of this {@link UpdateTaskInstancesPayload} instance.
   *
   * @param id  The ID of the user task instance. The ID is at least 36 characters long.
   */
  public void setId( @Nonnull final String id) {
    this.id = id;
  }

  /**
   * Set the subject of this {@link UpdateTaskInstancesPayload} instance and return the same instance.
   *
   * @param subject  Specify the new subject of the task instance. The subject can be at most 255 characters long.  Note that patching a translated subject is not supported, i.e. GET requests executed on a translated user task do not display the patched text.
   * @return The same instance of this {@link UpdateTaskInstancesPayload} class
   */
  @Nonnull public UpdateTaskInstancesPayload subject( @Nullable final String subject) {
    this.subject = subject;
    return this;
  }

  /**
   * Specify the new subject of the task instance. The subject can be at most 255 characters long.  Note that patching a translated subject is not supported, i.e. GET requests executed on a translated user task do not display the patched text.
   * @return subject  The subject of this {@link UpdateTaskInstancesPayload} instance.
   */
  @Nonnull
  public String getSubject() {
    return subject;
  }

  /**
   * Set the subject of this {@link UpdateTaskInstancesPayload} instance.
   *
   * @param subject  Specify the new subject of the task instance. The subject can be at most 255 characters long.  Note that patching a translated subject is not supported, i.e. GET requests executed on a translated user task do not display the patched text.
   */
  public void setSubject( @Nullable final String subject) {
    this.subject = subject;
  }

  /**
   * Set the description of this {@link UpdateTaskInstancesPayload} instance and return the same instance.
   *
   * @param description  Specify the new description of the task instance. The description can be at most 4000 characters long.  Note that patching a translated description is not supported, i.e. GET requests executed on a translated user task do not display the patched text.
   * @return The same instance of this {@link UpdateTaskInstancesPayload} class
   */
  @Nonnull public UpdateTaskInstancesPayload description( @Nullable final String description) {
    this.description = description;
    return this;
  }

  /**
   * Specify the new description of the task instance. The description can be at most 4000 characters long.  Note that patching a translated description is not supported, i.e. GET requests executed on a translated user task do not display the patched text.
   * @return description  The description of this {@link UpdateTaskInstancesPayload} instance.
   */
  @Nonnull
  public String getDescription() {
    return description;
  }

  /**
   * Set the description of this {@link UpdateTaskInstancesPayload} instance.
   *
   * @param description  Specify the new description of the task instance. The description can be at most 4000 characters long.  Note that patching a translated description is not supported, i.e. GET requests executed on a translated user task do not display the patched text.
   */
  public void setDescription( @Nullable final String description) {
    this.description = description;
  }

  /**
   * Set the recipientUsers of this {@link UpdateTaskInstancesPayload} instance and return the same instance.
   *
   * @param recipientUsers  Specify the new recipient users of the task instance as a comma-separated list. Specify at most 100 recipient users. The ID of a recipient user can be at most 255 characters long.
   * @return The same instance of this {@link UpdateTaskInstancesPayload} class
   */
  @Nonnull public UpdateTaskInstancesPayload recipientUsers( @Nullable final String recipientUsers) {
    this.recipientUsers = recipientUsers;
    return this;
  }

  /**
   * Specify the new recipient users of the task instance as a comma-separated list. Specify at most 100 recipient users. The ID of a recipient user can be at most 255 characters long.
   * @return recipientUsers  The recipientUsers of this {@link UpdateTaskInstancesPayload} instance.
   */
  @Nonnull
  public String getRecipientUsers() {
    return recipientUsers;
  }

  /**
   * Set the recipientUsers of this {@link UpdateTaskInstancesPayload} instance.
   *
   * @param recipientUsers  Specify the new recipient users of the task instance as a comma-separated list. Specify at most 100 recipient users. The ID of a recipient user can be at most 255 characters long.
   */
  public void setRecipientUsers( @Nullable final String recipientUsers) {
    this.recipientUsers = recipientUsers;
  }

  /**
   * Set the recipientGroups of this {@link UpdateTaskInstancesPayload} instance and return the same instance.
   *
   * @param recipientGroups  Specify the new recipient groups of the task instance, as a comma-separated list. Specify at most 100 recipient groups. The ID of a recipient group can be at most 255 characters long.
   * @return The same instance of this {@link UpdateTaskInstancesPayload} class
   */
  @Nonnull public UpdateTaskInstancesPayload recipientGroups( @Nullable final String recipientGroups) {
    this.recipientGroups = recipientGroups;
    return this;
  }

  /**
   * Specify the new recipient groups of the task instance, as a comma-separated list. Specify at most 100 recipient groups. The ID of a recipient group can be at most 255 characters long.
   * @return recipientGroups  The recipientGroups of this {@link UpdateTaskInstancesPayload} instance.
   */
  @Nonnull
  public String getRecipientGroups() {
    return recipientGroups;
  }

  /**
   * Set the recipientGroups of this {@link UpdateTaskInstancesPayload} instance.
   *
   * @param recipientGroups  Specify the new recipient groups of the task instance, as a comma-separated list. Specify at most 100 recipient groups. The ID of a recipient group can be at most 255 characters long.
   */
  public void setRecipientGroups( @Nullable final String recipientGroups) {
    this.recipientGroups = recipientGroups;
  }

  /**
   * Set the processor of this {@link UpdateTaskInstancesPayload} instance and return the same instance.
   *
   * @param processor  Specify the new processor of the task instance. The ID of the processor can be at most 255 characters long and must not contain commas.
   * @return The same instance of this {@link UpdateTaskInstancesPayload} class
   */
  @Nonnull public UpdateTaskInstancesPayload processor( @Nullable final String processor) {
    this.processor = processor;
    return this;
  }

  /**
   * Specify the new processor of the task instance. The ID of the processor can be at most 255 characters long and must not contain commas.
   * @return processor  The processor of this {@link UpdateTaskInstancesPayload} instance.
   */
  @Nonnull
  public String getProcessor() {
    return processor;
  }

  /**
   * Set the processor of this {@link UpdateTaskInstancesPayload} instance.
   *
   * @param processor  Specify the new processor of the task instance. The ID of the processor can be at most 255 characters long and must not contain commas.
   */
  public void setProcessor( @Nullable final String processor) {
    this.processor = processor;
  }

  /**
   * Set the dueDate of this {@link UpdateTaskInstancesPayload} instance and return the same instance.
   *
   * @param dueDate  Specify the new due date of the task instance.
   * @return The same instance of this {@link UpdateTaskInstancesPayload} class
   */
  @Nonnull public UpdateTaskInstancesPayload dueDate( @Nullable final OffsetDateTime dueDate) {
    this.dueDate = dueDate;
    return this;
  }

  /**
   * Specify the new due date of the task instance.
   * @return dueDate  The dueDate of this {@link UpdateTaskInstancesPayload} instance.
   */
  @Nonnull
  public OffsetDateTime getDueDate() {
    return dueDate;
  }

  /**
   * Set the dueDate of this {@link UpdateTaskInstancesPayload} instance.
   *
   * @param dueDate  Specify the new due date of the task instance.
   */
  public void setDueDate( @Nullable final OffsetDateTime dueDate) {
    this.dueDate = dueDate;
  }

  /**
   * Set the priority of this {@link UpdateTaskInstancesPayload} instance and return the same instance.
   *
   * @param priority  Specify the new priority of the task instance.
   * @return The same instance of this {@link UpdateTaskInstancesPayload} class
   */
  @Nonnull public UpdateTaskInstancesPayload priority( @Nullable final PriorityEnum priority) {
    this.priority = priority;
    return this;
  }

  /**
   * Specify the new priority of the task instance.
   * @return priority  The priority of this {@link UpdateTaskInstancesPayload} instance.
   */
  @Nonnull
  public PriorityEnum getPriority() {
    return priority;
  }

  /**
   * Set the priority of this {@link UpdateTaskInstancesPayload} instance.
   *
   * @param priority  Specify the new priority of the task instance.
   */
  public void setPriority( @Nullable final PriorityEnum priority) {
    this.priority = priority;
  }

  /**
   * Set the confidenceLevel of this {@link UpdateTaskInstancesPayload} instance and return the same instance.
   *
   * @param confidenceLevel  Specify the confidenceLevel for a task instance. The value must be between 0.0 and 1.0. To delete the confidenceLevel, specify a value of -1.0.
   * @return The same instance of this {@link UpdateTaskInstancesPayload} class
   */
  @Nonnull public UpdateTaskInstancesPayload confidenceLevel( @Nullable final Double confidenceLevel) {
    this.confidenceLevel = confidenceLevel;
    return this;
  }

  /**
   * Specify the confidenceLevel for a task instance. The value must be between 0.0 and 1.0. To delete the confidenceLevel, specify a value of -1.0.
   * @return confidenceLevel  The confidenceLevel of this {@link UpdateTaskInstancesPayload} instance.
   */
  @Nonnull
  public Double getConfidenceLevel() {
    return confidenceLevel;
  }

  /**
   * Set the confidenceLevel of this {@link UpdateTaskInstancesPayload} instance.
   *
   * @param confidenceLevel  Specify the confidenceLevel for a task instance. The value must be between 0.0 and 1.0. To delete the confidenceLevel, specify a value of -1.0.
   */
  public void setConfidenceLevel( @Nullable final Double confidenceLevel) {
    this.confidenceLevel = confidenceLevel;
  }

  /**
   * Set the userInterfaceUri of this {@link UpdateTaskInstancesPayload} instance and return the same instance.
   *
   * @param userInterfaceUri  Specify the new URI for the user interface of the task instance.
   * @return The same instance of this {@link UpdateTaskInstancesPayload} class
   */
  @Nonnull public UpdateTaskInstancesPayload userInterfaceUri( @Nullable final String userInterfaceUri) {
    this.userInterfaceUri = userInterfaceUri;
    return this;
  }

  /**
   * Specify the new URI for the user interface of the task instance.
   * @return userInterfaceUri  The userInterfaceUri of this {@link UpdateTaskInstancesPayload} instance.
   */
  @Nonnull
  public String getUserInterfaceUri() {
    return userInterfaceUri;
  }

  /**
   * Set the userInterfaceUri of this {@link UpdateTaskInstancesPayload} instance.
   *
   * @param userInterfaceUri  Specify the new URI for the user interface of the task instance.
   */
  public void setUserInterfaceUri( @Nullable final String userInterfaceUri) {
    this.userInterfaceUri = userInterfaceUri;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link UpdateTaskInstancesPayload}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link UpdateTaskInstancesPayload} instance.
   * @deprecated Use {@link #toMap()} instead.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField( @Nonnull final String name ) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("UpdateTaskInstancesPayload has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link UpdateTaskInstancesPayload} instance including unrecognized properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap()
  {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if( id != null ) declaredFields.put("id", id);
    if( subject != null ) declaredFields.put("subject", subject);
    if( description != null ) declaredFields.put("description", description);
    if( recipientUsers != null ) declaredFields.put("recipientUsers", recipientUsers);
    if( recipientGroups != null ) declaredFields.put("recipientGroups", recipientGroups);
    if( processor != null ) declaredFields.put("processor", processor);
    if( dueDate != null ) declaredFields.put("dueDate", dueDate);
    if( priority != null ) declaredFields.put("priority", priority);
    if( confidenceLevel != null ) declaredFields.put("confidenceLevel", confidenceLevel);
    if( userInterfaceUri != null ) declaredFields.put("userInterfaceUri", userInterfaceUri);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link UpdateTaskInstancesPayload} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final UpdateTaskInstancesPayload updateTaskInstancesPayload = (UpdateTaskInstancesPayload) o;
    return Objects.equals(this.cloudSdkCustomFields, updateTaskInstancesPayload.cloudSdkCustomFields) &&
        Objects.equals(this.id, updateTaskInstancesPayload.id) &&
        Objects.equals(this.subject, updateTaskInstancesPayload.subject) &&
        Objects.equals(this.description, updateTaskInstancesPayload.description) &&
        Objects.equals(this.recipientUsers, updateTaskInstancesPayload.recipientUsers) &&
        Objects.equals(this.recipientGroups, updateTaskInstancesPayload.recipientGroups) &&
        Objects.equals(this.processor, updateTaskInstancesPayload.processor) &&
        Objects.equals(this.dueDate, updateTaskInstancesPayload.dueDate) &&
        Objects.equals(this.priority, updateTaskInstancesPayload.priority) &&
        Objects.equals(this.confidenceLevel, updateTaskInstancesPayload.confidenceLevel) &&
        Objects.equals(this.userInterfaceUri, updateTaskInstancesPayload.userInterfaceUri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, subject, description, recipientUsers, recipientGroups, processor, dueDate, priority, confidenceLevel, userInterfaceUri, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class UpdateTaskInstancesPayload {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    recipientUsers: ").append(toIndentedString(recipientUsers)).append("\n");
    sb.append("    recipientGroups: ").append(toIndentedString(recipientGroups)).append("\n");
    sb.append("    processor: ").append(toIndentedString(processor)).append("\n");
    sb.append("    dueDate: ").append(toIndentedString(dueDate)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    confidenceLevel: ").append(toIndentedString(confidenceLevel)).append("\n");
    sb.append("    userInterfaceUri: ").append(toIndentedString(userInterfaceUri)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

