

/*
 * Workflow
 * This API uses the workflow capability of SAP Build Process Automation. With the API, you can, for example, start new workflow instances and work with tasks.  Note: These APIs are designed for loosely coupled clients. This means:  - If SAP Build Process Automation adds fields to responses, the API version number does not increase. Your client must ignore new fields. - The order of fields in responses and of entries in arrays may change. This applies unless the API provides an explicit means to specify the desired order. 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.openapi.sbpaworkflow.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * Information about the referenced subflow.
 */
// CHECKSTYLE:OFF
public class WorkflowInstanceExecutionLogSubflow 
// CHECKSTYLE:ON
{
  @JsonProperty("workflowInstanceId")
  private String workflowInstanceId;

  @JsonProperty("workflowDefinitionId")
  private String workflowDefinitionId;

  @JsonProperty("businessKey")
  private String businessKey;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /**
   * Set the workflowInstanceId of this {@link WorkflowInstanceExecutionLogSubflow} instance and return the same instance.
   *
   * @param workflowInstanceId  The ID of the workflow instance. The workflow instance ID is 36 characters long.
   * @return The same instance of this {@link WorkflowInstanceExecutionLogSubflow} class
   */
  @Nonnull public WorkflowInstanceExecutionLogSubflow workflowInstanceId( @Nullable final String workflowInstanceId) {
    this.workflowInstanceId = workflowInstanceId;
    return this;
  }

  /**
   * The ID of the workflow instance. The workflow instance ID is 36 characters long.
   * @return workflowInstanceId  The workflowInstanceId of this {@link WorkflowInstanceExecutionLogSubflow} instance.
   */
  @Nonnull
  public String getWorkflowInstanceId() {
    return workflowInstanceId;
  }

  /**
   * Set the workflowInstanceId of this {@link WorkflowInstanceExecutionLogSubflow} instance.
   *
   * @param workflowInstanceId  The ID of the workflow instance. The workflow instance ID is 36 characters long.
   */
  public void setWorkflowInstanceId( @Nullable final String workflowInstanceId) {
    this.workflowInstanceId = workflowInstanceId;
  }

  /**
   * Set the workflowDefinitionId of this {@link WorkflowInstanceExecutionLogSubflow} instance and return the same instance.
   *
   * @param workflowDefinitionId  The ID of the workflow definition. The workflow definition ID is at most 255 characters long.
   * @return The same instance of this {@link WorkflowInstanceExecutionLogSubflow} class
   */
  @Nonnull public WorkflowInstanceExecutionLogSubflow workflowDefinitionId( @Nullable final String workflowDefinitionId) {
    this.workflowDefinitionId = workflowDefinitionId;
    return this;
  }

  /**
   * The ID of the workflow definition. The workflow definition ID is at most 255 characters long.
   * @return workflowDefinitionId  The workflowDefinitionId of this {@link WorkflowInstanceExecutionLogSubflow} instance.
   */
  @Nonnull
  public String getWorkflowDefinitionId() {
    return workflowDefinitionId;
  }

  /**
   * Set the workflowDefinitionId of this {@link WorkflowInstanceExecutionLogSubflow} instance.
   *
   * @param workflowDefinitionId  The ID of the workflow definition. The workflow definition ID is at most 255 characters long.
   */
  public void setWorkflowDefinitionId( @Nullable final String workflowDefinitionId) {
    this.workflowDefinitionId = workflowDefinitionId;
  }

  /**
   * Set the businessKey of this {@link WorkflowInstanceExecutionLogSubflow} instance and return the same instance.
   *
   * @param businessKey  The business key of the workflow instance, in UTF-8 encoding. The business key of a workflow instance is limited to 255 characters.
   * @return The same instance of this {@link WorkflowInstanceExecutionLogSubflow} class
   */
  @Nonnull public WorkflowInstanceExecutionLogSubflow businessKey( @Nullable final String businessKey) {
    this.businessKey = businessKey;
    return this;
  }

  /**
   * The business key of the workflow instance, in UTF-8 encoding. The business key of a workflow instance is limited to 255 characters.
   * @return businessKey  The businessKey of this {@link WorkflowInstanceExecutionLogSubflow} instance.
   */
  @Nonnull
  public String getBusinessKey() {
    return businessKey;
  }

  /**
   * Set the businessKey of this {@link WorkflowInstanceExecutionLogSubflow} instance.
   *
   * @param businessKey  The business key of the workflow instance, in UTF-8 encoding. The business key of a workflow instance is limited to 255 characters.
   */
  public void setBusinessKey( @Nullable final String businessKey) {
    this.businessKey = businessKey;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link WorkflowInstanceExecutionLogSubflow}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link WorkflowInstanceExecutionLogSubflow} instance.
   * @deprecated Use {@link #toMap()} instead.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField( @Nonnull final String name ) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("WorkflowInstanceExecutionLogSubflow has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link WorkflowInstanceExecutionLogSubflow} instance including unrecognized properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap()
  {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if( workflowInstanceId != null ) declaredFields.put("workflowInstanceId", workflowInstanceId);
    if( workflowDefinitionId != null ) declaredFields.put("workflowDefinitionId", workflowDefinitionId);
    if( businessKey != null ) declaredFields.put("businessKey", businessKey);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link WorkflowInstanceExecutionLogSubflow} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final WorkflowInstanceExecutionLogSubflow workflowInstanceExecutionLogSubflow = (WorkflowInstanceExecutionLogSubflow) o;
    return Objects.equals(this.cloudSdkCustomFields, workflowInstanceExecutionLogSubflow.cloudSdkCustomFields) &&
        Objects.equals(this.workflowInstanceId, workflowInstanceExecutionLogSubflow.workflowInstanceId) &&
        Objects.equals(this.workflowDefinitionId, workflowInstanceExecutionLogSubflow.workflowDefinitionId) &&
        Objects.equals(this.businessKey, workflowInstanceExecutionLogSubflow.businessKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(workflowInstanceId, workflowDefinitionId, businessKey, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowInstanceExecutionLogSubflow {\n");
    sb.append("    workflowInstanceId: ").append(toIndentedString(workflowInstanceId)).append("\n");
    sb.append("    workflowDefinitionId: ").append(toIndentedString(workflowDefinitionId)).append("\n");
    sb.append("    businessKey: ").append(toIndentedString(businessKey)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

