

/*
 * Inbox
 * This API provides the functionality for building \"own inbox\" capabilities on top of SAP Build Process Automation. It is based on the task consumption model (TCM) as documented in SAP Note [2304317](https://launchpad.support.sap.com/#/notes/2304317/E).  Only users who have the ProcessAutomationParticipant role assigned are able to use the Inbox API.  SAP Build Process Automation currently supports only a subset of the Task Consumption Model capabilities. Only the functionality included in this document is available.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.openapi.sbpaworkflow.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sap.openapi.sbpaworkflow.model.TaskInstanceDDescription;
import com.sap.openapi.sbpaworkflow.model.WorkflowLogMetadata;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * WorkflowLogsDResultsInner
 */
// CHECKSTYLE:OFF
public class WorkflowLogsDResultsInner 
// CHECKSTYLE:ON
{
  @JsonProperty("__metadata")
  private WorkflowLogMetadata metadata;

  @JsonProperty("InstanceID")
  private String instanceID;

  @JsonProperty("SAP__Origin")
  private String saPOrigin = "NA";

  @JsonProperty("EventOrder")
  private String eventOrder;

  @JsonProperty("ReferenceInstanceID")
  private String referenceInstanceID;

  @JsonProperty("PerformedBy")
  private String performedBy;

  @JsonProperty("PerformedByName")
  private String performedByName;

  /**
   * Latest status of the work item.
   */
  public enum StatusEnum {
    /**
    * The WORKFLOW_STARTED option of this WorkflowLogsDResultsInner
    */
    WORKFLOW_STARTED("WORKFLOW_STARTED"),
    
    /**
    * The READY option of this WorkflowLogsDResultsInner
    */
    READY("READY"),
    
    /**
    * The IN_PROGRESS option of this WorkflowLogsDResultsInner
    */
    IN_PROGRESS("IN_PROGRESS"),
    
    /**
    * The COMPLETED option of this WorkflowLogsDResultsInner
    */
    COMPLETED("COMPLETED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    /**
    * Get the value of the enum
    * @return The enum value
    */
    @JsonValue
    @Nonnull public String getValue() {
      return value;
    }

    /**
    * Get the String value of the enum value.
    * @return The enum value as String
    */
    @Override
    @Nonnull public String toString() {
      return String.valueOf(value);
    }

    /**
    * Get the enum value from a String value
    * @param value The String value
    * @return The enum value of type WorkflowLogsDResultsInner
    */
    @JsonCreator
    @Nonnull public static StatusEnum fromValue(@Nonnull final String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  @JsonProperty("Status")
  private StatusEnum status;

  @JsonProperty("Timestamp")
  private OffsetDateTime timestamp;

  @JsonProperty("Description")
  private String description;

  @JsonProperty("SupportsNavigation")
  private Boolean supportsNavigation = false;

  @JsonProperty("Result")
  private String result;

  /**
   * Nature for the outcome of the work item.
   */
  public enum ResultTypeEnum {
    /**
    * The POSITIVE option of this WorkflowLogsDResultsInner
    */
    POSITIVE("POSITIVE"),
    
    /**
    * The NEUTRAL option of this WorkflowLogsDResultsInner
    */
    NEUTRAL("NEUTRAL"),
    
    /**
    * The NEGATIVE option of this WorkflowLogsDResultsInner
    */
    NEGATIVE("NEGATIVE");

    private String value;

    ResultTypeEnum(String value) {
      this.value = value;
    }

    /**
    * Get the value of the enum
    * @return The enum value
    */
    @JsonValue
    @Nonnull public String getValue() {
      return value;
    }

    /**
    * Get the String value of the enum value.
    * @return The enum value as String
    */
    @Override
    @Nonnull public String toString() {
      return String.valueOf(value);
    }

    /**
    * Get the enum value from a String value
    * @param value The String value
    * @return The enum value of type WorkflowLogsDResultsInner
    */
    @JsonCreator
    @Nonnull public static ResultTypeEnum fromValue(@Nonnull final String value) {
      for (ResultTypeEnum b : ResultTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  @JsonProperty("ResultType")
  private ResultTypeEnum resultType;

  @JsonProperty("CreationTimestamp")
  private OffsetDateTime creationTimestamp;

  @JsonProperty("EndTimestamp")
  private OffsetDateTime endTimestamp;

  @JsonProperty("PerformedByDetails")
  private TaskInstanceDDescription performedByDetails;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /**
   * Set the metadata of this {@link WorkflowLogsDResultsInner} instance and return the same instance.
   *
   * @param metadata  The metadata of this {@link WorkflowLogsDResultsInner}
   * @return The same instance of this {@link WorkflowLogsDResultsInner} class
   */
  @Nonnull public WorkflowLogsDResultsInner metadata( @Nullable final WorkflowLogMetadata metadata) {
    this.metadata = metadata;
    return this;
  }

  /**
   * Get metadata
   * @return metadata  The metadata of this {@link WorkflowLogsDResultsInner} instance.
   */
  @Nonnull
  public WorkflowLogMetadata getMetadata() {
    return metadata;
  }

  /**
   * Set the metadata of this {@link WorkflowLogsDResultsInner} instance.
   *
   * @param metadata  The metadata of this {@link WorkflowLogsDResultsInner}
   */
  public void setMetadata( @Nullable final WorkflowLogMetadata metadata) {
    this.metadata = metadata;
  }

  /**
   * Set the instanceID of this {@link WorkflowLogsDResultsInner} instance and return the same instance.
   *
   * @param instanceID  The ID of the task to which the workflow log belongs.
   * @return The same instance of this {@link WorkflowLogsDResultsInner} class
   */
  @Nonnull public WorkflowLogsDResultsInner instanceID( @Nullable final String instanceID) {
    this.instanceID = instanceID;
    return this;
  }

  /**
   * The ID of the task to which the workflow log belongs.
   * @return instanceID  The instanceID of this {@link WorkflowLogsDResultsInner} instance.
   */
  @Nonnull
  public String getInstanceID() {
    return instanceID;
  }

  /**
   * Set the instanceID of this {@link WorkflowLogsDResultsInner} instance.
   *
   * @param instanceID  The ID of the task to which the workflow log belongs.
   */
  public void setInstanceID( @Nullable final String instanceID) {
    this.instanceID = instanceID;
  }

  /**
   * Set the saPOrigin of this {@link WorkflowLogsDResultsInner} instance and return the same instance.
   *
   * @param saPOrigin  The SID discriminator. Set to &#39;NA&#39; for all entities. For more information, see the Task Consumption Model documentation in SAP Note [2304317](https://launchpad.support.sap.com/#/notes/2304317/E).
   * @return The same instance of this {@link WorkflowLogsDResultsInner} class
   */
  @Nonnull public WorkflowLogsDResultsInner saPOrigin( @Nullable final String saPOrigin) {
    this.saPOrigin = saPOrigin;
    return this;
  }

  /**
   * The SID discriminator. Set to &#39;NA&#39; for all entities. For more information, see the Task Consumption Model documentation in SAP Note [2304317](https://launchpad.support.sap.com/#/notes/2304317/E).
   * @return saPOrigin  The saPOrigin of this {@link WorkflowLogsDResultsInner} instance.
   */
  @Nonnull
  public String getSaPOrigin() {
    return saPOrigin;
  }

  /**
   * Set the saPOrigin of this {@link WorkflowLogsDResultsInner} instance.
   *
   * @param saPOrigin  The SID discriminator. Set to &#39;NA&#39; for all entities. For more information, see the Task Consumption Model documentation in SAP Note [2304317](https://launchpad.support.sap.com/#/notes/2304317/E).
   */
  public void setSaPOrigin( @Nullable final String saPOrigin) {
    this.saPOrigin = saPOrigin;
  }

  /**
   * Set the eventOrder of this {@link WorkflowLogsDResultsInner} instance and return the same instance.
   *
   * @param eventOrder  The order in which the events have been processed for a workflow. The value is a linearly increasing number. It starts at zero per workflow instance.
   * @return The same instance of this {@link WorkflowLogsDResultsInner} class
   */
  @Nonnull public WorkflowLogsDResultsInner eventOrder( @Nullable final String eventOrder) {
    this.eventOrder = eventOrder;
    return this;
  }

  /**
   * The order in which the events have been processed for a workflow. The value is a linearly increasing number. It starts at zero per workflow instance.
   * @return eventOrder  The eventOrder of this {@link WorkflowLogsDResultsInner} instance.
   */
  @Nonnull
  public String getEventOrder() {
    return eventOrder;
  }

  /**
   * Set the eventOrder of this {@link WorkflowLogsDResultsInner} instance.
   *
   * @param eventOrder  The order in which the events have been processed for a workflow. The value is a linearly increasing number. It starts at zero per workflow instance.
   */
  public void setEventOrder( @Nullable final String eventOrder) {
    this.eventOrder = eventOrder;
  }

  /**
   * Set the referenceInstanceID of this {@link WorkflowLogsDResultsInner} instance and return the same instance.
   *
   * @param referenceInstanceID  The ID of the task instance for which the event has been triggered.
   * @return The same instance of this {@link WorkflowLogsDResultsInner} class
   */
  @Nonnull public WorkflowLogsDResultsInner referenceInstanceID( @Nullable final String referenceInstanceID) {
    this.referenceInstanceID = referenceInstanceID;
    return this;
  }

  /**
   * The ID of the task instance for which the event has been triggered.
   * @return referenceInstanceID  The referenceInstanceID of this {@link WorkflowLogsDResultsInner} instance.
   */
  @Nonnull
  public String getReferenceInstanceID() {
    return referenceInstanceID;
  }

  /**
   * Set the referenceInstanceID of this {@link WorkflowLogsDResultsInner} instance.
   *
   * @param referenceInstanceID  The ID of the task instance for which the event has been triggered.
   */
  public void setReferenceInstanceID( @Nullable final String referenceInstanceID) {
    this.referenceInstanceID = referenceInstanceID;
  }

  /**
   * Set the performedBy of this {@link WorkflowLogsDResultsInner} instance and return the same instance.
   *
   * @param performedBy  The unique ID of the agent who performed the action on the work item.
   * @return The same instance of this {@link WorkflowLogsDResultsInner} class
   */
  @Nonnull public WorkflowLogsDResultsInner performedBy( @Nullable final String performedBy) {
    this.performedBy = performedBy;
    return this;
  }

  /**
   * The unique ID of the agent who performed the action on the work item.
   * @return performedBy  The performedBy of this {@link WorkflowLogsDResultsInner} instance.
   */
  @Nonnull
  public String getPerformedBy() {
    return performedBy;
  }

  /**
   * Set the performedBy of this {@link WorkflowLogsDResultsInner} instance.
   *
   * @param performedBy  The unique ID of the agent who performed the action on the work item.
   */
  public void setPerformedBy( @Nullable final String performedBy) {
    this.performedBy = performedBy;
  }

  /**
   * Set the performedByName of this {@link WorkflowLogsDResultsInner} instance and return the same instance.
   *
   * @param performedByName  Currently it is the same value as &#39;PerformedBy&#39;. In future it will contain the name of the agent who performed the action on the work item.
   * @return The same instance of this {@link WorkflowLogsDResultsInner} class
   */
  @Nonnull public WorkflowLogsDResultsInner performedByName( @Nullable final String performedByName) {
    this.performedByName = performedByName;
    return this;
  }

  /**
   * Currently it is the same value as &#39;PerformedBy&#39;. In future it will contain the name of the agent who performed the action on the work item.
   * @return performedByName  The performedByName of this {@link WorkflowLogsDResultsInner} instance.
   */
  @Nonnull
  public String getPerformedByName() {
    return performedByName;
  }

  /**
   * Set the performedByName of this {@link WorkflowLogsDResultsInner} instance.
   *
   * @param performedByName  Currently it is the same value as &#39;PerformedBy&#39;. In future it will contain the name of the agent who performed the action on the work item.
   */
  public void setPerformedByName( @Nullable final String performedByName) {
    this.performedByName = performedByName;
  }

  /**
   * Set the status of this {@link WorkflowLogsDResultsInner} instance and return the same instance.
   *
   * @param status  Latest status of the work item.
   * @return The same instance of this {@link WorkflowLogsDResultsInner} class
   */
  @Nonnull public WorkflowLogsDResultsInner status( @Nullable final StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Latest status of the work item.
   * @return status  The status of this {@link WorkflowLogsDResultsInner} instance.
   */
  @Nonnull
  public StatusEnum getStatus() {
    return status;
  }

  /**
   * Set the status of this {@link WorkflowLogsDResultsInner} instance.
   *
   * @param status  Latest status of the work item.
   */
  public void setStatus( @Nullable final StatusEnum status) {
    this.status = status;
  }

  /**
   * Set the timestamp of this {@link WorkflowLogsDResultsInner} instance and return the same instance.
   *
   * @param timestamp  Indication when the event was logged.
   * @return The same instance of this {@link WorkflowLogsDResultsInner} class
   */
  @Nonnull public WorkflowLogsDResultsInner timestamp( @Nullable final OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  /**
   * Indication when the event was logged.
   * @return timestamp  The timestamp of this {@link WorkflowLogsDResultsInner} instance.
   */
  @Nonnull
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }

  /**
   * Set the timestamp of this {@link WorkflowLogsDResultsInner} instance.
   *
   * @param timestamp  Indication when the event was logged.
   */
  public void setTimestamp( @Nullable final OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }

  /**
   * Set the description of this {@link WorkflowLogsDResultsInner} instance and return the same instance.
   *
   * @param description  Description text of the work item.
   * @return The same instance of this {@link WorkflowLogsDResultsInner} class
   */
  @Nonnull public WorkflowLogsDResultsInner description( @Nullable final String description) {
    this.description = description;
    return this;
  }

  /**
   * Description text of the work item.
   * @return description  The description of this {@link WorkflowLogsDResultsInner} instance.
   */
  @Nonnull
  public String getDescription() {
    return description;
  }

  /**
   * Set the description of this {@link WorkflowLogsDResultsInner} instance.
   *
   * @param description  Description text of the work item.
   */
  public void setDescription( @Nullable final String description) {
    this.description = description;
  }

  /**
   * Set the supportsNavigation of this {@link WorkflowLogsDResultsInner} instance and return the same instance.
   *
   * @param supportsNavigation  Flag that determines whether the user can click the description. Currently, this will always return false. This is subject to change.
   * @return The same instance of this {@link WorkflowLogsDResultsInner} class
   */
  @Nonnull public WorkflowLogsDResultsInner supportsNavigation( @Nullable final Boolean supportsNavigation) {
    this.supportsNavigation = supportsNavigation;
    return this;
  }

  /**
   * Flag that determines whether the user can click the description. Currently, this will always return false. This is subject to change.
   * @return supportsNavigation  The supportsNavigation of this {@link WorkflowLogsDResultsInner} instance.
   */
  @Nonnull
  public Boolean isSupportsNavigation() {
    return supportsNavigation;
  }

  /**
   * Set the supportsNavigation of this {@link WorkflowLogsDResultsInner} instance.
   *
   * @param supportsNavigation  Flag that determines whether the user can click the description. Currently, this will always return false. This is subject to change.
   */
  public void setSupportsNavigation( @Nullable final Boolean supportsNavigation) {
    this.supportsNavigation = supportsNavigation;
  }

  /**
   * Set the result of this {@link WorkflowLogsDResultsInner} instance and return the same instance.
   *
   * @param result  Outcome of the work item.
   * @return The same instance of this {@link WorkflowLogsDResultsInner} class
   */
  @Nonnull public WorkflowLogsDResultsInner result( @Nullable final String result) {
    this.result = result;
    return this;
  }

  /**
   * Outcome of the work item.
   * @return result  The result of this {@link WorkflowLogsDResultsInner} instance.
   */
  @Nonnull
  public String getResult() {
    return result;
  }

  /**
   * Set the result of this {@link WorkflowLogsDResultsInner} instance.
   *
   * @param result  Outcome of the work item.
   */
  public void setResult( @Nullable final String result) {
    this.result = result;
  }

  /**
   * Set the resultType of this {@link WorkflowLogsDResultsInner} instance and return the same instance.
   *
   * @param resultType  Nature for the outcome of the work item.
   * @return The same instance of this {@link WorkflowLogsDResultsInner} class
   */
  @Nonnull public WorkflowLogsDResultsInner resultType( @Nullable final ResultTypeEnum resultType) {
    this.resultType = resultType;
    return this;
  }

  /**
   * Nature for the outcome of the work item.
   * @return resultType  The resultType of this {@link WorkflowLogsDResultsInner} instance.
   */
  @Nonnull
  public ResultTypeEnum getResultType() {
    return resultType;
  }

  /**
   * Set the resultType of this {@link WorkflowLogsDResultsInner} instance.
   *
   * @param resultType  Nature for the outcome of the work item.
   */
  public void setResultType( @Nullable final ResultTypeEnum resultType) {
    this.resultType = resultType;
  }

  /**
   * Set the creationTimestamp of this {@link WorkflowLogsDResultsInner} instance and return the same instance.
   *
   * @param creationTimestamp  Indication when the workflow was initiated.
   * @return The same instance of this {@link WorkflowLogsDResultsInner} class
   */
  @Nonnull public WorkflowLogsDResultsInner creationTimestamp( @Nullable final OffsetDateTime creationTimestamp) {
    this.creationTimestamp = creationTimestamp;
    return this;
  }

  /**
   * Indication when the workflow was initiated.
   * @return creationTimestamp  The creationTimestamp of this {@link WorkflowLogsDResultsInner} instance.
   */
  @Nonnull
  public OffsetDateTime getCreationTimestamp() {
    return creationTimestamp;
  }

  /**
   * Set the creationTimestamp of this {@link WorkflowLogsDResultsInner} instance.
   *
   * @param creationTimestamp  Indication when the workflow was initiated.
   */
  public void setCreationTimestamp( @Nullable final OffsetDateTime creationTimestamp) {
    this.creationTimestamp = creationTimestamp;
  }

  /**
   * Set the endTimestamp of this {@link WorkflowLogsDResultsInner} instance and return the same instance.
   *
   * @param endTimestamp  Indication by when the workflow should be completed. For a COMPLETED task, it will be the completion time of the task. For an open task, for which a deadline is defined, it is either the &#39;Latest End&#39; or the &#39;Requested End&#39;.
   * @return The same instance of this {@link WorkflowLogsDResultsInner} class
   */
  @Nonnull public WorkflowLogsDResultsInner endTimestamp( @Nullable final OffsetDateTime endTimestamp) {
    this.endTimestamp = endTimestamp;
    return this;
  }

  /**
   * Indication by when the workflow should be completed. For a COMPLETED task, it will be the completion time of the task. For an open task, for which a deadline is defined, it is either the &#39;Latest End&#39; or the &#39;Requested End&#39;.
   * @return endTimestamp  The endTimestamp of this {@link WorkflowLogsDResultsInner} instance.
   */
  @Nonnull
  public OffsetDateTime getEndTimestamp() {
    return endTimestamp;
  }

  /**
   * Set the endTimestamp of this {@link WorkflowLogsDResultsInner} instance.
   *
   * @param endTimestamp  Indication by when the workflow should be completed. For a COMPLETED task, it will be the completion time of the task. For an open task, for which a deadline is defined, it is either the &#39;Latest End&#39; or the &#39;Requested End&#39;.
   */
  public void setEndTimestamp( @Nullable final OffsetDateTime endTimestamp) {
    this.endTimestamp = endTimestamp;
  }

  /**
   * Set the performedByDetails of this {@link WorkflowLogsDResultsInner} instance and return the same instance.
   *
   * @param performedByDetails  The performedByDetails of this {@link WorkflowLogsDResultsInner}
   * @return The same instance of this {@link WorkflowLogsDResultsInner} class
   */
  @Nonnull public WorkflowLogsDResultsInner performedByDetails( @Nullable final TaskInstanceDDescription performedByDetails) {
    this.performedByDetails = performedByDetails;
    return this;
  }

  /**
   * Get performedByDetails
   * @return performedByDetails  The performedByDetails of this {@link WorkflowLogsDResultsInner} instance.
   */
  @Nonnull
  public TaskInstanceDDescription getPerformedByDetails() {
    return performedByDetails;
  }

  /**
   * Set the performedByDetails of this {@link WorkflowLogsDResultsInner} instance.
   *
   * @param performedByDetails  The performedByDetails of this {@link WorkflowLogsDResultsInner}
   */
  public void setPerformedByDetails( @Nullable final TaskInstanceDDescription performedByDetails) {
    this.performedByDetails = performedByDetails;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link WorkflowLogsDResultsInner}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link WorkflowLogsDResultsInner} instance.
   * @deprecated Use {@link #toMap()} instead.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField( @Nonnull final String name ) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("WorkflowLogsDResultsInner has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link WorkflowLogsDResultsInner} instance including unrecognized properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap()
  {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if( metadata != null ) declaredFields.put("metadata", metadata);
    if( instanceID != null ) declaredFields.put("instanceID", instanceID);
    if( saPOrigin != null ) declaredFields.put("saPOrigin", saPOrigin);
    if( eventOrder != null ) declaredFields.put("eventOrder", eventOrder);
    if( referenceInstanceID != null ) declaredFields.put("referenceInstanceID", referenceInstanceID);
    if( performedBy != null ) declaredFields.put("performedBy", performedBy);
    if( performedByName != null ) declaredFields.put("performedByName", performedByName);
    if( status != null ) declaredFields.put("status", status);
    if( timestamp != null ) declaredFields.put("timestamp", timestamp);
    if( description != null ) declaredFields.put("description", description);
    if( supportsNavigation != null ) declaredFields.put("supportsNavigation", supportsNavigation);
    if( result != null ) declaredFields.put("result", result);
    if( resultType != null ) declaredFields.put("resultType", resultType);
    if( creationTimestamp != null ) declaredFields.put("creationTimestamp", creationTimestamp);
    if( endTimestamp != null ) declaredFields.put("endTimestamp", endTimestamp);
    if( performedByDetails != null ) declaredFields.put("performedByDetails", performedByDetails);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link WorkflowLogsDResultsInner} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final WorkflowLogsDResultsInner workflowLogsDResultsInner = (WorkflowLogsDResultsInner) o;
    return Objects.equals(this.cloudSdkCustomFields, workflowLogsDResultsInner.cloudSdkCustomFields) &&
        Objects.equals(this.metadata, workflowLogsDResultsInner.metadata) &&
        Objects.equals(this.instanceID, workflowLogsDResultsInner.instanceID) &&
        Objects.equals(this.saPOrigin, workflowLogsDResultsInner.saPOrigin) &&
        Objects.equals(this.eventOrder, workflowLogsDResultsInner.eventOrder) &&
        Objects.equals(this.referenceInstanceID, workflowLogsDResultsInner.referenceInstanceID) &&
        Objects.equals(this.performedBy, workflowLogsDResultsInner.performedBy) &&
        Objects.equals(this.performedByName, workflowLogsDResultsInner.performedByName) &&
        Objects.equals(this.status, workflowLogsDResultsInner.status) &&
        Objects.equals(this.timestamp, workflowLogsDResultsInner.timestamp) &&
        Objects.equals(this.description, workflowLogsDResultsInner.description) &&
        Objects.equals(this.supportsNavigation, workflowLogsDResultsInner.supportsNavigation) &&
        Objects.equals(this.result, workflowLogsDResultsInner.result) &&
        Objects.equals(this.resultType, workflowLogsDResultsInner.resultType) &&
        Objects.equals(this.creationTimestamp, workflowLogsDResultsInner.creationTimestamp) &&
        Objects.equals(this.endTimestamp, workflowLogsDResultsInner.endTimestamp) &&
        Objects.equals(this.performedByDetails, workflowLogsDResultsInner.performedByDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(metadata, instanceID, saPOrigin, eventOrder, referenceInstanceID, performedBy, performedByName, status, timestamp, description, supportsNavigation, result, resultType, creationTimestamp, endTimestamp, performedByDetails, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowLogsDResultsInner {\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    instanceID: ").append(toIndentedString(instanceID)).append("\n");
    sb.append("    saPOrigin: ").append(toIndentedString(saPOrigin)).append("\n");
    sb.append("    eventOrder: ").append(toIndentedString(eventOrder)).append("\n");
    sb.append("    referenceInstanceID: ").append(toIndentedString(referenceInstanceID)).append("\n");
    sb.append("    performedBy: ").append(toIndentedString(performedBy)).append("\n");
    sb.append("    performedByName: ").append(toIndentedString(performedByName)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    supportsNavigation: ").append(toIndentedString(supportsNavigation)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    resultType: ").append(toIndentedString(resultType)).append("\n");
    sb.append("    creationTimestamp: ").append(toIndentedString(creationTimestamp)).append("\n");
    sb.append("    endTimestamp: ").append(toIndentedString(endTimestamp)).append("\n");
    sb.append("    performedByDetails: ").append(toIndentedString(performedByDetails)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

