

/*
 * Inbox
 * This API provides the functionality for building \"own inbox\" capabilities on top of SAP Build Process Automation. It is based on the task consumption model (TCM) as documented in SAP Note [2304317](https://launchpad.support.sap.com/#/notes/2304317/E).  Only users who have the ProcessAutomationParticipant role assigned are able to use the Inbox API.  SAP Build Process Automation currently supports only a subset of the Task Consumption Model capabilities. Only the functionality included in this document is available.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.openapi.sbpaworkflow.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * WorkflowLogMetadata
 */
// CHECKSTYLE:OFF
public class WorkflowLogMetadata 
// CHECKSTYLE:ON
{
  @JsonProperty("id")
  private String id;

  @JsonProperty("uri")
  private String uri;

  @JsonProperty("type")
  private String type = "com.sap.bpm.wfs.tcm.metadata.WorkflowLog";

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

  /**
   * Set the id of this {@link WorkflowLogMetadata} instance and return the same instance.
   *
   * @param id  The ID of the object.
   * @return The same instance of this {@link WorkflowLogMetadata} class
   */
  @Nonnull public WorkflowLogMetadata id( @Nullable final String id) {
    this.id = id;
    return this;
  }

  /**
   * The ID of the object.
   * @return id  The id of this {@link WorkflowLogMetadata} instance.
   */
  @Nonnull
  public String getId() {
    return id;
  }

  /**
   * Set the id of this {@link WorkflowLogMetadata} instance.
   *
   * @param id  The ID of the object.
   */
  public void setId( @Nullable final String id) {
    this.id = id;
  }

  /**
   * Set the uri of this {@link WorkflowLogMetadata} instance and return the same instance.
   *
   * @param uri  The canonical URI identifying the current entry.
   * @return The same instance of this {@link WorkflowLogMetadata} class
   */
  @Nonnull public WorkflowLogMetadata uri( @Nullable final String uri) {
    this.uri = uri;
    return this;
  }

  /**
   * The canonical URI identifying the current entry.
   * @return uri  The uri of this {@link WorkflowLogMetadata} instance.
   */
  @Nonnull
  public String getUri() {
    return uri;
  }

  /**
   * Set the uri of this {@link WorkflowLogMetadata} instance.
   *
   * @param uri  The canonical URI identifying the current entry.
   */
  public void setUri( @Nullable final String uri) {
    this.uri = uri;
  }

  /**
   * Set the type of this {@link WorkflowLogMetadata} instance and return the same instance.
   *
   * @param type  The name of the EntityType in the data model of the OData service that describes the current entry.
   * @return The same instance of this {@link WorkflowLogMetadata} class
   */
  @Nonnull public WorkflowLogMetadata type( @Nullable final String type) {
    this.type = type;
    return this;
  }

  /**
   * The name of the EntityType in the data model of the OData service that describes the current entry.
   * @return type  The type of this {@link WorkflowLogMetadata} instance.
   */
  @Nonnull
  public String getType() {
    return type;
  }

  /**
   * Set the type of this {@link WorkflowLogMetadata} instance.
   *
   * @param type  The name of the EntityType in the data model of the OData service that describes the current entry.
   */
  public void setType( @Nullable final String type) {
    this.type = type;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link WorkflowLogMetadata}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link WorkflowLogMetadata} instance.
   * @deprecated Use {@link #toMap()} instead.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  @Deprecated
  public Object getCustomField( @Nonnull final String name ) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("WorkflowLogMetadata has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Get the value of all properties of this {@link WorkflowLogMetadata} instance including unrecognized properties.
   *
   * @return The map of all properties
   */
  @JsonIgnore
  @Nonnull
  public Map<String, Object> toMap()
  {
    final Map<String, Object> declaredFields = new LinkedHashMap<>(cloudSdkCustomFields);
    if( id != null ) declaredFields.put("id", id);
    if( uri != null ) declaredFields.put("uri", uri);
    if( type != null ) declaredFields.put("type", type);
    return declaredFields;
  }

  /**
   * Set an unrecognizable property of this {@link WorkflowLogMetadata} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final WorkflowLogMetadata workflowLogMetadata = (WorkflowLogMetadata) o;
    return Objects.equals(this.cloudSdkCustomFields, workflowLogMetadata.cloudSdkCustomFields) &&
        Objects.equals(this.id, workflowLogMetadata.id) &&
        Objects.equals(this.uri, workflowLogMetadata.uri) &&
        Objects.equals(this.type, workflowLogMetadata.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, uri, type, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowLogMetadata {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

