syntax = "proto3";

option java_multiple_files = true;

package com.sap.bfx.valuehelp.grpc;

/*-------------------------------------------------------------------------------------*/

service ValueHelpsService {
  rpc GetValueHelp(GetValueHelpRequest) returns (GetValueHelpResponse);
  rpc GetValueHelpsVersion(GetValueHelpsVersionRequest) returns (GetValueHelpsVersionResponse);
  rpc GetValueHelpDefs(GetValueHelpDefsRequest) returns (GetValueHelpDefsResponse);
  rpc Test(TestRequest) returns (TestResponse);
}

//-----------------------------------------------------------------------------

message GetValueHelpRequest {
  string id = 1;
  string locale = 2;
}

message ValueHelpRow {
  map<string, string> items = 1;
}

message GetValueHelpResponse {
  string id = 1;
  string locale = 2;
  uint64 version = 3;
  string keyKey = 4;
  repeated string valueKey = 5;
  string formatTemplate = 6;
  repeated ValueHelpRow values = 7;
}

//-----------------------------------------------------------------------------

message ValueHelpsVersion {
  string name = 1;
  uint64 version = 2;
}

message GetValueHelpsVersionRequest {
  string locale = 1;
  repeated string valueHelps = 2;
}

message GetValueHelpsVersionResponse {
  repeated ValueHelpsVersion values = 1;
}

//-----------------------------------------------------------------------------

message TestRequest {
  string name = 1;
}

message TestResponse {
  string reply = 1;
}

//-----------------------------------------------------------------------------

message GetValueHelpDefsRequest {
  repeated string ids = 1;
}

message ValueHelpDef {
  string id = 1;
  string description = 2;
  repeated string languages = 3;
  string keyKey = 4;
  repeated string valueKey = 5;
  string formatTemplate = 6;
}

message GetValueHelpDefsResponse {
  repeated ValueHelpDef values = 1;
}