<?xml version="1.0" encoding="UTF-8"?>

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>core-workflow-sbpa</artifactId>
    <name>core-workflow-sbpa</name>

    <parent>
        <groupId>com.sap.build-forms-extension</groupId>
        <artifactId>core-workflow</artifactId>
        <version>0.2.0-SNAPSHOT</version>
    </parent>

    <dependencies>
        <dependency>
            <groupId>com.sap.build-forms-extension</groupId>
            <artifactId>core-framework</artifactId>
            <version>${forms.version}</version>
        </dependency>
        <dependency>
            <groupId>com.sap.cloud.sdk.datamodel</groupId>
            <artifactId>openapi-core</artifactId>
            <version>${sap-cloud-openapi-core.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
<!--
            <plugin>
                <groupId>com.sap.cloud.sdk.datamodel</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>${openapi-generator-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <id>Generate OData SBPA Workflow Inbox classes</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <inputSpec>${project.basedir}/src/main/openapi/SPA_Workflow_Inbox.yaml</inputSpec>
                        </configuration>
                    </execution>
                    <execution>
                        <id>Generate REST SBPA Workflow Runtime classes</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <inputSpec>${project.basedir}/src/main/openapi/SPA_Workflow_Runtime.yaml</inputSpec>
                        </configuration>
                    </execution>
                </executions>
                <configuration>
                    <outputDirectory>${project.basedir}/src/main/java</outputDirectory>
                    <deleteOutputDirectory>false</deleteOutputDirectory>
                    <apiPackage>com.sap.openapi.sbpaworkflow.api</apiPackage>
                    <modelPackage>com.sap.openapi.sbpaworkflow.model</modelPackage>
                    <apiMaturity>released</apiMaturity>
                </configuration>
            </plugin>
-->
        </plugins>
    </build>
</project>
